// ═══ EXTENDED BANKING TERMINOLOGY & CONCEPTS ═══

const BANKING_TERMS_EXT={
title:'Complete Banking & Finance Glossary — 300+ Terms',
categories:[
{
category:'Central Banking & Monetary Policy',
terms:[
{term:'Accommodation',def:'Providing credit or liquidity to banks or borrowers. Central bank "accommodation" = providing reserves to banking system. Loose monetary policy = accommodative stance.'},
{term:'Monetary Base',def:'Currency in circulation + Bank reserves with central bank (M0). Also called high-powered money or reserve money. Multiplied through fractional reserve banking to create broader money supply.'},
{term:'Reserve Requirement',def:'Minimum reserves banks must hold against deposits. In India: CRR = 4%. Changing reserve requirement is a blunt instrument used less frequently than repo rate.'},
{term:'Quantitative Easing (QE)',def:'Central bank creates money to buy long-term assets (government bonds, mortgage securities) when interest rates are already near zero. Expands central bank\'s balance sheet and injects liquidity. Used by US Fed, ECB, Bank of Japan post-2008.'},
{term:'Sterilization',def:'Offsetting the domestic monetary impact of foreign exchange intervention. RBI buys dollars (increasing rupee supply) → sterilizes by selling G-secs (reducing rupee supply). Net effect: exchange rate changes but money supply unchanged.'},
{term:'Monetization of Deficit',def:'Government borrowing directly from central bank by printing money. FRBM prohibits RBI from buying government bonds in primary market. Leads to inflation if excessive.'},
{term:'Seigniorage',def:'Revenue government earns from issuing currency. Difference between face value of currency and cost to produce. Government "profits" from public\'s acceptance of paper as money.'},
{term:'Velocity of Money',def:'How frequently a unit of money is used in transactions within a period. MV=PT (Fisher). High velocity = money circulates quickly. Digital payments increase velocity. If velocity increases without growth in real output, prices rise.'},
{term:'Liquidity Trap',def:'Situation where interest rates are near zero and monetary policy becomes ineffective. Even with zero rates, people prefer holding cash to investment (fear of deflation or negative returns). Keynes first described; Japan experienced in 1990s.'},
{term:'Neutral Interest Rate (r*)',def:'The theoretical interest rate consistent with full employment and stable inflation — neither stimulating nor restraining. Currently estimated at 0.5-1.5% in India. Difficult to observe directly; crucial for monetary policy calibration.'},
{term:'Taylor Principle',def:'For monetary policy to stabilize inflation, interest rate must increase by MORE than the rise in inflation (so the REAL interest rate rises). If rate increases 1:1 with inflation, no stabilizing effect.'},
{term:'Inflation Expectations',def:'Expectations of future inflation formed by households, businesses, and financial markets. If inflation expectations become unanchored (people expect high future inflation), it becomes self-fulfilling through wage demands and price-setting.'},
{term:'Second-Round Effects',def:'When initial supply-side inflation (food/fuel prices) leads to higher wage demands and generalized price increases. Primary concern of central banks — temporary supply shock becomes embedded structural inflation.'},
{term:'Currency Swap',def:'Exchange of principal and interest in one currency for the same in another between two parties. Central bank currency swaps: bilateral arrangements between central banks to exchange currencies. RBI has swaps with neighboring countries to support rupee trade.'},
{term:'Standing Deposit Facility (SDF)',def:'RBI\'s tool to absorb excess rupee liquidity from banks without requiring collateral. Banks can park funds with RBI at SDF rate (25 bps below repo). Introduced April 2022, replacing reverse repo as main absorption instrument.'}
]},{
category:'Credit & Lending',
terms:[
{term:'Adverse Selection',def:'Problem arising from information asymmetry before a transaction. Borrowers know more about their own creditworthiness than lenders. High-risk borrowers have incentive to seek credit; low-risk may be discouraged by high rates. Banks use screening (credit checks, collateral, covenants) to address.'},
{term:'Agency Problem',def:'Conflict of interest when one party (agent) acts on behalf of another (principal) but has different incentives. Bank manager may approve risky loans to meet growth targets even if it harms shareholders and depositors. Solved by: proper incentive alignment, oversight, governance.'},
{term:'ALCO',def:'Asset-Liability Committee. Bank committee responsible for managing the balance sheet risks including interest rate risk, liquidity risk, and forex risk. Meets periodically to review gap analysis, set internal pricing, and approve hedging strategies.'},
{term:'Amortizing Loan',def:'Loan where each payment includes both interest and principal repayment. Early payments are mostly interest; later payments are mostly principal. Home loans, auto loans are amortizing. Reduces outstanding balance with each payment. Opposite: bullet loan (full principal at maturity).'},
{term:'Bridge Financing',def:'Short-term funding to cover a financing gap until permanent financing is arranged. Property developer uses bridge loan between construction completion and final mortgage. Higher interest rate due to short-term and higher-risk nature.'},
{term:'Capital Call',def:'Request by private equity/venture fund to investors to transfer committed capital when needed for investment. Investors must respond quickly; failure to do so = "defaulting LP" with penalties. Also used for bank rights issues.'},
{term:'Consortium Lending',def:'Multiple banks jointly providing a loan to a single borrower, with one bank serving as lead arranger. Each bank takes a portion of the risk and earns proportional income. Used for large infrastructure or corporate loans. Lead arranger coordinates documentation and monitoring.'},
{term:'Covenant',def:'Legally binding condition in a loan agreement. Affirmative covenants: borrower must do something (maintain insurance, provide audited accounts). Negative covenants: borrower must not do something (not exceed debt-equity ratio, not pay dividends if performance weak). Breach = default trigger.'},
{term:'Credit Enhancement',def:'Measures to improve credit quality of a financial instrument, making it more attractive to investors. Methods: Collateral (over-collateralization), Guarantees (government, corporate), Subordination (junior tranches absorb losses first), Letter of Credit, Insurance.'},
{term:'Deficiency Judgment',def:'Court judgment against borrower for the remaining balance after collateral sale doesn\'t cover the debt. If bank sells foreclosed property for ₹50L but loan was ₹70L, deficiency = ₹20L. Bank can pursue borrower for deficiency. SARFAESI enables this without court for many cases.'},
{term:'Deed of Trust',def:'Three-party instrument where borrower (trustor) transfers property title to a trustee who holds it on behalf of the lender (beneficiary) as security for a loan. More common in US for mortgages; India uses mortgage deed.'},
{term:'Drawdown',def:'Withdrawal of funds from a credit facility or loan. Borrower doesn\'t take the full loan at once; draws as needed. Working capital credit lines are usually drawdown facilities. Banks earn commitment fees on undrawn amounts.'},
{term:'Due Diligence',def:'Comprehensive investigation before financial transaction — loan approval, acquisition, IPO. Legal (title, litigation), financial (audited accounts, cash flows), operational (management capability, processes), regulatory (compliance history). Cost of due diligence is shared or borne by the party seeking the transaction.'},
{term:'Escrow Account',def:'Account held by a third party (escrow agent) on behalf of two transacting parties. Funds released only when specified conditions are met. Used in property transactions (buyer deposits earnest money), M&A (part of purchase price held pending warranties), and government schemes (developers\' collection for buyers\' protection under RERA).'},
{term:'Evergreening',def:'Practice of rolling over or renewing loans of distressed borrowers to avoid NPA classification. Bank lends new money to enable repayment of old loan — creates appearance of performing loan without genuine recovery. Distorts asset quality reporting. RBI\'s Asset Quality Review (2015) targeted this practice.'},
{term:'Factoring',def:'Financial service where business sells accounts receivable (invoices) to a factoring company at a discount for immediate cash. Three parties: seller (client), buyer of receivables (factor), original debtor. Recourse factoring: client bears default risk. Non-recourse: factor bears risk. Helps MSMEs with cash flow management.'},
{term:'Grace Period',def:'Period after the payment due date during which the borrower can make payment without penalty or default declaration. Home loan EMI due on 1st; grace period till 10th. Important for borrowers facing temporary cash flow issues.'},
{term:'Guarantee',def:'Promise by third party (guarantor) to pay if principal borrower defaults. Personal guarantee: individual commits personal assets. Corporate guarantee: parent company guarantees subsidiary\'s debt. Government guarantee: sovereign backs certain borrowings. Guarantee reduces credit risk and enables higher loan amounts.'},
{term:'Hard Collateral',def:'Physical asset accepted as loan security — land, building, plant and machinery, vehicles. Distinguished from soft collateral (receivables, inventory). Hard collateral is easier to value and liquidate, preferred by banks for long-term loans.'},
{term:'Impaired Loan',def:'Loan where it is probable that lender cannot collect all amounts due. Under accounting standards (IFRS 9/Ind AS 109), loans are assessed for impairment and Expected Credit Loss (ECL) is calculated and provisioned. Impaired loans may or may not have missed payments yet.'},
{term:'Indemnity',def:'Promise to compensate for loss or damage. Bank indemnity letter: customer indemnifies bank against loss in specific situations (issuing duplicate passbook). Banker\'s indemnity in LC transactions: bank indemnifies correspondent for acting on instructions.'},
{term:'Investment Grade',def:'Credit rating indicating low credit risk — BBB-/Baa3 or higher (S&P/Moody\'s). Bonds rated investment grade can be held by institutional investors (insurance companies, pension funds) with conservative mandates. Below investment grade = "junk" or "high yield." India\'s sovereign rating: BBB- (lowest investment grade).'},
{term:'Joint Venture (JV)',def:'Business arrangement where two or more parties share ownership, control, risk, and profit. Common in infrastructure projects — one party provides capital, another provides land, third provides expertise. JV partners may also jointly guarantee project loans.'},
{term:'Jumbo Loan',def:'Mortgage loan exceeding conforming loan limits (US terminology). In India context: large-value home loans beyond standard categories. Also used loosely for any unusually large loan.'},
{term:'Knock-In / Knock-Out Option',def:'Exotic derivatives that are activated (knock-in) or deactivated (knock-out) when the underlying asset reaches a specified price level (barrier). Used in structured products for currency hedging with lower premium.'},
{term:'Lien',def:'Legal right of creditor to retain possession of or claim against debtor\'s property until debt is paid. Bank has lien over all assets in customer\'s account. Banker\'s right of general lien: can retain any property in bank\'s possession until all dues are cleared.'},
{term:'Liquidity Premium',def:'Additional return investors demand for holding less liquid assets. Treasury bonds are liquid (easy to sell quickly); private equity is illiquid. Illiquidity premium = difference in returns. Explains why illiquid investments must offer higher returns.'},
{term:'Moral Suasion',def:'Central bank\'s use of persuasion (advice, guidance, informal pressure) to influence banks\' behavior without formal regulatory action. RBI may "suade" banks not to lend to specific sectors or to maintain credit standards without issuing formal directions.'},
{term:'Negative Pledge',def:'Covenant where borrower agrees not to create new security (pledge, charge) on its assets that would rank ahead of existing unsecured creditors. Protects unsecured creditors against subordination. Common in bond terms.'},
{term:'Originate-to-Distribute',def:'Business model where bank originates loans then sells or securitizes them to investors, keeping no risk. Creates moral hazard: originator has less incentive to maintain credit standards if they won\'t hold the risk. Led to 2008 crisis. Now regulated to require some retention (skin in the game).'},
{term:'Overcollateralization',def:'Pledging collateral worth significantly more than the loan amount. If loan = ₹100, collateral = ₹150, overcollateralization = 50%. Provides cushion against collateral value decline. Required in asset-backed securities to protect investors.'},
{term:'Prepayment Penalty',def:'Fee charged by lender when borrower repays loan before maturity. Compensates lender for lost interest income. RBI has prohibited prepayment penalties on floating-rate home loans. Fixed-rate loans may still have prepayment clauses.'},
{term:'Priority in Liquidation',def:'Order in which creditors are paid if borrower goes bankrupt. Order: Secured creditors (first charge holders) → Secured creditors (second charge) → Preferential creditors (employee wages, tax) → Unsecured creditors → Shareholders. Senior secured lenders have highest priority; equity holders are last.'},
{term:'Promissory Note',def:'Written promise by one party (maker) to pay a specified sum to another (payee) at a specific date or on demand. Negotiable instrument under NI Act. Microfinance joint liability groups often use promissory notes.'},
{term:'Recourse',def:'Legal right to demand compensation. Full recourse loan: lender can pursue borrower\'s other assets beyond collateral. Non-recourse: lender can only claim specific pledged assets. Project finance is often non-recourse — repayment only from project cash flows.'},
{term:'Refinancing Risk',def:'Risk that a borrower cannot roll over or refinance a maturing loan at acceptable terms. When loan matures, borrower must find new lender or new terms. In rising rate environment, refinancing happens at higher cost. Short-term funding of long-term assets creates high refinancing risk.'},
{term:'Rehypothecation',def:'Practice where broker/bank uses client\'s pledged collateral for its own purposes. If broker pledges client\'s securities to get a loan, and broker fails, client may lose securities. Regulated in India — banks must disclose and get explicit consent.'},
{term:'Seasoning',def:'Time period since a loan was originated. "Seasoned" loans: older, with payment history — less uncertain. New loans have no payment history — higher initial uncertainty. Credit quality of loan portfolio improves as loans season (proven performers identified).'},
{term:'Syndication Fee',def:'Fee paid to lead arranger bank for putting together a syndicated loan. Typically 0.5-2% of loan amount. Distributed partially to other syndicate banks as participation fees.'},
{term:'Tranche',def:'One of several portions of a debt offering. An infrastructure bond might be offered in three tranches — ₹500 crore at 7%, ₹300 crore at 7.5%, ₹200 crore at 8% (for different maturity investors). Each tranche may have different terms.'},
{term:'Underwater',def:'Asset worth less than the loan against it. Underwater mortgage: property value < loan amount. Borrower has negative equity — rational reason to default if they can walk away from non-recourse loan. Housing market collapse causes mass underwater mortgages.'},
{term:'Usury',def:'Charging excessively high interest rates, often illegal. India\'s Usurious Loans Act 1918 allowed courts to reopen usurious loan contracts. NBFC-MFI regulations cap interest at 24% per annum to prevent usury in microfinance.'},
{term:'Warrant',def:'Security giving holder the right (but not obligation) to purchase company\'s stock at specific price before expiration. Similar to call option but issued by company itself (dilutes equity when exercised). Sometimes attached to bonds ("bond with warrants") as sweetener.'}
]},{
category:'Financial Markets',
terms:[
{term:'Arbitrage',def:'Simultaneous purchase and sale of an asset in different markets to profit from price difference. Riskless arbitrage eliminates itself — price difference disappears as arbitrageurs trade. Statistical arbitrage: quantitative strategies exploiting historical correlations. Regulatory arbitrage: exploiting differences in regulations across jurisdictions.'},
{term:'Ask Price',def:'Price at which seller is willing to sell a security. Also called "offer price." Buyers pay the ask price (higher price). Bid-ask spread = Ask - Bid. Market makers profit from this spread.'},
{term:'Asset Bubble',def:'Rapid escalation in asset prices driven by speculative behavior rather than fundamentals. Prices are far above intrinsic value. Classic bubbles: Dutch Tulip Mania (1637), Dot-com (1990s), US Housing (2000s), Bitcoin (cyclical). Bubbles eventually burst — sharp price decline.'},
{term:'Bear Raid',def:'Illegal market manipulation where traders short sell a stock and simultaneously spread negative rumors to drive down its price, then cover at lower price for profit. SEBI investigates such manipulation.'},
{term:'Beta',def:'Measure of a stock\'s volatility relative to the market. Beta=1: moves with market. Beta>1: more volatile than market (e.g., small-cap tech). Beta<1: less volatile (e.g., utilities). Negative beta: moves opposite to market (rare — gold ETF sometimes). Key input in CAPM for expected return.'},
{term:'Bid Price',def:'Price at which a buyer is willing to buy a security. Lower than ask price. Sellers receive the bid price. Bid-ask spread compensates market makers for providing liquidity.'},
{term:'Book Value',def:'Net asset value per share = (Total Assets - Intangibles - Liabilities) / Shares outstanding. For banks: total equity / shares outstanding. P/B ratio = Market Price / Book Value. Distressed banks trade below book value (P/B < 1).'},
{term:'Bull Market',def:'Sustained period of rising asset prices (typically stocks), 20%+ above recent low. Characterized by investor optimism, economic expansion, and improving corporate earnings. Opposite: Bear market (20%+ decline).'},
{term:'Capital Asset Pricing Model (CAPM)',def:'Model for determining expected return of an investment: E(R) = Rf + β(Rm-Rf). Where Rf = risk-free rate, β = beta, Rm = market return, (Rm-Rf) = equity risk premium. Higher beta = higher expected return. Used to value stocks and make investment decisions.'},
{term:'Circuit Breaker',def:'Automatic mechanism that pauses trading when index falls by specified percentage. India (SEBI): Circuit breakers at 10%, 15%, 20% decline in Sensex/Nifty. Designed to prevent panic selling, allow time for information to be absorbed. Also applied to individual stocks (upper and lower price limits).'},
{term:'Commodity Futures',def:'Contracts to buy/sell physical commodities (oil, gold, wheat, cotton) at future date and price. Commodity exchanges in India: MCX (Multi Commodity Exchange) and NCDEX (National Commodity and Derivatives Exchange). Now regulated by SEBI (after FMC-SEBI merger in 2015).'},
{term:'Credit Default Swap (CDS)',def:'Derivative contract where buyer pays periodic premium; seller pays if specified credit event (default, restructuring) occurs on reference entity. Provides protection against credit losses. Problematic when sellers (like AIG in 2008) can\'t pay when multiple events occur simultaneously.'},
{term:'Dark Pool',def:'Private exchange or forum for trading securities not accessible to public. Large institutional investors use dark pools to trade large blocks without revealing their hand to market. SEBI regulates dark pool equivalents (block deals, institutional window).'},
{term:'Delta Hedging',def:'Technique for managing option risk by taking offsetting position in underlying asset. Delta = change in option price for unit change in underlying. Delta-hedging keeps portfolio neutral to small price changes. Requires continuous rebalancing as delta changes.'},
{term:'Derivatives Market',def:'Market for financial instruments whose value derives from underlying asset. Two broad categories: Exchange-traded (standardized futures and options on NSE/BSE) and Over-the-counter or OTC (customized forwards, swaps between parties). India\'s derivatives market is world\'s largest for single-stock derivatives by volume.'},
{term:'Dividend Yield',def:'Annual dividend per share / Share price. High dividend yield = relatively high return from dividends. PSBs traditionally offered high dividend yields. Banks with high dividend yields but struggling fundamentals should be viewed cautiously.'},
{term:'Exchange Rate Risk',def:'Risk of loss from adverse exchange rate movements. For Indian importers: rupee depreciation increases import costs. For exporters: rupee appreciation reduces rupee earnings from exports. Managed with hedging instruments: forwards, futures, options on currency pairs.'},
{term:'Futures',def:'Standardized contracts to buy/sell an asset at specified price at future date. Traded on exchanges. Both parties must fulfill the contract. Daily mark-to-market: gains/losses credited/debited daily. Most futures don\'t result in actual delivery — positions closed before expiry.'},
{term:'Hedge Fund',def:'Investment fund using diverse strategies to generate returns — long/short equity, global macro, merger arbitrage, quantitative. Generally lightly regulated (SEBI regulates Category III AIFs). High minimum investment (typically $1 million+). Performance fees (2% management, 20% of profits = "2 and 20").'},
{term:'Index Fund',def:'Mutual fund tracking a market index (Nifty 50, Sensex) by holding same securities in same proportion. Passive management — very low expense ratio (0.05-0.5%). Growing in India: UTI Nifty 50 Index Fund, SBI Nifty Index Fund. Arguments for: diversification, low cost, outperforms most active funds long-term.'},
{term:'Initial Public Offering (IPO)',def:'First time a company offers shares to public on stock exchange. Process: Company files DRHP with SEBI → SEBI review → Book building/fixed price → Listing. Allotment is proportional/lottery for oversubscribed IPOs. 10% reserved for retail investors. Lock-in: promoters cannot sell for 18 months post-listing.'},
{term:'Interest Rate Swap',def:'Agreement between two parties to exchange interest payments: fixed rate for floating rate. Bank A pays fixed 7%, receives MIBOR+0.5% from Bank B. Useful for: banks converting fixed-rate assets to floating, or managing interest rate exposure. Notional principal is not exchanged — only interest payments.'},
{term:'Liquidity Risk Premium',def:'Additional return required by investors to hold less liquid assets. Government bonds are liquid (easily sold); private equity is illiquid. Illiquidity premium compensates investors for not being able to exit quickly. Small-cap stocks have higher liquidity risk premium than large caps.'},
{term:'Market Capitalization',def:'Total market value of a company\'s outstanding shares. = Share price × number of shares outstanding. Categories: Large-cap (>₹20,000 crore in India), Mid-cap (₹5,000-20,000 crore), Small-cap (<₹5,000 crore). Bank\'s market cap reflects market\'s assessment of future earnings and governance.'},
{term:'Money Market Fund',def:'Mutual fund investing in short-term, high-quality money market instruments (T-bills, CPs, CDs). Very low risk, higher return than savings account. In India: Overnight funds, Liquid funds. Regulated by SEBI; returns linked to money market rates.'},
{term:'Mutual Fund Net Asset Value (NAV)',def:'Per-unit value of mutual fund = (Total assets - Liabilities) / Units outstanding. Calculated daily at market close. Investors buy and sell at NAV. Exit load applies if redeemed before specified period. NAV does not equal unit price.'},
{term:'Open Interest',def:'Total number of outstanding derivative contracts (futures/options) that have not been settled. Rising open interest with rising price = bullish. Rising open interest with falling price = bearish. Declining open interest = short covering or position reduction.'},
{term:'Options Premium',def:'Price paid by option buyer to option seller for the right to buy (call) or sell (put) underlying asset at specified price. Premium = Intrinsic value + Time value. Intrinsic value = current benefit if exercised now. Time value = additional premium for remaining time before expiry.'},
{term:'Price-to-Earnings Ratio (P/E)',def:'Share price / Earnings per share. Indicates how much investors pay per rupee of earnings. High P/E = growth expectations. Low P/E = value or struggling company. Indian bank P/E: Private banks 15-25x; PSBs 8-15x (discount for governance concerns and growth pace).'},
{term:'Repo Rate (market)',def:'In money markets, repo rate = rate on repurchase agreements (repos). Differs from RBI\'s policy repo rate. TREP (Triparty Repo) rate and market repo rates are market-determined and fluctuate around RBI\'s policy corridor.'},
{term:'Rights Issue',def:'Company offers additional shares to existing shareholders in proportion to holdings, usually at discount. Shareholders can: subscribe (maintain percentage), sell rights, or let lapse. Bank rights issues: banks raise additional equity capital from existing shareholders to boost capital adequacy.'},
{term:'Short Selling',def:'Selling borrowed securities expecting price to fall. Borrow stock → sell at current price → price falls → buy back at lower price → return stock → profit = price difference. Risk: price may rise (unlimited loss). SEBI has Short-Selling regulations; PSBs are banned from short-selling.'},
{term:'Stock Split',def:'Company divides existing shares into multiple new shares. 2:1 split: each share becomes 2 shares; price halves. No change in total market cap. Makes shares more affordable for retail investors. Example: Tata Motors 1:1 bonus or MRF\'s high per-share price (no split).'},
{term:'Treasury Stock',def:'Shares that company has repurchased from open market. Reduces shares outstanding, increases EPS. Can be used for employee stock options or cancelled. Buyback of shares from shareholders reduces equity — increases return on equity if funded by debt at lower cost.'},
{term:'Volatility Index (VIX)',def:'India VIX (National Stock Exchange): Measures expected volatility in Nifty 50 over next 30 days. High VIX = fear/uncertainty. Low VIX = complacency. Often called "fear gauge." VIX>30 = high anxiety (as seen during COVID crash March 2020). India VIX historically ranges 10-30.'},
{term:'Warrants',def:'Securities giving holder right to buy company\'s stock at specified price before expiry. Company-issued (dilutes equity when exercised). Sometimes attached to bonds as "sweetener" to reduce coupon rate. Example: A ₹1000 bond with warrant allowing purchase of 10 shares at ₹100 each.'},
{term:'Yield Curve',def:'Graph plotting yields of bonds against their maturities. Normal curve: upward sloping (longer term = higher yield). Inverted curve: shorter yields higher than longer (recession predictor). Flat curve: similar yields across maturities. G-sec yield curve in India: typically upward sloping; 10-year yield ≈7%.'}
]}
]};

// 100 More Banking and Economics One-Liners
const MORE_ONELINERS=[
'CRAR minimum in India: 9% (Basel III global minimum: 8%)',
'Capital Conservation Buffer (CCyB): Additional 2.5% CET1 required above minimum CRAR',
'G-SIBs: Global Systemically Important Banks — additional 1-3.5% loss absorbency required',
'India\'s D-SIBs: SBI (bucket 3 = 0.6% additional), HDFC Bank and ICICI Bank (bucket 1 = 0.2%)',
'Provision Coverage Ratio (PCR): Provisions / Gross NPAs; RBI recommends 70%+ for most banks',
'IBC resolution success rate: ~45-50% (rest liquidated or withdrawn)',
'Average IBC resolution time: 600+ days (vs 180-day mandate)',
'Total IBC cases resolved: 7000+ by 2024',
'NARCL (National Asset Reconstruction Company): Government "bad bank" for PSB legacy NPAs',
'IBC covers: Companies, LLPs, and individuals (personal insolvency — not fully implemented)',
'Threshold for initiating CIRP: Default of Rs.1 crore (reduced from Rs.1 lakh in 2020)',
'Operational creditors (suppliers) can also initiate IBC; not just financial creditors',
'Committee of Creditors (CoC) voting: 66% of financial creditors must approve resolution plan',
'Under IBC, Resolution Applicant can\'t be a defaulter (Section 29A disqualification)',
'Insolvency Professional Agencies: ICSI, ICAI, ICWAI have registered insolvency professional agencies',
'IBBI: Insolvency and Bankruptcy Board of India — regulates insolvency professionals and IUs',
'Information Utility (IU): Database where creditors record financial transactions for IBC purposes',
'NeSL: National e-Governance Services Limited — India\'s first IBBI-registered Information Utility',
'UNCITRAL Model Law on Cross-Border Insolvency: India yet to adopt (limits cross-border IBC)',
'One-time Settlement (OTS): Banks can settle NPA loans at a negotiated amount (< full dues)',
'Farm loan waiver: Populist policy; does not address root cause; creates moral hazard in credit culture',
'MSME Restructuring Scheme: One-time restructuring for MSME accounts classified as NPA',
'Emergency Credit Line Guarantee Scheme (ECLGS): COVID relief; Rs.5 lakh crore guaranteed credit to MSMEs',
'SHG-Bank Linkage Program: World\'s largest microfinance program by reach; over 86 lakh SHGs linked',
'Microfinance NPA in FY24: ~3.5%; higher than banking sector average — concentrated in overleveraged states',
'CGTMSE (Credit Guarantee Fund Trust for MSEs): Provides collateral-free credit guarantee for MSEs up to Rs.5 crore',
'SIDBI: Refinances banks and MFIs for MSME and microfinance lending; direct lending also',
'MUDRA Bank: Under SIDBI. Provides refinance to MFIs and banks for micro lending. Not a direct lender.',
'PM SVANidhi scheme: Working capital loans for street vendors (Rs.10,000 to Rs.50,000)',
'Kisan Credit Card (KCC): Revolving credit for farmers; covers crop, post-harvest, ancillary needs',
'KCC limit: Typically 3-year limit based on crops and scale; need renewal/revision',
'Interest Subvention Scheme: Government pays 2% interest subsidy on KCC loans up to Rs.3 lakh for timely repayment',
'Agricultural NPAs: Higher than overall banking NPAs (~7-8%); seasonal and weather-dependent',
'NABARD\'s RIDF (Rural Infrastructure Development Fund): Banks park shortfall in agriculture PSL in RIDF',
'SIDBI\'s MUDRA refinance: Banks get cheaper funds from SIDBI to lend to MUDRA-eligible enterprises',
'Priority Sector Lending Certificates (PSLCs): Enable flexible PSL compliance through market mechanism',
'PSL Shortfall: Banks deposit in RIDF (NABARD) at lower interest rate — penalty for not meeting targets',
'MGNREGS: 100 days guaranteed employment; wage linked to CPI-AL; implemented since Feb 2006',
'PMGSY (Pradhan Mantri Gram Sadak Yojana): Rural road connectivity; covered 1.77 lakh unconnected habitations',
'Pradhan Mantri Awas Yojana (PMAY): Housing for All — Urban (HFAs) and Gramin (PMAY-G)',
'PM-SVY (PM Svanidhi): Street vendor loans — tiered scheme with credit limit increasing with repayment history',
'Swachh Bharat Mission (SBM): 120 crore+ individual household toilets built; ODF (Open Defecation Free) villages',
'PM-KUSUM (Kisan Urja Suraksha and Utthaan Mahabhiyan): Solar pumps for farmers to reduce power costs',
'PM Fasal Bima Yojana (PMFBY): Premium rate 2% Kharif, 1.5% Rabi, 5% commercial; government pays rest',
'PM Kaushal Vikas Yojana (PMKVY): Short-term skill training; 1.37 crore certified trainees by 2024',
'Atal Innovation Mission (AIM): Promotes innovation and entrepreneurship; runs 10,000+ Atal Tinkering Labs',
'Start-up India: 1+ lakh DPIIT-recognized startups; Rs.10,000 crore Fund of Funds; tax holiday 3 years',
'National Pension System (NPS): Market-linked, portable; mandatory for central govt employees from Jan 2004',
'Unified Pension Scheme (UPS): Announced August 2024; guaranteed 50% of last 12-month salary; from April 2025',
'EPFO (Employees\' Provident Fund Organisation): Manages PF for organized sector; current interest: 8.25%',
'ESIC (Employees\' State Insurance Corporation): Health insurance for employees earning up to Rs.21,000/month',
'Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM): Pension for unorganized sector workers (age 18-40); Rs.3,000/month',
'Jan Arogya Yojana (PM-JAY) enrollments: 30+ crore beneficiaries actively enrolled by 2024',
'Ayushman Bharat Digital Mission (ABDM): Abha health IDs; digital health records; interoperable health data',
'COVID vaccination: 220 crore doses administered via CoWIN platform; world\'s largest vaccination drive',
'National Health Account: India\'s out-of-pocket expenditure ~48% of total health expenditure (high, need reduction)',
'National Digital Health Mission (NDHM): Now ABDM — creates digital health ecosystem with ABHA IDs',
'PM-WANI (Wi-Fi Access Network Interface): Public Wi-Fi network for internet access at affordable prices',
'BharatNet: OFC (optical fiber cable) to gram panchayats — 2 lakh+ gram panchayats covered',
'Digital Village: Fully connected village with high-speed internet, digital services, e-governance',
'Common Service Centres (CSC): 5+ lakh CSCs across India providing digital, banking, insurance services',
'GeM (Government e-Marketplace): Rs.4 lakh crore+ procurement through digital platform (FY24)',
'ONDC (Open Network for Digital Commerce): Democratizing e-commerce; alternative to Amazon/Flipkart duopoly',
'Direct Tax-to-GDP ratio India: ~6.5%. Global comparison: USA ~10%, UK ~11%.',
'Goods and Services Tax compensation: States compensated for 5 years (2017-22) for revenue loss from GST',
'GST composition scheme: Small businesses (up to Rs.1.5 crore) pay flat GST %: 1% for manufacturers, 5% for restaurants',
'Input Tax Credit (ITC): GST paid on inputs can be credited against GST liability on outputs — reduces tax cascading',
'E-Invoice under GST: Mandatory for businesses with turnover > Rs.10 crore; auto-populates GSTR-1',
'E-Way Bill: Required for movement of goods > Rs.50,000; tracks inter-state and intra-state movement',
'GSTN (Goods and Services Tax Network): Technology backbone of GST — maintained by GSTN company',
'GST on banking services: Banks charge 18% GST on service charges (processing fees, advisory fees, locker rent)',
'GST on financial products: Life insurance premium (18% on risk component), health insurance (18% on premium)',
'GST on gold: 3% GST; making charges 5% GST',
'Input Service Distributor (ISD): Mechanism to distribute ITC to branches from head office — relevant for multi-branch banks',
'Transfer of ITC for banking sector: Complex due to many exempt supplies; banks can claim only partial ITC',
'Net Tax Revenue (NTR): Gross tax revenue minus refunds. Shared between Centre and States through Finance Commission formula',
'Finance Commission: Constitutional body recommending tax sharing between Centre and States; 15th FC award period: 2021-26',
'15th Finance Commission: Recommended 41% of taxes to states (same as 14th FC); allocated Rs.10 lakh crore grant to states',
'Vertical devolution: Tax sharing between Centre and States. Horizontal devolution: Distribution among states.',
'State Disaster Risk Management Fund (SDRMF): State-level fund for disaster relief; Centre contributes 75%',
'National Investment and Infrastructure Fund (NIIF): India\'s sovereign wealth-style fund for infrastructure; Rs.40,000 crore',
'Infrastructure Investment Trust (InvIT): SEBI-regulated vehicle for infrastructure assets to raise funds from investors',
'Real Estate Investment Trust (REIT): SEBI-regulated vehicle for commercial real estate; listed on exchanges',
'Domestic Systemically Important Insurer (D-SII): IRDAI designates large insurers; enhanced regulatory scrutiny',
'IRDAI insurance penetration target: 5% of GDP by 2030 (from 4% currently)',
'Bima Sugam: IRDAI\'s digital platform for purchasing, managing insurance; one-stop shop for all insurance needs',
'Bima Vahak: Rural distribution channel for insurance; similar to BC model in banking',
'Swasthya Bima: Proposed comprehensive health insurance cover; replacement for PM-JAY for all citizens',
'Cashless Insurance: Digital settlement of health claims without patient paying upfront; growing rapidly',
'AFTER: Automated Fraud and error Transfer Exchange Repository — IRDAI fraud tracking system'
];
