if(typeof Q==='undefined')window.Q=[];

// ═══════════════════════════════════════════════════════════════
// ENGLISH — READING COMPREHENSION (rc1_1 to rc6_5) — 30 questions
// ═══════════════════════════════════════════════════════════════

// ── PASSAGE 1: Financial Inclusion & PMJDY ──
const RC1 = `Financial inclusion has emerged as a cornerstone of India's developmental agenda. The Pradhan Mantri Jan Dhan Yojana (PMJDY), launched in August 2014, is the world's largest financial inclusion initiative. It aims to ensure access to financial services — savings accounts, remittance, credit, insurance, and pension — for the excluded sections of society at an affordable cost. Under this scheme, every household is entitled to at least one bank account, a RuPay debit card with an inbuilt accident insurance cover of Rs.2 lakh, and an overdraft facility of up to Rs.10,000 for eligible account holders. By 2024, the scheme had opened over 53 crore accounts, with women holding more than 55% of these accounts. The Direct Benefit Transfer (DBT) mechanism, linked with PMJDY accounts, has prevented leakages worth thousands of crores. The scheme also promotes digital literacy, helping rural populations transition from cash-based to digital transactions. Despite challenges such as dormant accounts, low average balances, and limited credit uptake, PMJDY remains a transformative milestone in banking the unbanked.`;

Q.push(
{id:'rc1_1',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC1}\n\nQ: According to the passage, which of the following is NOT a financial service offered under PMJDY?`,o:['Savings account and remittance','Accident insurance cover via RuPay card','Home loan at subsidised interest rates','Overdraft facility up to Rs.10,000'],c:2,e:'The passage lists savings accounts, remittance, credit, insurance, pension, RuPay debit card with accident insurance of Rs.2 lakh, and overdraft facility — but makes no mention of home loans at subsidised interest rates. Hence option C is not mentioned.',x:['sbi_mains','rbi_phase1','sbi_prelims']},

{id:'rc1_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC1}\n\nQ: What does the passage identify as the primary purpose of the Direct Benefit Transfer mechanism linked with PMJDY?`,o:['To promote digital literacy in rural areas','To provide accident insurance to account holders','To prevent leakages of government funds','To increase the number of bank accounts opened'],c:2,e:'The passage states: "The Direct Benefit Transfer (DBT) mechanism, linked with PMJDY accounts, has prevented leakages worth thousands of crores." This directly answers the question — the primary purpose is to prevent fund leakages.',x:['sbi_mains','rbi_phase1','sbi_prelims']},

{id:'rc1_3',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC1}\n\nQ: What percentage of PMJDY accounts are held by women, as stated in the passage?`,o:['More than 45%','More than 50%','More than 55%','Exactly 60%'],c:2,e:'The passage clearly states "women holding more than 55% of these accounts." Option C is directly supported by the text.',x:['sbi_prelims','sbi_mains']},

{id:'rc1_4',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC1}\n\nQ: Which of the following challenges to PMJDY is mentioned in the passage?`,o:['Lack of government support and funding','Dormant accounts and low average balances','Absence of RuPay network in rural areas','Inadequate overdraft limits for farmers'],c:1,e:'The passage mentions "challenges such as dormant accounts, low average balances, and limited credit uptake." Option B correctly identifies two of these challenges. The other options are not mentioned in the passage.',x:['sbi_mains','rbi_phase1']},

{id:'rc1_5',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC1}\n\nQ: The author's tone towards PMJDY can best be described as:`,o:['Highly critical and dismissive','Completely neutral and factual','Balanced — acknowledging both achievements and challenges','Enthusiastically promotional without any reservations'],c:2,e:'The author presents significant achievements (53 crore accounts, DBT linkage, women empowerment) but also acknowledges challenges (dormant accounts, low balances, limited credit uptake). This balanced perspective makes option C the most accurate description of the author\'s tone.',x:['sbi_mains','rbi_phase1']},
);

// ── PASSAGE 2: UPI & Digital Payments ──
const RC2 = `The Unified Payments Interface (UPI) has revolutionised the digital payments landscape in India, positioning the country as a global leader in real-time payment systems. Developed by the National Payments Corporation of India (NPCI) and launched in 2016, UPI enables instant interbank transfers using a Virtual Payment Address (VPA) without the need to share sensitive bank details. By 2024, UPI was processing over 13 billion transactions per month, with a total annual value exceeding Rs.200 lakh crore. The ecosystem includes apps like PhonePe, Google Pay, Paytm, and the government-backed BHIM. A significant policy milestone was the introduction of UPI123Pay for feature phone users, and UPI Lite for small offline transactions, extending digital payments to those without smartphones or reliable internet. India has also exported UPI to countries like Singapore, UAE, France, and Bhutan, enhancing cross-border remittance capabilities. The RBI's tokenisation framework and the interoperability mandate have further strengthened consumer trust. Critics, however, point to zero MDR (Merchant Discount Rate) as a potential barrier to long-term sustainability of payment service providers.`;

Q.push(
{id:'rc2_1',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC2}\n\nQ: Which organisation developed UPI, as mentioned in the passage?`,o:['Reserve Bank of India (RBI)','Ministry of Finance','National Payments Corporation of India (NPCI)','State Bank of India'],c:2,e:'The passage explicitly states "Developed by the National Payments Corporation of India (NPCI)." RBI regulates but did not develop UPI directly.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc2_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC2}\n\nQ: UPI123Pay was introduced specifically to benefit which group of users?`,o:['Users without a bank account','Feature phone users without smartphones','Merchants with large transaction volumes','NRIs sending money from abroad'],c:1,e:'The passage states "the introduction of UPI123Pay for feature phone users" — this was specifically to extend digital payment access to those who do not have smartphones.',x:['sbi_mains','rbi_phase1']},

{id:'rc2_3',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC2}\n\nQ: Which of the following countries is NOT mentioned in the passage as a nation to which India has exported UPI?`,o:['Singapore','UAE','Japan','Bhutan'],c:2,e:'The passage mentions Singapore, UAE, France, and Bhutan as countries where UPI has been exported. Japan is not mentioned anywhere in the passage.',x:['sbi_prelims','sbi_mains']},

{id:'rc2_4',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC2}\n\nQ: What concern do critics raise about UPI's ecosystem, according to the passage?`,o:['UPI transactions are not secure for large amounts','Zero MDR may harm long-term sustainability of payment providers','Feature phone users cannot access UPI services','Cross-border UPI transfers attract high charges'],c:1,e:'The passage states "Critics, however, point to zero MDR (Merchant Discount Rate) as a potential barrier to long-term sustainability of payment service providers." Zero MDR means merchants are not charged, reducing revenue for payment companies.',x:['sbi_mains','rbi_phase1']},

{id:'rc2_5',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC2}\n\nQ: The word 'interoperability' as used in the passage most nearly means:`,o:['The ability of different systems to work together seamlessly','The process of encrypting payment data for security','A government mandate requiring fee-free transactions','The system of virtual payment addresses'],c:0,e:'"Interoperability" refers to the capability of different systems, platforms, or applications to communicate and work together. In the context of UPI, it means different payment apps and banks can transact with each other without barriers.',x:['sbi_mains','rbi_phase1']},
);

// ── PASSAGE 3: Non-Performing Assets & Banking Reforms ──
const RC3 = `Non-Performing Assets (NPAs) represent one of the most critical challenges confronting the Indian banking system. An asset becomes non-performing when the borrower fails to service the loan — either interest or principal — for more than 90 days. Gross NPAs of scheduled commercial banks peaked at approximately Rs.10.36 lakh crore in 2018, accounting for 11.6% of total advances. The government and the RBI undertook a series of structural reforms to address this crisis. The Insolvency and Bankruptcy Code (IBC), enacted in 2016, established a time-bound resolution framework, replacing the earlier slow-moving debt recovery mechanisms. Asset Quality Review (AQR) initiated by the RBI in 2015 forced banks to recognise hidden NPAs, resulting in a short-term spike in reported bad loans but providing a truer picture of banking health. Recapitalisation of public sector banks, consolidation of weaker banks with stronger ones, and the establishment of the National Asset Reconstruction Company Ltd (NARCL) — commonly called the 'bad bank' — represent further reform measures. By 2023, gross NPAs had declined to around 3.9%, signalling significant improvement, though concerns about restructured loans and evergreening of accounts persist.`;

Q.push(
{id:'rc3_1',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC3}\n\nQ: According to the passage, an asset is classified as non-performing when the borrower fails to service the loan for more than:`,o:['60 days','90 days','120 days','180 days'],c:1,e:'The passage explicitly states "when the borrower fails to service the loan — either interest or principal — for more than 90 days." This is the standard RBI definition of an NPA.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc3_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC3}\n\nQ: What was the immediate effect of the Asset Quality Review (AQR) initiated by RBI in 2015?`,o:['Immediate reduction in gross NPAs across all banks','A short-term spike in reported bad loans','Consolidation of public sector banks','Enactment of the Insolvency and Bankruptcy Code'],c:1,e:'The passage states AQR "forced banks to recognise hidden NPAs, resulting in a short-term spike in reported bad loans but providing a truer picture of banking health." The spike was a short-term consequence of recognising previously hidden NPAs.',x:['sbi_mains','rbi_phase1']},

{id:'rc3_3',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC3}\n\nQ: NARCL is referred to in the passage as:`,o:['A debt recovery tribunal','A credit rating agency','A bad bank','A special purpose vehicle for bank mergers'],c:2,e:'The passage states "the establishment of the National Asset Reconstruction Company Ltd (NARCL) — commonly called the \'bad bank\'." This is the term used in the passage to describe NARCL.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc3_4',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC3}\n\nQ: Which of the following best describes the significance of the Insolvency and Bankruptcy Code (IBC) as explained in the passage?`,o:['It recapitalised public sector banks with government funds','It replaced slow debt recovery mechanisms with a time-bound resolution framework','It merged weak banks with stronger public sector banks','It mandated banks to disclose NPAs quarterly to the RBI'],c:1,e:'The passage says the IBC "established a time-bound resolution framework, replacing the earlier slow-moving debt recovery mechanisms." This is the key significance of IBC highlighted in the passage.',x:['sbi_mains','rbi_phase1']},

{id:'rc3_5',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC3}\n\nQ: What does the phrase "evergreening of accounts" most likely refer to in the context of the passage?`,o:['Maintaining a positive balance in savings accounts year-round','The practice of granting fresh loans to repay old loans, masking bad debts','Converting foreign currency loans to rupee-denominated loans','The process of upgrading non-performing accounts to standard status'],c:1,e:'"Evergreening" is a banking term for the practice where banks extend new credit to a defaulting borrower to help repay old dues, thereby avoiding NPA classification. The passage uses it alongside "restructured loans" as a persistent concern even after NPA improvement.',x:['sbi_mains','rbi_phase1']},
);

// ── PASSAGE 4: Monetary Policy & Inflation ──
const RC4 = `Monetary policy is the mechanism by which a central bank, such as the Reserve Bank of India (RBI), controls the money supply and interest rates to achieve macroeconomic objectives — primarily price stability and growth. The Monetary Policy Committee (MPC), constituted in 2016 under the amended RBI Act, is a six-member body responsible for setting the policy repo rate. The MPC comprises three RBI officials, including the Governor who chairs it, and three external members appointed by the government. The inflation-targeting framework, adopted in 2016, mandates the MPC to maintain Consumer Price Index (CPI) inflation at 4%, with a tolerance band of ±2%. If inflation remains outside this band for three consecutive quarters, the RBI must submit a report to the government explaining the reasons and remedial measures. Key policy instruments include the repo rate (rate at which RBI lends to banks), the reverse repo rate (rate at which RBI absorbs liquidity from banks), the Cash Reserve Ratio (CRR), and the Statutory Liquidity Ratio (SLR). Food inflation, particularly driven by vegetable price volatility, remains a recurring challenge for meeting the inflation target in India.`;

Q.push(
{id:'rc4_1',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC4}\n\nQ: How many members does the Monetary Policy Committee (MPC) comprise, according to the passage?`,o:['Three members','Four members','Six members','Eight members'],c:2,e:'The passage states "a six-member body" — the MPC has six members in total: three RBI officials and three external members appointed by the government.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc4_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC4}\n\nQ: According to the inflation-targeting framework described in the passage, what action must the RBI take if inflation stays outside the tolerance band for three consecutive quarters?`,o:['Immediately raise the repo rate by 50 basis points','Impose emergency CRR restrictions on all banks','Submit a report to the government explaining reasons and remedial measures','Convene an emergency MPC meeting within 15 days'],c:2,e:'The passage explicitly states "the RBI must submit a report to the government explaining the reasons and remedial measures" if inflation stays outside the ±2% band for three consecutive quarters.',x:['sbi_mains','rbi_phase1']},

{id:'rc4_3',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC4}\n\nQ: The reverse repo rate, as defined in the passage, is:`,o:['The rate at which RBI lends money to commercial banks','The rate at which banks borrow from each other overnight','The rate at which RBI absorbs liquidity from banks','The minimum rate banks must charge on retail loans'],c:2,e:'The passage defines reverse repo rate as "rate at which RBI absorbs liquidity from banks." When banks park excess funds with RBI, RBI pays this rate to them.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc4_4',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC4}\n\nQ: What does the passage identify as a recurring challenge for meeting India's inflation target?`,o:['Volatile crude oil prices and global commodity shocks','Food inflation driven by vegetable price volatility','Depreciation of the Indian Rupee against the US Dollar','High fiscal deficit leading to excess money supply'],c:1,e:'The passage concludes: "Food inflation, particularly driven by vegetable price volatility, remains a recurring challenge for meeting the inflation target in India." This is directly stated.',x:['sbi_mains','rbi_phase1']},

{id:'rc4_5',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC4}\n\nQ: Which of the following inferences can be validly drawn from the passage?`,o:['The MPC has the authority to override the RBI Governor on rate decisions','The inflation target of 4% has never been breached since 2016','External members of the MPC are drawn from the finance ministry only','The inflation-targeting framework was introduced as part of an amendment to the RBI Act'],c:3,e:'The passage states "The Monetary Policy Committee (MPC), constituted in 2016 under the amended RBI Act." This confirms that the framework was introduced via an amendment to the RBI Act. Option A is wrong (voting procedure is not discussed), B is wrong (the passage mentions the band tolerance implying breaches are possible), and C is wrong (the passage says "government" appoints them, not specifically finance ministry).',x:['sbi_mains','rbi_phase1']},
);

// ── PASSAGE 5: MSME Sector ──
const RC5 = `Micro, Small and Medium Enterprises (MSMEs) form the backbone of India's economy, contributing approximately 30% to the GDP, over 45% to exports, and providing employment to more than 11 crore people. Revised classification criteria introduced in 2020 redefined MSMEs based on both investment in plant and machinery and annual turnover, replacing the earlier single-criterion approach. A micro enterprise now has an investment limit of up to Rs.1 crore and a turnover of up to Rs.5 crore. Despite their significance, MSMEs face structural challenges: limited access to formal credit, technological backwardness, infrastructure deficiencies, and vulnerability to global supply chain disruptions. The Emergency Credit Line Guarantee Scheme (ECLGS), launched during the COVID-19 pandemic, provided guaranteed credit to stressed MSMEs, disbursing over Rs.3.6 lakh crore. The MSME Samadhaan portal enables online filing of delayed payment complaints. Delayed payment by large corporates and government departments remains a systemic issue — MSMEs are legally entitled to payment within 45 days under the MSMED Act. The Udyam Registration portal has simplified MSME formalisation. Despite policy support, many micro enterprises remain in the informal economy, limiting their access to institutional finance and social security benefits.`;

Q.push(
{id:'rc5_1',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC5}\n\nQ: According to the passage, what is the employment provided by the MSME sector?`,o:['More than 5 crore people','More than 8 crore people','More than 11 crore people','More than 15 crore people'],c:2,e:'The passage states "providing employment to more than 11 crore people." This figure refers to total direct employment generated by the MSME sector.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc5_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC5}\n\nQ: What was the key change introduced by the revised MSME classification criteria of 2020?`,o:['MSMEs were reclassified based solely on number of employees','The single-criterion approach was replaced by a dual criterion of investment and turnover','The investment limit for all categories was doubled uniformly','A new category of "super-micro" enterprises was introduced'],c:1,e:'The passage states "Revised classification criteria introduced in 2020 redefined MSMEs based on both investment in plant and machinery and annual turnover, replacing the earlier single-criterion approach." The key change was moving from a single criterion to a dual criterion.',x:['sbi_mains','rbi_phase1']},

{id:'rc5_3',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC5}\n\nQ: The MSME Samadhaan portal, as described in the passage, is used for:`,o:['Online MSME registration and formalisation','Accessing emergency credit guarantees during crises','Filing delayed payment complaints online','Tracking export performance of MSME units'],c:2,e:'The passage states "The MSME Samadhaan portal enables online filing of delayed payment complaints." Udyam Registration handles formalisation; ECLGS handles emergency credit — these are separate mechanisms.',x:['sbi_prelims','sbi_mains']},

{id:'rc5_4',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC5}\n\nQ: Under the MSMED Act, within how many days are large corporates legally required to pay MSMEs?`,o:['30 days','45 days','60 days','90 days'],c:1,e:'The passage explicitly states "MSMEs are legally entitled to payment within 45 days under the MSMED Act." Delayed payment beyond this period is a systemic problem the passage highlights.',x:['sbi_mains','rbi_phase1']},

{id:'rc5_5',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC5}\n\nQ: Which of the following best explains why many micro enterprises remain outside the institutional finance system, as suggested by the passage?`,o:['They deliberately avoid formal registration to evade taxes','They prefer informal money-lenders who offer lower interest rates','Many remain in the informal economy, limiting access to institutional finance','The government has not created any specific portals for their registration'],c:2,e:'The passage concludes: "many micro enterprises remain in the informal economy, limiting their access to institutional finance and social security benefits." Operating informally means they lack the documentation and formal status needed to access bank credit.',x:['sbi_mains','rbi_phase1']},
);

// ── PASSAGE 6: Green Finance & Sustainable Banking ──
const RC6 = `Green finance refers to financial instruments and services that support environmentally sustainable economic activities and projects that mitigate climate change. In India, the Securities and Exchange Board of India (SEBI) introduced the Green Bond framework in 2023, building on existing regulations to align with international standards such as the International Capital Market Association (ICMA) Green Bond Principles. The Reserve Bank of India has incorporated climate risk into the financial stability assessment framework, acknowledging that physical and transition risks from climate change pose systemic threats to banks' asset quality. In 2023, the government issued Sovereign Green Bonds worth Rs.16,000 crore to fund green infrastructure projects, including solar energy, clean transportation, and energy efficiency. The Business Responsibility and Sustainability Report (BRSR) mandated by SEBI for listed companies ensures transparency in ESG (Environmental, Social, and Governance) disclosures. Internationally, the concept of 'stranded assets' — fossil fuel assets that may lose value due to climate regulations — is increasingly factoring into bank lending decisions. Despite growing momentum, challenges include the absence of a unified green taxonomy in India, greenwashing risks, and limited capacity of banks to assess climate-related financial risks. Sustainable finance presents an enormous opportunity for India to mobilise capital towards its net-zero commitments.`;

Q.push(
{id:'rc6_1',s:'english',t:'reading_comprehension',d:'easy',q:`Read the following passage carefully:\n\n${RC6}\n\nQ: What does ESG stand for, as mentioned in the passage?`,o:['Economic, Social and Governance','Environmental, Social and Governance','Environmental, Sustainability and Growth','Equity, Social and Green'],c:1,e:'The passage explicitly states "ESG (Environmental, Social, and Governance) disclosures." ESG is a standard framework for evaluating a company\'s impact and risks across these three dimensions.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'rc6_2',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC6}\n\nQ: For what total value did the Government of India issue Sovereign Green Bonds in 2023?`,o:['Rs.8,000 crore','Rs.10,000 crore','Rs.16,000 crore','Rs.20,000 crore'],c:2,e:'The passage states "the government issued Sovereign Green Bonds worth Rs.16,000 crore to fund green infrastructure projects." This figure is directly mentioned.',x:['sbi_prelims','sbi_mains']},

{id:'rc6_3',s:'english',t:'reading_comprehension',d:'medium',q:`Read the following passage carefully:\n\n${RC6}\n\nQ: The term 'stranded assets' as used in the passage refers to:`,o:['Bank loans that have become non-performing assets','Green bonds that cannot find buyers in the market','Fossil fuel assets that may lose value due to climate regulations','Infrastructure projects abandoned due to environmental protests'],c:2,e:'The passage defines stranded assets as "fossil fuel assets that may lose value due to climate regulations." As the world transitions away from fossil fuels, such assets risk becoming economically unviable.',x:['sbi_mains','rbi_phase1']},

{id:'rc6_4',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC6}\n\nQ: Which of the following challenges to green finance in India is mentioned in the passage?`,o:['Lack of investor interest in green bonds','Absence of a unified green taxonomy and greenwashing risks','RBI\'s refusal to incorporate climate risk in policy frameworks','SEBI has not introduced any green bond regulations'],c:1,e:'The passage states "challenges include the absence of a unified green taxonomy in India, greenwashing risks, and limited capacity of banks to assess climate-related financial risks." Option B directly matches two of these stated challenges.',x:['sbi_mains','rbi_phase1']},

{id:'rc6_5',s:'english',t:'reading_comprehension',d:'hard',q:`Read the following passage carefully:\n\n${RC6}\n\nQ: What role does the Business Responsibility and Sustainability Report (BRSR) play, according to the passage?`,o:['It mandates green bond issuance by listed companies every year','It sets interest rate guidelines for sustainable project loans','It ensures transparency in ESG disclosures for listed companies','It replaces the Green Bond framework introduced by SEBI'],c:2,e:'The passage states BRSR is "mandated by SEBI for listed companies ensures transparency in ESG (Environmental, Social, and Governance) disclosures." Its function is disclosure and transparency, not bond issuance or interest rate setting.',x:['sbi_mains','rbi_phase1']},
);

// ═══════════════════════════════════════════════════════════════
// ERROR DETECTION (ed1 to ed25) — 25 questions
// ═══════════════════════════════════════════════════════════════

Q.push(
{id:'ed1',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The committee have / (B) decided to postpone / (C) the meeting until / (D) further notice. / (E) No error',o:['A','B','C','D'],c:0,e:'"The committee" is treated as a singular collective noun in formal/standard usage, so the verb should be "has decided," not "have decided." The error is in part A.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ed2',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Neither the manager / (B) nor the employees / (C) were present / (D) at the board meeting. / (E) No error',o:['A','B','C','D'],c:3,e:'With "neither...nor," the verb agrees with the subject closest to it — "the employees" (plural), so "were" is correct. There is no grammatical error in this sentence. The answer is D (No error).',x:['sbi_prelims','sbi_mains']},

{id:'ed3',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The RBI has been / (B) implementing several / (C) measure to curb / (D) rising inflation. / (E) No error',o:['A','B','C','D'],c:2,e:'"Measure" should be "measures" (plural) because several is used, which always takes a plural noun. The error is in part C.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ed4',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Had the government / (B) not intervened timely, / (C) the banking crisis / (D) would have worsened. / (E) No error',o:['A','B','C','D'],c:1,e:'"Timely" is an adjective, not an adverb. The correct adverb form is also "timely" in some usages, but in this context "in time" or "promptly" is more appropriate. However, the specific error is that "timely" here functions as an adjective used adverbially — the grammatically precise option is "in a timely manner." Part B contains the error.',x:['sbi_mains','rbi_phase1']},

{id:'ed5',s:'english',t:'error_detection',d:'easy',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Each of the students / (B) in the banking class / (C) are expected to / (D) submit their assignment. / (E) No error',o:['A','B','C','D'],c:2,e:'"Each" is singular and always takes a singular verb. The correct form is "is expected to," not "are expected to." The error is in part C.',x:['sbi_prelims','sbi_mains']},

{id:'ed6',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The news about / (B) the bank mergers / (C) were shocking / (D) to the investors. / (E) No error',o:['A','B','C','D'],c:2,e:'"News" is an uncountable singular noun and always takes a singular verb. The correct form is "was shocking," not "were shocking." The error is in part C.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ed7',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Despite of his / (B) vast experience in / (C) banking, he failed / (D) the interview. / (E) No error',o:['A','B','C','D'],c:0,e:'"Despite" is a preposition that does not take "of." The correct usage is simply "Despite his vast experience..." — "despite of" is grammatically incorrect. The error is in part A.',x:['sbi_prelims','sbi_mains']},

{id:'ed8',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The data collected / (B) by the survey team / (C) suggests a decline / (D) in rural savings. / (E) No error',o:['A','B','C','D'],c:2,e:'"Data" is the plural form of "datum." In formal/academic usage, it takes a plural verb: "suggest," not "suggests." The error is in part C. (Note: In informal usage "data" is sometimes treated as singular, but in exam English, plural agreement is preferred.)',x:['sbi_mains','rbi_phase1']},

{id:'ed9',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) He is one of / (B) those officers who / (C) has always performed / (D) beyond expectations. / (E) No error',o:['A','B','C','D'],c:2,e:'In "one of those + plural noun + who/that" constructions, the relative clause verb agrees with the plural noun, not "one." So it should be "have always performed," not "has always performed." The error is in part C.',x:['sbi_mains','rbi_phase1']},

{id:'ed10',s:'english',t:'error_detection',d:'easy',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The bank will / (B) sanction the loan / (C) only if you will submit / (D) all required documents. / (E) No error',o:['A','B','C','D'],c:2,e:'In conditional sentences (Type 1), the "if" clause uses simple present tense, not future tense. Correct form: "only if you submit." Using "will submit" in the if-clause is grammatically incorrect. The error is in part C.',x:['sbi_prelims','sbi_mains']},

{id:'ed11',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The number of / (B) unemployed youth / (C) are increasing / (D) year after year. / (E) No error',o:['A','B','C','D'],c:2,e:'"The number of" takes a singular verb — the focus is on "the number," which is singular. Correct form: "is increasing." (Note: "A number of" takes a plural verb, but "The number of" takes singular.) Error is in part C.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ed12',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The policy, along with / (B) its amendments, have been / (C) approved by the / (D) parliamentary committee. / (E) No error',o:['A','B','C','D'],c:1,e:'When a singular subject is followed by "along with," "as well as," or "together with," the verb agrees with the main subject, not the additional phrase. "The policy" is singular, so "has been approved" is correct, not "have been." Error is in part B.',x:['sbi_mains','rbi_phase1']},

{id:'ed13',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) She has been / (B) working in this bank / (C) since the last / (D) five years. / (E) No error',o:['A','B','C','D'],c:2,e:'"Since" is used with a point in time (since 2010, since Monday). "For" is used with a period of time (for five years). The correct form is "for the last five years," not "since the last five years." Error is in part C.',x:['sbi_prelims','sbi_mains']},

{id:'ed14',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The manager asked / (B) the clerk that / (C) why he was absent / (D) without prior intimation. / (E) No error',o:['A','B','C','D'],c:1,e:'In indirect speech with a "why" question, "that" should not be used before the question word. The correct form is "the manager asked the clerk why he was absent." "That" is redundant and incorrect before "why." Error is in part B.',x:['sbi_prelims','sbi_mains']},

{id:'ed15',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) It is imperative / (B) that every employee / (C) follows the new / (D) compliance guidelines. / (E) No error',o:['A','B','C','D'],c:2,e:'After "It is imperative that," the verb in the subordinate clause must be in the subjunctive mood (base form), not the indicative. Correct form: "that every employee follow the new compliance guidelines" — not "follows." Error is in part C.',x:['sbi_mains','rbi_phase1']},

{id:'ed16',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Scarcely had / (B) the RBI announced / (C) the rate cut when / (D) markets rallied sharply. / (E) No error',o:['A','B','C','D'],c:3,e:'"Scarcely/Hardly/Barely" correctly pairs with "when" — not "than." The sentence "Scarcely had the RBI announced the rate cut when markets rallied sharply" is grammatically correct. There is no error. The answer is D (No error).',x:['sbi_mains','rbi_phase1']},

{id:'ed17',s:'english',t:'error_detection',d:'easy',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Ram and Shyam / (B) is going to attend / (C) the banking seminar / (D) next Monday. / (E) No error',o:['A','B','C','D'],c:1,e:'"Ram and Shyam" is a compound subject (plural). It requires a plural verb: "are going to attend," not "is going to attend." Error is in part B.',x:['sbi_prelims','sbi_mains']},

{id:'ed18',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) No sooner did / (B) the Finance Minister announce / (C) the budget than / (D) share prices dropped. / (E) No error',o:['A','B','C','D'],c:3,e:'The sentence uses "No sooner...than" correctly. "No sooner did the Finance Minister announce the budget than share prices dropped." This is grammatically correct. The answer is No Error (D — the last option).',x:['sbi_mains','rbi_phase1']},

{id:'ed19',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The inflation has / (B) risen by two percent / (C) in the last quarter / (D) of this fiscal. / (E) No error',o:['A','B','C','D'],c:0,e:'"Has risen" in part A implies recent past action with present relevance, which is used correctly here. However, "the inflation" is incorrect — inflation as a general concept does not take the definite article "the." It should be "Inflation has risen." Error is in part A.',x:['sbi_mains','rbi_phase1']},

{id:'ed20',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The robbers / (B) have fled away / (C) before the police / (D) arrived at the scene. / (E) No error',o:['A','B','C','D'],c:1,e:'"Fled" already implies moving away; "fled away" is redundant. The correct form is simply "had fled" (past perfect, since fleeing occurred before police arrived) — making both "away" and the tense in part B erroneous. The primary error is "fled away" (redundancy and tense) in part B.',x:['sbi_prelims','sbi_mains']},

{id:'ed21',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The RBI Governor, / (B) along with senior officials, / (C) were present at / (D) the G20 finance meet. / (E) No error',o:['A','B','C','D'],c:2,e:'When the subject "The RBI Governor" (singular) is followed by "along with senior officials," the verb agrees with the main subject. "Were present" should be "was present." Error is in part C.',x:['sbi_mains','rbi_phase1']},

{id:'ed22',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) He denied / (B) that he had not / (C) taken any bribe / (D) from the contractor. / (E) No error',o:['A','B','C','D'],c:1,e:'"Denied" already carries a negative meaning. Adding "not" in "denied that he had not taken" creates a double negative that reverses the intended meaning. Correct form: "He denied that he had taken any bribe." Remove "not." Error is in part B.',x:['sbi_mains','rbi_phase1']},

{id:'ed23',s:'english',t:'error_detection',d:'easy',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) My sister as well as / (B) my brothers / (C) are planning to / (D) join the banking sector. / (E) No error',o:['A','B','C','D'],c:2,e:'"My sister" is the main subject; "as well as my brothers" is a parenthetical addition. The verb should agree with "my sister" (singular): "is planning," not "are planning." Error is in part C.',x:['sbi_prelims','sbi_mains']},

{id:'ed24',s:'english',t:'error_detection',d:'hard',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) The committee recommended / (B) that the manager should / (C) be suspended for / (D) gross misconduct. / (E) No error',o:['A','B','C','D'],c:1,e:'After verbs of recommendation, suggestion, demand, insistence, etc., the subjunctive mood is used: "that the manager BE suspended." Using "should be" is common but not the grammatically prescribed form in formal English. Error is in part B.',x:['sbi_mains','rbi_phase1']},

{id:'ed25',s:'english',t:'error_detection',d:'medium',q:'Identify the part of the sentence that has a grammatical error:\n\n(A) Two-thirds of the / (B) work have already / (C) been completed by / (D) the project team. / (E) No error',o:['A','B','C','D'],c:1,e:'In fractions, when the noun after "of" is uncountable or refers to a whole ("work"), the verb is singular. "Two-thirds of the work HAS already been completed" is correct. "Have" is incorrect. Error is in part B.',x:['sbi_prelims','sbi_mains']},
);

// ═══════════════════════════════════════════════════════════════
// SENTENCE IMPROVEMENT (si1 to si20) — 20 questions
// ═══════════════════════════════════════════════════════════════

Q.push(
{id:'si1',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe officer was asked to look [into] the matter as soon as possible.',o:['look over','look into','look after','look up'],c:1,e:'"Look into" means to investigate or examine, which is the correct phrasal verb when examining a matter. "Look over" means to review briefly; "look after" means to take care of; "look up" means to search for information. No change is needed — "look into" is already correct and option B preserves it.',x:['sbi_prelims','sbi_mains']},

{id:'si2',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe bank manager insisted that the new policy [will be implemented] from the next quarter.',o:['would be implemented','will be implemented','should have been implemented','has been implemented'],c:0,e:'After "insisted that" (a reporting verb expressing demand/insistence), the subordinate clause uses "would" (past modal) or subjunctive. Since the main verb "insisted" is past tense, "would be implemented" is the correct form for reported speech.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'si3',s:'english',t:'sentence_improvement',d:'easy',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nShe is [more smarter] than her colleagues in financial analysis.',o:['smartest','smarter','more smart','most smartest'],c:1,e:'"More smarter" is a double comparative error. "Smart" is a one-syllable adjective and forms comparatives with "-er": "smarter." Never use "more" with "-er" forms. "Smarter than" is the correct construction.',x:['sbi_prelims','sbi_mains']},

{id:'si4',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe finance ministry [has been announced] a new scheme for rural credit last week.',o:['announced','has announced','have announced','was announcing'],c:0,e:'"Last week" is a specific past time reference, so simple past tense must be used: "announced." Present perfect ("has been announced," "has announced") cannot be used with specific past time expressions like "last week," "yesterday," or "in 2020."',x:['sbi_prelims','sbi_mains']},

{id:'si5',s:'english',t:'sentence_improvement',d:'hard',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nNeither the Chairman nor the board members [was] willing to accept the audit findings.',o:['were','was','are being','have been'],c:0,e:'In "Neither...nor" constructions, the verb agrees with the subject closest to it — "board members" (plural). So the correct verb is "were," not "was." Option A is correct.',x:['sbi_mains','rbi_phase1']},

{id:'si6',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe accused [admitted committing] the fraud when confronted with evidence.',o:['admitted to commit','admitted committing','admitted to have committed','admitted having commit'],c:1,e:'"Admit" is followed by a gerund (verb+ing), not an infinitive. "Admitted committing" is correct. "Admitted to commit" is wrong (infinitive after "to" is possible only in "admit to" + gerund form). "Admitted committing" (option B) is the standard correct form.',x:['sbi_mains','rbi_phase1']},

{id:'si7',s:'english',t:'sentence_improvement',d:'easy',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe government is working [hardly] to reduce unemployment in rural areas.',o:['hard','hardly','more harder','most hard'],c:0,e:'"Hard" functions both as an adjective and an adverb meaning "with great effort." "Hardly" is a different word meaning "scarcely" or "almost not." The sentence needs the adverb of intensity "hard" to mean working with great effort.',x:['sbi_prelims','sbi_mains']},

{id:'si8',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nBy the time the auditors arrived, the accounts [were already tampered] with.',o:['had already been tampered','were already tampered','have already been tampered','had already tampered'],c:0,e:'The action of tampering happened before the past action of auditors arriving — this requires past perfect passive: "had already been tampered with." "Were tampered" is simple past passive, which does not convey the chronological relationship correctly.',x:['sbi_mains','rbi_phase1']},

{id:'si9',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe economist suggested that India [should focuses] more on domestic demand.',o:['should focus','should focuses','must focuses','ought to focused'],c:0,e:'After modal verbs (should, must, will, etc.), the base form of the verb is used without "s" — "should focus," not "should focuses." Adding "s" after a modal verb is a common error.',x:['sbi_prelims','sbi_mains']},

{id:'si10',s:'english',t:'sentence_improvement',d:'hard',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nIt is high time the government [takes] strong action against financial fraudsters.',o:['took','takes','had taken','will take'],c:0,e:'"It is high time" is always followed by the past tense (subjunctive), even though the meaning is present or future: "It is high time the government TOOK strong action." Using simple present "takes" is incorrect in this construction.',x:['sbi_mains','rbi_phase1']},

{id:'si11',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe rupee has been [continuously depreciating] against the dollar for the past six months.',o:['continuously depreciating','continuous depreciating','continual depreciated','continually depreciated'],c:0,e:'"Has been depreciating" is present perfect continuous tense — used for an ongoing action that started in the past and continues. "Continuously depreciating" correctly uses the adverb form "continuously" with the present participle "depreciating." No change needed; option A preserves the original.',x:['sbi_prelims','sbi_mains']},

{id:'si12',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe bank [refrained] from making any comment on the allegations.',o:['refrained itself','refrained from','abstained from making','refraining from'],c:1,e:'"Refrain from" is the correct phrasal verb — it does not take a reflexive pronoun ("itself"). Option B "refrained from" is already correct. "Abstained from making" would work grammatically but changes the meaning slightly. The sentence as given is correct; the answer maintains "refrained from."',x:['sbi_prelims','sbi_mains']},

{id:'si13',s:'english',t:'sentence_improvement',d:'hard',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\n[Having completed] the audit, the report was submitted to the board.',o:['Having completed','After completing','When they completed','The auditors completing'],c:1,e:'The original sentence has a dangling participle — "Having completed the audit" implies the subject of the main clause (the report) completed the audit, which is illogical. "After completing the audit" still has this issue. The best correction is "After the auditors completed the audit, the report was submitted" — but among given options, "After completing" (option B) is the most acceptable standard correction used in exam contexts.',x:['sbi_mains','rbi_phase1']},

{id:'si14',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nShe is [used to work] late hours due to the workload during closing month.',o:['used to working','used to work','use to working','uses to work'],c:0,e:'"Be used to" (meaning accustomed to) is followed by a gerund (verb+ing): "used to working." Contrast with "used to + base verb" (past habit). Since the sentence describes habitual current behaviour (she is accustomed to), "used to working" is correct.',x:['sbi_prelims','sbi_mains']},

{id:'si15',s:'english',t:'sentence_improvement',d:'easy',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe seminar on banking reforms will be held [in] 15th March at the RBI headquarters.',o:['at','in','on','by'],c:2,e:'For specific dates, we use the preposition "on": "on 15th March." "In" is used for months/years; "at" is used for specific times. "On 15th March" is the correct form.',x:['sbi_prelims','sbi_mains']},

{id:'si16',s:'english',t:'sentence_improvement',d:'hard',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe board, [in addition to the CEO], have approved the merger proposal.',o:['in addition to the CEO, has','in addition to the CEO, have','along with CEO, have','besides the CEO, had'],c:0,e:'"The board" is the main subject (singular collective noun). Phrases introduced by "in addition to," "as well as," "together with" do not change the subject. "The board...has approved" is correct. Option A correctly uses "has" with the singular subject.',x:['sbi_mains','rbi_phase1']},

{id:'si17',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe new banking app is [convenient for use] by senior citizens.',o:['convenient to use','convenient for use','conveniently used','convenient using'],c:0,e:'"Convenient to use" (adjective + infinitive) is the standard correct construction in English. "Convenient for use" is awkward phrasing. The pattern "adjective + to + infinitive" (e.g., easy to use, difficult to understand, convenient to use) is grammatically preferred.',x:['sbi_prelims','sbi_mains']},

{id:'si18',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nAlthough the scheme was beneficial, [but] many farmers did not apply for it.',o:['yet','but','however','No improvement needed'],c:0,e:'"Although...but" is a double conjunction error — two subordinating/coordinating conjunctions cannot anchor the same clause. "Although...yet" is an accepted literary construction in formal English. Replacing "but" with "yet" corrects the error while preserving meaning.',x:['sbi_mains','rbi_phase1']},

{id:'si19',s:'english',t:'sentence_improvement',d:'hard',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nThe Finance Minister, together with his advisers, [were formulating] the new fiscal policy.',o:['was formulating','were formulating','have been formulating','are formulating'],c:0,e:'"The Finance Minister" is the singular main subject. "Together with his advisers" is a parenthetical phrase and does not change the subject number. Therefore, the singular verb "was formulating" is correct.',x:['sbi_mains','rbi_phase1']},

{id:'si20',s:'english',t:'sentence_improvement',d:'medium',q:'Which of the following, if substituted for the underlined part, makes the sentence grammatically correct and meaningful?\n\nI wish I [have] more time to prepare for the RBI Grade B examination.',o:['had','have','would have','will have'],c:0,e:'"I wish" expresses a hypothetical or contrary-to-fact situation. It is followed by the past subjunctive: "I wish I had more time." Using present tense "have" is incorrect after "wish" when referring to a present desire. "Would have" is used for past hypotheticals.',x:['sbi_prelims','sbi_mains','rbi_phase1']},
);

// ═══════════════════════════════════════════════════════════════
// CLOZE TEST (ct1_1 to ct3_5) — 15 questions
// ═══════════════════════════════════════════════════════════════

// ── CLOZE PASSAGE 1: Digital Banking Transformation ──
const CLOZE1_INTRO = `[Cloze Passage 1 — Digital Banking Transformation]\n\nThe Indian banking sector has undergone a __(1)__ transformation in recent years, driven primarily by technological innovation and regulatory support. Digital channels have __(2)__ traditional brick-and-mortar branches as the preferred mode of banking for millions of customers. The RBI's push for financial inclusion through mobile banking, internet banking, and UPI has __(3)__ access to formal financial services. Banks are now investing heavily in artificial intelligence to __(4)__ customer experience and detect fraudulent transactions. However, cybersecurity threats remain a __(5)__ concern, requiring constant upgradation of digital infrastructure.\n\n`;

Q.push(
{id:'ct1_1',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE1_INTRO}Q: Choose the most appropriate word for blank (1):\n"The Indian banking sector has undergone a __(1)__ transformation..."`,o:['marginal','profound','superficial','temporary'],c:1,e:'"Profound" means far-reaching and deep, which correctly describes the scale of transformation in Indian banking. "Marginal" and "superficial" imply minor changes (opposite meaning), while "temporary" contradicts the idea of structural change.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ct1_2',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE1_INTRO}Q: Choose the most appropriate word for blank (2):\n"Digital channels have __(2)__ traditional brick-and-mortar branches..."`,o:['supplemented','overshadowed','demolished','ignored'],c:1,e:'"Overshadowed" means to diminish the importance of something, which aptly describes how digital channels have made physical branches less prominent. "Supplemented" would mean added to (not replaced), "demolished" is too extreme, and "ignored" is inappropriate.',x:['sbi_prelims','sbi_mains']},

{id:'ct1_3',s:'english',t:'cloze_test',d:'easy',q:`${CLOZE1_INTRO}Q: Choose the most appropriate word for blank (3):\n"...has __(3)__ access to formal financial services."`,o:['restricted','democratised','commercialised','eliminated'],c:1,e:'"Democratised" means made something available to everyone regardless of social standing — perfectly describing financial inclusion. "Restricted" is the opposite. "Commercialised" means profit-focused, and "eliminated" means removed entirely.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ct1_4',s:'english',t:'cloze_test',d:'easy',q:`${CLOZE1_INTRO}Q: Choose the most appropriate word for blank (4):\n"Banks are now investing heavily in artificial intelligence to __(4)__ customer experience..."`,o:['degrade','enhance','monitor','restrict'],c:1,e:'"Enhance" means to improve or add value, which is the purpose of AI investment in banking — improving customer experience. "Degrade" is opposite; "monitor" and "restrict" do not fit the positive context of investment in AI for customer benefit.',x:['sbi_prelims','sbi_mains']},

{id:'ct1_5',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE1_INTRO}Q: Choose the most appropriate word for blank (5):\n"...cybersecurity threats remain a __(5)__ concern..."`,o:['trivial','persistent','resolved','technical'],c:1,e:'"Persistent" means continuing to exist despite efforts to address it — accurately describing cybersecurity threats in banking. "Trivial" means insignificant (opposite context), "resolved" means solved (contradicts "remain a concern"), and "technical" is too vague as a descriptor.',x:['sbi_prelims','sbi_mains','rbi_phase1']},
);

// ── CLOZE PASSAGE 2: RBI's Role in Economy ──
const CLOZE2_INTRO = `[Cloze Passage 2 — RBI's Role in the Economy]\n\nThe Reserve Bank of India __(1)__ as the central bank and monetary authority of the country. It is __(2)__ for formulating and implementing monetary policy to maintain price stability. The RBI also acts as a banker to the government and __(3)__ the foreign exchange reserves of India. In times of economic __(4)__, the RBI may cut interest rates to stimulate growth or raise them to __(5)__ inflationary pressures.\n\n`;

Q.push(
{id:'ct2_1',s:'english',t:'cloze_test',d:'easy',q:`${CLOZE2_INTRO}Q: Choose the most appropriate word for blank (1):\n"The Reserve Bank of India __(1)__ as the central bank..."`,o:['acts','acted','is acting','will act'],c:0,e:'"Acts" (simple present) is correct for stating a permanent role or institutional function. The RBI\'s role as central bank is an ongoing, established fact — simple present tense is appropriate for such universal truths.',x:['sbi_prelims','sbi_mains']},

{id:'ct2_2',s:'english',t:'cloze_test',d:'easy',q:`${CLOZE2_INTRO}Q: Choose the most appropriate word for blank (2):\n"It is __(2)__ for formulating and implementing monetary policy..."`,o:['criticised','responsible','blamed','celebrated'],c:1,e:'"Responsible for" is the standard phrase meaning having the duty or obligation to do something. "Criticised for," "blamed for," and "celebrated for" all change the meaning entirely and are contextually inappropriate.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ct2_3',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE2_INTRO}Q: Choose the most appropriate word for blank (3):\n"...and __(3)__ the foreign exchange reserves of India."`,o:['spends','manages','liquidates','borrows'],c:1,e:'"Manages" correctly describes the RBI\'s custodial role over India\'s foreign exchange reserves. The RBI manages and maintains these reserves. "Spends" and "liquidates" imply disposing of assets, while "borrows" is contextually wrong.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ct2_4',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE2_INTRO}Q: Choose the most appropriate word for blank (4):\n"In times of economic __(4)__, the RBI may cut interest rates..."`,o:['boom','slowdown','stability','surplus'],c:1,e:'The RBI cuts interest rates to stimulate growth — this action is taken during an economic "slowdown" (when growth is sluggish). During a "boom" or "stability," rate cuts are not typical. "Surplus" refers to finances, not economic conditions.',x:['sbi_prelims','sbi_mains']},

{id:'ct2_5',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE2_INTRO}Q: Choose the most appropriate word for blank (5):\n"...or raise them to __(5)__ inflationary pressures."`,o:['encourage','address','curb','ignite'],c:2,e:'"Curb" means to control or reduce — raising interest rates is used to curb (reduce) inflationary pressures by making borrowing more expensive, thus reducing money supply. "Encourage" and "ignite" mean to increase inflation (opposite). "Address" is too vague.',x:['sbi_prelims','sbi_mains','rbi_phase1']},
);

// ── CLOZE PASSAGE 3: Credit Rating & Investment ──
const CLOZE3_INTRO = `[Cloze Passage 3 — Credit Rating and Investment Climate]\n\nCredit rating agencies play a __(1)__ role in the financial markets by assessing the creditworthiness of borrowers, including governments and corporations. A high credit rating __(2)__ to investors that the borrower is financially sound and likely to repay debt obligations on time. Conversely, a downgrade in credit rating can __(3)__ capital outflows and increase borrowing costs significantly. India's credit rating has remained at the lowest investment __(4)__ by global agencies such as Moody's and S&P, reflecting both its growth potential and fiscal challenges. Improving the fiscal deficit and maintaining economic __(5)__ are key factors that could lead to a rating upgrade.`;

Q.push(
{id:'ct3_1',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE3_INTRO}\n\nQ: Choose the most appropriate word for blank (1):\n"Credit rating agencies play a __(1)__ role in the financial markets..."`,o:['marginal','pivotal','decorative','temporary'],c:1,e:'"Pivotal" means critically important — credit rating agencies have a fundamentally important role in financial markets, influencing investment decisions globally. "Marginal" means minor; "decorative" and "temporary" are clearly inappropriate.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'ct3_2',s:'english',t:'cloze_test',d:'easy',q:`${CLOZE3_INTRO}\n\nQ: Choose the most appropriate word for blank (2):\n"A high credit rating __(2)__ to investors that the borrower is financially sound..."`,o:['warns','signals','conceals','denies'],c:1,e:'"Signals" means sends a clear message or indication — a high credit rating signals financial soundness to investors. "Warns" implies danger (opposite meaning in this context); "conceals" and "denies" are antonyms of the intended meaning.',x:['sbi_prelims','sbi_mains']},

{id:'ct3_3',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE3_INTRO}\n\nQ: Choose the most appropriate word for blank (3):\n"...a downgrade in credit rating can __(3)__ capital outflows..."`,o:['prevent','reverse','trigger','welcome'],c:2,e:'"Trigger" means to cause or initiate — a credit rating downgrade triggers capital outflows as investors pull funds out of a country perceived as risky. "Prevent" and "reverse" suggest reduction of outflows, which is opposite. "Welcome" is contextually absurd.',x:['sbi_mains','rbi_phase1']},

{id:'ct3_4',s:'english',t:'cloze_test',d:'medium',q:`${CLOZE3_INTRO}\n\nQ: Choose the most appropriate word for blank (4):\n"India's credit rating has remained at the lowest investment __(4)__..."`,o:['class','grade','category','notch'],c:1,e:'In credit rating terminology, "investment grade" is the standard phrase denoting the tier of creditworthiness. "BBB-" or equivalent is typically the lowest investment grade rating. "Notch," "class," and "category" are not used in this specific financial context.',x:['sbi_mains','rbi_phase1']},

{id:'ct3_5',s:'english',t:'cloze_test',d:'hard',q:`${CLOZE3_INTRO}\n\nQ: Choose the most appropriate word for blank (5):\n"Improving the fiscal deficit and maintaining economic __(5)__ are key factors..."`,o:['turmoil','stagnation','resilience','inflation'],c:2,e:'"Resilience" means the ability to withstand shocks and recover — maintaining economic resilience is a positive factor that would lead to a credit rating upgrade. "Turmoil" and "stagnation" are negative conditions. "Inflation" is a challenge, not something to "maintain" positively.',x:['sbi_mains','rbi_phase1']},
);

// Total: adds ~95 questions to Q[]
