// ═══ ESI NOTES — Economic & Social Issues (RBI Grade B Paper I) ═══
// Comprehensive notes for RBI Grade B Phase 2 Paper I

const ESI_NOTES={
title:'Economic & Social Issues — Complete Study Material',
chapters:[
{
chapter:'Chapter 1: Growth and Development',
sections:[
{
heading:'1.1 Economic Growth vs Economic Development',
content:'Economic growth is a narrow concept referring to the increase in a country\'s real Gross Domestic Product (GDP) or per capita GDP over time. It is measured in purely quantitative terms — how much more output the economy is producing. Development, on the other hand, is a multidimensional concept that encompasses not just growth in income and output, but also improvements in the quality of life, reduction in poverty and inequality, expansion of freedoms, and enhancement of human capabilities. The Nobel Prize-winning economist Amartya Sen defined development as the expansion of human freedom — freedom from hunger, ignorance, ill health, insecurity, and deprivation. The United Nations Development Programme (UNDP) operationalizes development through the Human Development Index (HDI), which combines three dimensions: life expectancy (health), mean and expected years of schooling (education), and gross national income per capita (living standards). India\'s HDI score of 0.644 places it at rank 132 out of 193 countries in the 2023 Human Development Report, classified as "Medium Human Development." This highlights the gap between India\'s economic size (5th largest GDP) and its human development outcomes — a challenge known as the "paradox of plenty" in development economics.',
keyTerms:['GDP per capita','Human Development Index (HDI)','Sen\'s Capability Approach','UNDP Human Development Report','Medium Human Development'],
examTips:'RBI Grade B frequently asks about the difference between growth and development, HDI components, India\'s HDI rank, and Amartya Sen\'s contribution. Know the current year\'s HDI data.'
},{
heading:'1.2 Theories of Economic Development',
content:'Several theoretical frameworks have been proposed to explain how economies develop from low-income agricultural societies to high-income industrial economies. Arthur Lewis\'s Dual Sector Model (1954) — for which he received the Nobel Prize in 1979 — posits that developing economies have two sectors: a traditional (agricultural) sector with surplus labor and subsistence wages, and a modern (industrial) sector with higher productivity and wages. Development occurs as labor migrates from the traditional sector to the modern sector, driven by the wage differential. This process continues until the "Lewis Turning Point" — when the surplus labor in agriculture is exhausted and wages begin to rise in both sectors. India has not yet fully reached the Lewis Turning Point, evidenced by the large workforce still engaged in low-productivity agricultural employment.\n\nW.W. Rostow\'s Stages of Growth Theory (1960) identifies five stages through which all societies pass: (1) Traditional Society, (2) Preconditions for Take-off, (3) Take-off, (4) Drive to Maturity, and (5) Age of High Mass Consumption. According to Rostow, India is in the "Drive to Maturity" stage, characterized by diversified industrial activity, rising savings rate, and expanding technology adoption. The Take-off stage, which India entered in the 1990s, was characterized by a rise in investment rates from 5-10% to 10-20% of GDP, driven by the liberalization reforms of 1991.\n\nHarrod-Domar Model emphasizes the relationship between savings rate, capital-output ratio, and GDP growth rate. The model posits that g = s/v, where g is the growth rate, s is the savings ratio, and v is the capital-output ratio. For India, with a savings rate of approximately 30% and an ICOR (Incremental Capital-Output Ratio) of around 4, the model would predict a growth rate of approximately 7.5% — close to India\'s actual potential growth rate.\n\nEndogenous Growth Theory (Paul Romer, 1986) and New Growth Theory challenged the neoclassical view that technology is exogenously determined. These theories argue that long-run growth is driven by internal factors such as human capital accumulation, knowledge spillovers, R&D investment, and innovation. This has important policy implications — governments can sustainably raise long-run growth through education investment, R&D support, and policies that encourage innovation. India\'s National Education Policy 2020 and the National Research Foundation (NRF) are aligned with endogenous growth principles.',
keyTerms:['Lewis Dual Sector Model','Lewis Turning Point','Rostow\'s Stages of Growth','Harrod-Domar Model','Endogenous Growth Theory','ICOR'],
examTips:'Know the Lewis model in detail for RBI Grade B. The Lewis Turning Point is particularly important. Also understand why India\'s demographic dividend depends on avoiding premature deindustrialization.'
},{
heading:'1.3 India\'s Growth Story — Pre and Post Liberalization',
content:'India\'s economic history can be divided into distinct phases. The post-independence period (1947-1980) was characterized by mixed economy framework with strong state intervention — nationalization of key industries, planned economy through Five-Year Plans, industrial licensing (License Raj), and import substitution industrialization. Growth during this period was modest — the infamous "Hindu rate of growth" of approximately 3.5% per annum — insufficient to significantly improve per capita incomes given population growth of about 2.5% per annum.\n\nThe 1980s saw some liberalization of industrial policy and adoption of export-led growth strategies, pushing growth to approximately 5-6%. The 1991 Balance of Payments crisis proved to be the turning point. India\'s foreign exchange reserves fell to just 15 days of import cover, and the country had to pledge gold reserves with the Bank of England as collateral for an IMF loan. This crisis forced transformative structural reforms — liberalization (reducing license raj), privatization, and globalization (LPG reforms) — under then Prime Minister P.V. Narasimha Rao and Finance Minister Manmohan Singh.\n\nPost-1991 reforms unleashed India\'s economic potential. The reforms included: dismantling industrial licensing in most sectors, reducing import tariffs from peak rates of 150%+ to 35% over a decade, allowing FDI across sectors, financial sector liberalization (new private bank licenses, capital market development), and external sector liberalization. GDP growth accelerated to 6-8% per annum in the 1990s and 2000s, driven by services sector (particularly IT/ITES) rather than manufacturing as seen in East Asian growth stories.\n\nThe 2004-2014 period saw India emerge as one of the world\'s fastest-growing major economies, with growth peaking at 9%+ in 2007-08. However, the post-2011 period saw growth slowdown due to high inflation, twin deficits (fiscal and current account), policy paralysis in project approvals, and global headwinds. The National Democratic Alliance (NDA) government from 2014 introduced structural reforms: Goods and Services Tax (GST) 2017, Insolvency and Bankruptcy Code (IBC) 2016, Real Estate (Regulation and Development) Act (RERA) 2016, PMJDY financial inclusion drive, and the JAM trinity (Jan Dhan-Aadhaar-Mobile). India\'s GDP grew at 8.2% in FY2023-24, the fastest among major economies, driven by strong domestic demand, government capital expenditure, and services sector resilience.',
keyTerms:['License Raj','Hindu rate of growth','1991 BOP Crisis','LPG Reforms','GDP growth trajectory','Structural reforms'],
examTips:'The 1991 reforms and their context are VERY frequently asked in RBI Grade B. Know the specific measures taken and their impact. Also understand the pre-reform economic model and why it failed.'
}
]},{
chapter:'Chapter 2: Poverty and Inequality',
sections:[
{
heading:'2.1 Poverty Measurement in India',
content:'Poverty measurement in India has evolved significantly over the decades, reflecting changing understanding of poverty\'s multidimensional nature. The traditional approach used income or consumption expenditure as the single criterion. The Planning Commission calculated poverty lines based on caloric intake requirements — a minimum of 2,100 calories per day in urban areas and 2,400 calories in rural areas — combined with non-food spending requirements.\n\nSeveral expert committees have revised poverty estimates: The Tendulkar Committee (2009) recommended moving away from calorie-based poverty lines to a consumption expenditure approach that includes non-food expenditures on health and education. The resulting poverty line (₹32/day rural, ₹47/day urban in 2011-12 prices) was controversial for being considered too low. The Rangarajan Committee (2014), appointed after criticism of Tendulkar\'s methodology, recommended higher poverty lines (₹32 rural and ₹47 urban vs ₹27 and ₹33 by Tendulkar). This gave a poverty headcount of 29.5% vs Tendulkar\'s estimate of 21.9% for 2011-12.\n\nMost recently, India has adopted the Multidimensional Poverty Index (MPI) approach, jointly developed by UNDP and Oxford Poverty and Human Development Initiative (OPHI). The MPI measures acute poverty across three dimensions and 10 indicators: Health (nutrition, child mortality), Education (years of schooling, school attendance), and Living Standards (cooking fuel, sanitation, drinking water, electricity, housing, assets). A person is considered multidimensionally poor if they are deprived in at least one-third of the weighted indicators.\n\nNITI Aayog\'s National MPI for India (2023) showed remarkable progress: 24.82 crore people were lifted out of multidimensional poverty between 2013-14 and 2022-23 — one of the fastest poverty reductions globally. The MPI headcount fell from 29.17% in 2013-14 to 11.28% in 2022-23. States that showed the greatest improvement included Uttar Pradesh, Bihar, Madhya Pradesh, Rajasthan, and Odisha — traditionally high-poverty states. Chhattisgarh, Uttarakhand, and Tripura showed the fastest rate of change.',
keyTerms:['Tendulkar Committee','Rangarajan Committee','Multidimensional Poverty Index (MPI)','NITI Aayog MPI','OPHI','Poverty headcount'],
examTips:'Know the specific poverty line figures and committee names. The MPI India 2023 data (11.28% poverty, 24.82 crore lifted from poverty) is highly exam-relevant for RBI Grade B.'
},{
heading:'2.2 Inequality in India',
content:'While poverty has been declining in India, inequality has been rising — a phenomenon economists call "growth with inequality." India\'s Gini coefficient (a measure of income inequality where 0 = perfect equality and 1 = perfect inequality) is approximately 0.35, indicating moderate inequality. However, this masks the extreme concentration of wealth at the very top. Oxfam\'s Survival of the Richest report (2023) found that India\'s richest 1% hold more than 40% of the nation\'s total wealth — a level of concentration that threatens social cohesion and democratic governance.\n\nBetween 2012 and 2021, the bottom 50% of India\'s population saw their income share decline from 14.7% to 13.1%, while the top 1%\'s income share rose from 21.7% to 22.6%. This rising inequality is driven by multiple factors: skill-biased technological change (technology increases demand for high-skill workers), globalization (benefits high-skill, tradeable sectors), unequal access to quality education and healthcare, urban-rural divide, and concentration of financial assets.\n\nThe Kuznets Curve hypothesis (Simon Kuznets, 1955) suggests that inequality initially rises as a country industrializes and then falls as it develops further — an inverted U-shape relationship between per capita income and inequality. India appears to be in the rising portion of the Kuznets curve. However, many economists dispute that the declining portion is automatic — active redistributive policies are needed.\n\nPolicy responses to inequality in India include: progressive direct taxation, GST compensation to states for revenue loss on essential items (lower GST rates on essentials), MGNREGS rural employment guarantee, public health and education spending, PMAY housing for all, PM-KISAN income support, and direct benefit transfers (DBT). The DBT system has transferred ₹34 lakh crore+ directly to beneficiaries since 2013, significantly reducing leakages and ensuring benefits reach intended recipients.',
keyTerms:['Gini Coefficient','Kuznets Curve','Oxfam inequality report','Skill-biased technological change','Urban-rural divide','Direct Benefit Transfer'],
examTips:'Gini coefficient value for India, Kuznets hypothesis, and the recent Oxfam data are frequent exam topics. Know the various anti-inequality policies and their mechanisms.'
}
]},{
chapter:'Chapter 3: Indian Financial System',
sections:[
{
heading:'3.1 Structure of Indian Financial System',
content:'The Indian financial system is a complex network of financial institutions, markets, instruments, and services that channels savings from surplus units to deficit units. It can be divided into organized and unorganized sectors. The organized sector comprises: (1) Banking sector — commercial banks (PSBs, private, foreign), cooperative banks (urban and rural), regional rural banks (RRBs), payments banks, and small finance banks; (2) Non-Banking Financial Companies (NBFCs); (3) Insurance sector — life and non-life; (4) Pension funds — PFRDA-regulated; (5) Capital markets — stock exchanges (BSE, NSE), commodity exchanges; (6) Financial infrastructure — depositories (NSDL, CDSL), credit information companies (CIBIL, Equifax), credit rating agencies (CRISIL, ICRA, CARE).\n\nThe Reserve Bank of India (RBI) is the apex regulatory body for banks, NBFCs, and payment systems. SEBI regulates capital markets and collective investment schemes. IRDAI regulates insurance. PFRDA regulates pension. IFC-AA (IFSCA) regulates International Financial Services Centres (GIFT City). This multi-regulatory structure reflects the specialization of different financial sectors, but also creates regulatory arbitrage challenges — financial entities may migrate to less-regulated sectors to escape stringent norms.\n\nThe financial system performs five core functions: (1) Mobilization of savings — pooling dispersed household savings; (2) Allocation of capital — directing funds to most productive uses; (3) Risk management — spreading and mitigating financial risks through insurance, derivatives, and diversification; (4) Payment facilitation — enabling smooth exchange of goods and services; (5) Price discovery — determining fair prices for financial assets through market mechanisms. The efficiency with which these functions are performed determines a financial system\'s contribution to economic growth.',
keyTerms:['RBI','SEBI','IRDAI','PFRDA','IFSCA','Financial system functions','NBFC'],
examTips:'Know all the regulators and their jurisdictions thoroughly. Financial system structure is repeatedly tested in RBI Grade B Phase 1 and Phase 2.'
},{
heading:'3.2 Monetary Policy Framework',
content:'India adopted a formal Flexible Inflation Targeting (FIT) framework through an amendment to the RBI Act in 2016. The framework mandates the Monetary Policy Committee (MPC) to achieve the primary objective of price stability — a CPI inflation target of 4% within a tolerance band of ±2% (i.e., 2% to 6%) — while keeping in mind the objective of growth. The inflation target is set by the Government of India in consultation with RBI for a 5-year period.\n\nThe MPC is a six-member committee: three members from RBI (Governor as chairperson, Deputy Governor in-charge of monetary policy, and one officer from RBI) and three external members appointed by the Central Government. Decisions are by majority vote; in case of tie, the Governor has the casting vote. The MPC meets at least four times a year (in practice, six times), and its deliberations are published in the form of minutes 14 days after the policy statement. The main policy rate is the Repo Rate — the rate at which RBI lends overnight against collateral (government securities) to commercial banks.\n\nMonetary policy transmission refers to the process by which changes in the policy repo rate affect various interest rates in the economy and ultimately influence inflation and output. The transmission channels include: (1) Interest rate channel — higher repo rate → higher bank lending rates → reduced credit demand → lower consumption and investment → lower inflation; (2) Credit channel — higher rates → reduced bank lending → credit crunch → lower investment; (3) Exchange rate channel — higher rates attract capital → rupee appreciates → cheaper imports → lower inflation; (4) Asset price channel — higher rates reduce asset values → negative wealth effect → lower consumption; (5) Expectations channel — RBI\'s forward guidance shapes inflation expectations.\n\nA key challenge in India\'s monetary transmission is the "long and variable lags" — the full effect of a rate change takes 3-6 quarters to materialize. Additionally, transmission was incomplete under the MCLR system because banks\' deposit costs didn\'t adjust immediately. The External Benchmark Rate (EBR) system, mandated from October 2019 for new floating rate retail loans, links loan rates directly to the repo rate, ensuring faster and more complete transmission. Another transmission challenge is the dominance of administered interest rates (post office savings, small savings) that don\'t respond to repo rate changes, creating a floor for bank deposit rates.',
keyTerms:['Flexible Inflation Targeting','MPC','Repo Rate','Monetary policy transmission','External Benchmark Rate','Forward guidance'],
examTips:'The MPC structure, inflation target (4%±2%), and transmission mechanisms are core RBI Grade B topics. The external benchmark system and its impact on transmission is particularly important.'
},{
heading:'3.3 Fiscal Policy and the Union Budget',
content:'Fiscal policy refers to the government\'s use of taxation and expenditure to influence macroeconomic conditions — aggregate demand, employment, inflation, and growth. The Union Budget, presented annually by the Finance Minister in Parliament (usually on February 1), is the primary instrument of fiscal policy. It contains the government\'s revenue and expenditure plans for the upcoming financial year (April-March).\n\nThe budget has two accounts: Revenue Account (day-to-day operations — salaries, subsidies, interest payments, grants) and Capital Account (asset creation and reduction of liabilities — infrastructure, acquisition of assets, loan repayments). A balanced budget means revenue receipts = revenue expenditure. The Revenue Deficit (= revenue expenditure - revenue receipts) indicates that the government is borrowing to finance current operations — considered fiscally imprudent. The Fiscal Deficit (= total expenditure - total receipts excluding borrowings) is the most important fiscal indicator, representing the total borrowing requirement of the government.\n\nThe Primary Deficit = Fiscal Deficit - Net Interest Payments. It represents the deficit excluding the debt service burden, giving a cleaner picture of the government\'s current fiscal stance. India\'s Union Budget 2024-25 targets: Fiscal Deficit at 4.9% of GDP (down from 5.8% in FY23), Revenue Deficit at 2.0% of GDP, Capital Expenditure at ₹11.11 lakh crore (3.4% of GDP).\n\nThe Fiscal Responsibility and Budget Management (FRBM) Act, 2003 was enacted to institutionalize fiscal discipline. The Act originally mandated bringing fiscal deficit to 3% of GDP by 2008-09, though this timeline has been repeatedly revised. The NK Singh Committee (2016) recommended a fiscal deficit target of 2.5% by 2022-23 and a central government debt-to-GDP ratio of 40% by 2022-23 (current: ~56%). The escape clause under FRBM allows deviations in extraordinary circumstances (like COVID-19), but the government must present a path back to target.\n\nGST (Goods and Services Tax), implemented from July 1, 2017, represented India\'s most significant indirect tax reform since independence. It replaced a complex web of central and state taxes (central excise, service tax, VAT, entry tax, etc.) with a unified tax structure. GST follows a dual structure — central GST (CGST) levied by Centre and state GST (SGST) levied by states simultaneously. For inter-state transactions, Integrated GST (IGST) applies. GST has four tax slabs: 5%, 12%, 18%, and 28% (plus cess on luxury/demerit goods). Essential items are either exempt or taxed at 0-5%, while demerit goods face 28%+cess.',
keyTerms:['Union Budget','Revenue Deficit','Fiscal Deficit','Primary Deficit','FRBM Act','Capital expenditure','GST'],
examTips:'Know the fiscal deficit targets, FRBM provisions, and GST structure thoroughly. Budget numbers for the current year are essential for RBI Grade B.'
}
]},{
chapter:'Chapter 4: External Sector',
sections:[
{
heading:'4.1 Balance of Payments',
content:'The Balance of Payments (BoP) is a systematic record of all economic transactions between residents of one country and the rest of the world during a specific period. It consists of three accounts: Current Account, Capital Account, and Financial Account (the three-account classification used by IMF).\n\nThe Current Account records: (a) Merchandise trade (exports and imports of goods) — India\'s merchandise trade deficit is typically $200-250 billion annually, as India imports more goods than it exports; (b) Services trade — India has a surplus (exports of IT/ITES, tourism, financial services exceed imports); (c) Primary income — investment income flows (dividends, interest, compensation); (d) Secondary income — transfers (most important: remittances from Indian diaspora, which at $125 billion+ annually are the world\'s largest).\n\nThe Capital Account records: Capital transfers (debt forgiveness, non-financial assets, intangibles like patents) — very small in India\'s case.\n\nThe Financial Account records: Foreign Direct Investment (FDI) — long-term capital with management control; Foreign Portfolio Investment (FPI) — short-term capital in stocks and bonds without management control; External Commercial Borrowings (ECB); Banking capital flows; Reserve assets changes.\n\nIndia\'s BoP dynamics: The Current Account Deficit (CAD) — when current account expenditure exceeds receipts — is a key vulnerability indicator. India\'s CAD surged to 2.7% of GDP in FY2022-23 due to high commodity prices (oil, gold) but fell to approximately 0.9% in FY2023-24 as commodity prices moderated and services exports grew strongly. India\'s CAD is typically financed by FDI and FPI inflows. When these inflows are insufficient (as in 2013\'s "Taper Tantrum"), the rupee depreciates sharply.\n\nIndia\'s Forex Reserves (managed by RBI) are the third/fourth largest in the world at approximately $640 billion (2024), representing about 10 months of merchandise import cover. This compares favorably with the rule-of-thumb minimum of 3 months. Adequate reserves are a crucial buffer against external shocks.',
keyTerms:['Balance of Payments','Current Account Deficit','CAD','FDI vs FPI','Remittances','Forex Reserves','Taper Tantrum'],
examTips:'Know the BoP structure, India\'s CAD numbers, remittance figures, and forex reserve levels. The 2013 currency crisis and its causes (twin deficits, taper tantrum) is frequently examined.'
},{
heading:'4.2 India\'s Trade Policy',
content:'India\'s external trade policy has evolved significantly from the autarkic (self-sufficient) import substitution model of the pre-1991 era to a more open, export-oriented approach. The Directorate General of Foreign Trade (DGFT) under the Ministry of Commerce & Industry formulates and implements foreign trade policy. The Foreign Trade Policy (FTP) is announced for a 5-year period, with the latest FTP announced in March 2023 focusing on reaching $2 trillion in merchandise and services exports by 2030.\n\nKey instruments of trade policy include: (a) Tariffs (customs duties) — India\'s average applied tariff rate has fallen from 80%+ in 1991 to about 15% today for non-agricultural products; (b) Non-tariff barriers (NTBs) — sanitary and phytosanitary standards, technical barriers, import licensing; (c) Export promotion — Advance Authorization Scheme, Duty Drawback, Export Oriented Units (EOUs), Special Economic Zones (SEZs), Merchandise Exports from India Scheme (MEIS replaced by RoDTEP); (d) Import substitution — PLI scheme, Make in India, phased manufacturing programs.\n\nIndia\'s merchandise trade deficit has been structural — India imports significantly more than it exports in goods. The top merchandise imports are crude petroleum, gold, electronic goods, and machinery. Top exports are petroleum products (refined), gems & jewelry, pharmaceuticals, engineering goods, and textiles. India has a large services trade surplus (IT/ITES, business services, travel) that partially offsets the merchandise deficit.\n\nIndia has signed Free Trade Agreements (FTAs) with ASEAN, UAE, Australia, and is negotiating with the UK and EU. India withdrew from RCEP in 2019 over concerns about Chinese goods flooding the market and inadequate concessions on services. The government\'s cautious approach to trade liberalization reflects the need to protect domestic industry, especially agriculture and MSMEs, from import competition.',
keyTerms:['Foreign Trade Policy','DGFT','Tariff','Non-tariff barriers','SEZ','FTA','RCEP','PLI scheme'],
examTips:'Trade policy instruments, India\'s trade composition, and FTA negotiations are important for RBI Grade B. Know why India left RCEP and the arguments for and against further trade liberalization.'
}
]},{
chapter:'Chapter 5: Agriculture & Rural Development',
sections:[
{
heading:'5.1 Importance and Challenges of Indian Agriculture',
content:'Agriculture in India occupies a position of extraordinary importance — it contributes approximately 18% to GDP, employs around 47% of the workforce (though this figure is declining), and provides food security for 1.4 billion people. India is the world\'s largest producer of spices, pulses, and jute, and among the top producers of rice, wheat, sugarcane, cotton, and fruits/vegetables. The sector is predominantly smallholder-based — 86% of farm holdings are less than 2 hectares (classified as marginal and small farmers) — which creates challenges of scale, credit access, and technology adoption.\n\nThe productivity gap between Indian agriculture and global benchmarks is substantial. India\'s rice yield (3.1 tonnes/hectare) is significantly below China\'s (6.9 tonnes/hectare) and even below the global average. Similar gaps exist for most crops. The causes include: (a) Fragmented landholdings that prevent mechanization; (b) Irrigation deficit — only 45% of gross cropped area is irrigated, leaving rest rain-dependent; (c) Soil degradation from overuse of chemical fertilizers; (d) Crop pattern distortions from MSP and free power/water for paddy and wheat in Punjab-Haryana; (e) Limited post-harvest infrastructure leading to 15-20% losses; (f) Weak price discovery and marketing through fragmented, regulated APMCs (Agricultural Produce Market Committees).\n\nThe Green Revolution of the 1960s (introduction of High-Yielding Variety seeds, fertilizers, and irrigation) dramatically increased wheat and rice production, ending India\'s chronic food shortages. However, it also created regional imbalances (concentrated in Punjab, Haryana, Western UP), environmental degradation (groundwater depletion, soil salinization), and overdependence on rice-wheat rotation. The Second Green Revolution, focusing on diversification, eastern India, pulses and oilseeds, and sustainable farming, is now a policy priority.\n\nKey government interventions in agriculture: Minimum Support Price (MSP) — announced before sowing season for 23 crops; Agricultural credit target (₹20 lakh crore in FY2023-24); Kisan Credit Cards; Pradhan Mantri Fasal Bima Yojana (crop insurance); PM-KISAN income support (₹6,000/year); e-NAM (electronic National Agriculture Market); Soil Health Cards; PM Krishi Sinchayee Yojana (irrigation); and Agricultural Infrastructure Fund.',
keyTerms:['Agricultural productivity gap','Green Revolution','MSP','PMFBY','PM-KISAN','e-NAM','APMC reforms','Kisan Credit Card'],
examTips:'Agriculture\'s share in GDP, employment, and the various schemes (MSP, KCC, PMFBY, PM-KISAN) are core ESI topics. The Green Revolution\'s benefits and drawbacks, and APMC reforms, are particularly important.'
}
]},{
chapter:'Chapter 6: Industry and Services Sector',
sections:[
{
heading:'6.1 Industrial Policy and Manufacturing',
content:'India\'s industrial policy has undergone fundamental transformation from state-directed, license-based industrialization to a market-friendly, globally competitive framework. The Industries (Development and Regulation) Act, 1951 established the framework for industrial licensing, which required government approval for establishing, expanding, or changing production of licensed industries. The 1991 reforms abolished industrial licensing for all but a few sensitive sectors (defense, atomic energy, hazardous chemicals) — a watershed reform that unleashed private sector dynamism.\n\nThe Make in India initiative, launched in 2014, aims to increase manufacturing\'s share of GDP from 17% to 25% by 2025 (target now extended) and create 100 million manufacturing jobs. It focuses on 25 sectors identified as growth drivers including automobiles, pharmaceuticals, defense, aerospace, IT and electronics, food processing, and renewable energy. The Production Linked Incentive (PLI) scheme, launched in 2020, provides financial incentives of 4-6% of incremental sales over 5 years to manufacturing companies in 14 identified sectors. The total PLI outlay of approximately ₹1.97 lakh crore aims to attract domestic and foreign manufacturing investment, reduce import dependence, and boost exports.\n\nMicro, Small and Medium Enterprises (MSMEs) form the backbone of India\'s industrial sector. The MSME sector: contributes 30% to GDP, 45% to exports, accounts for 45% of total employment in India, and comprises 6.3 crore+ enterprises. MSMEs are classified (revised from June 2020) based on investment in plant/machinery and turnover: Micro (investment ≤₹1 crore, turnover ≤₹5 crore), Small (≤₹10 crore, ≤₹50 crore), Medium (≤₹50 crore, ≤₹250 crore). MSMEs face challenges including limited access to formal credit (₹25 lakh crore credit gap), technological obsolescence, lack of scale, difficulty in accessing markets, and limited R&D capability.',
keyTerms:['Industrial licensing','Make in India','PLI scheme','MSME definition','MSME credit gap','Manufacturing share of GDP'],
examTips:'PLI scheme details (sectors, amount, objectives), MSME revised definition, and industrial policy evolution are important ESI topics for RBI Grade B.'
}
]},{
chapter:'Chapter 7: Social Sector',
sections:[
{
heading:'7.1 Education and Skill Development',
content:'India\'s education system, one of the world\'s largest with over 1.5 million schools and 40,000+ higher education institutions, faces twin challenges of access and quality. The Right to Education Act (RTE) 2009 mandates free and compulsory education for children aged 6-14 years, leading to near-universal primary school enrollment. However, learning outcomes remain poor — the Annual Status of Education Report (ASER) consistently shows that many children in upper primary classes cannot read simple text or do basic arithmetic.\n\nThe National Education Policy (NEP) 2020 represents the first comprehensive education reform since 1986. Key features: (a) New pedagogical structure replacing 10+2 with 5+3+3+4 system (Foundational: 5 years, Preparatory: 3 years, Middle: 3 years, Secondary: 4 years); (b) Emphasis on mother tongue or regional language as medium of instruction till Class 5; (c) Multidisciplinary approach at higher education level; (d) Multiple entry-exit points in higher education with Academic Bank of Credits; (e) Target to increase Gross Enrollment Ratio (GER) in higher education from 26.3% to 50% by 2035; (f) Establishment of National Research Foundation (NRF) with ₹50,000 crore outlay over 5 years to fund research and innovation.\n\nIndia faces a severe skill development challenge — the National Skill Development Corporation (NSDC) estimates that 400+ million people will need skilled training by 2022 (already behind). The Skill India Mission (2015) aims to train 40 crore people across industries. The Pradhan Mantri Kaushal Vikas Yojana (PMKVY) is the flagship scheme providing short-term skill training. The Recognition of Prior Learning (RPL) component certifies existing workers\' informal skills. India\'s low skill profile — only 5.4% of workforce (aged 15-59) has formal vocational training, compared to 52% in USA, 74% in Germany, and 80% in Japan — is a major constraint on productivity and income.',
keyTerms:['Right to Education','National Education Policy 2020','ASER','Gross Enrollment Ratio','Skill India','PMKVY','NSDC'],
examTips:'NEP 2020 details, learning outcomes data (ASER), and skill development schemes are ESI exam favorites. Know the 5+3+3+4 structure and GER target.'
},{
heading:'7.2 Health Sector',
content:'India\'s health system faces both a quantitative challenge (insufficient infrastructure and personnel) and a qualitative challenge (inequitable access and poor outcomes in some areas). India spends approximately 3.8% of GDP on health (2023) — below the WHO recommendation of 5%+ for developing countries. Public health expenditure is about 2.1% of GDP, compared to 8-10% in advanced economies. The low public expenditure forces high out-of-pocket (OOP) healthcare spending — approximately 48% of total health expenditure in India is OOP, among the highest globally, causing catastrophic health expenditure for millions of households.\n\nKey health metrics: Life expectancy (2023): 67.7 years (Male: 66.5, Female: 69). Infant Mortality Rate (IMR): 27 per 1,000 live births (2020) — improved from 80 in 1990 but still above target of SDG (25 by 2030). Maternal Mortality Ratio (MMR): 97 per 100,000 live births (2018-20) — improved dramatically from 556 in 1990. These improvements reflect the impact of government programs: National Rural Health Mission (NRHM), Janani Suraksha Yojana (institutional deliveries), Pradhan Mantri Suraksha Matritva Abhiyan, and Poshan Abhiyaan (nutrition).\n\nPradhan Mantri Jan Arogya Yojana (PM-JAY), launched in 2018 under Ayushman Bharat, provides health insurance cover of ₹5 lakh per family per year for secondary and tertiary care to the bottom 40% of India\'s population (approximately 55 crore beneficiaries). It is the world\'s largest government-funded health insurance scheme. Ayushman Bharat also includes Health and Wellness Centres (HWCs) at sub-centre and primary health centre levels to provide comprehensive primary health care.\n\nIndia faces the "triple burden of disease" — communicable diseases (tuberculosis, malaria, HIV/AIDS), non-communicable diseases (diabetes, cardiovascular diseases, cancer, which now account for 63% of deaths), and injuries/accidents. The COVID-19 pandemic highlighted India\'s health system vulnerabilities while also accelerating digital health (e-Sanjeevani telemedicine, Ayushman Bharat Digital Mission creating Abha health IDs).',
keyTerms:['Out-of-pocket expenditure','Ayushman Bharat PM-JAY','National Rural Health Mission','Infant Mortality Rate','Maternal Mortality Rate','Triple burden of disease','Ayushman Bharat Digital Mission'],
examTips:'PM-JAY details (₹5 lakh cover, 55 crore beneficiaries), health statistics (life expectancy, IMR, MMR), and Ayushman Bharat Digital Mission are important ESI topics.'
}
]},{
chapter:'Chapter 8: Money, Banking & Inflation',
sections:[
{
heading:'8.1 Money Supply and Monetary Aggregates',
content:'Money supply is the total stock of money in circulation in an economy at a given point of time. The Reserve Bank of India publishes four monetary aggregates: M0, M1, M2, and M3.\n\nM0 (Reserve Money or High-Powered Money) = Currency in Circulation + Banker\'s Deposits with RBI + Other Deposits with RBI. M0 is also called the monetary base because it forms the base on which commercial banks create credit through the money multiplier mechanism.\n\nM1 (Narrow Money) = Currency with Public + Demand Deposits with Banks + Other Deposits with RBI. M1 measures the most liquid components of money supply — currency in hand and deposits withdrawable on demand.\n\nM2 = M1 + Savings Deposits with Post Office Savings Banks. This includes the savings deposits at post offices.\n\nM3 (Broad Money) = M1 + Time Deposits with Banks. M3 is the most comprehensive measure of money supply and is used as the primary policy target by RBI. Currently, India\'s M3 exceeds ₹220 lakh crore.\n\nThe money multiplier (m) relates M3 to M0: M3 = m × M0, where m = (1+c)/(c+r). Here, c = currency-deposit ratio (public\'s preference for holding currency vs bank deposits) and r = reserve ratio (fraction of deposits banks keep as reserves, primarily CRR+SLR). A higher CRR reduces the money multiplier, reducing credit creation. This is how RBI uses CRR as a monetary control tool.\n\nQuantity Theory of Money (Irving Fisher): MV = PT, where M = money supply, V = velocity of money, P = price level, T = transactions/output. In growth rate form: m + v = p + y (where lowercase = growth rates). If V is stable and output (y) grows at potential, any excess money growth translates into inflation (p). This forms the basis for monetary targeting — central banks targeting money supply growth to control inflation.',
keyTerms:['M0','M1','M3','Money multiplier','Reserve Money','Currency-deposit ratio','Quantity Theory of Money'],
examTips:'Know all four monetary aggregates (M0 to M3) and their components. The money multiplier formula and its relationship to CRR/SLR is frequently tested.'
}
]}
]};
