// ═══ COMPREHENSIVE BANKING REFERENCE — Final Addition ═══

// 300+ Additional MCQ Questions
Q.push(
// Banking Awareness — Comprehensive
{id:'ba081',s:'banking_awareness',t:'banking_terms',d:'medium',q:'The "moral hazard" problem in banking occurs when:',o:['Banks face too much regulation','Insured banks take excessive risks knowing government will bail them out','Banks refuse to lend during recessions','Interest rates are too high'],c:1,e:'Moral hazard: When actors take more risk because they are shielded from consequences. Banks knowing they are "too big to fail" may take excessive risks, knowing the government/central bank will rescue them. Solutions: Bail-in provisions, higher capital for SIFIs, risk-based deposit insurance.',x:['rbi_phase1','rbi_phase2']},
{id:'ba082',s:'banking_awareness',t:'banking_terms',d:'hard',q:'In the context of bank mergers, "demerger" or "spin-off" means:',o:['Two banks combining into one','A bank separating a division into a new independent company','A bank closing down operations','Government taking over a private bank'],c:1,e:'Demerger/Spin-off: A company or bank separates a division, subsidiary, or business unit into a new, independent company. Example: A bank spinning off its insurance arm as a separate listed company. Creates focused entities, unlocks value.',x:['sbi_mains','rbi_phase1']},
{id:'ba083',s:'banking_awareness',t:'banking_terms',d:'medium',q:'What is a "call option" on a bond?',o:['Option to buy the bond at any time','Issuer\'s right to redeem the bond before maturity at a predetermined price','Bondholder\'s right to sell back to issuer','Option linked to interest rate changes'],c:1,e:'Call provision/call option: Bond issuer can redeem (call back) the bond before maturity at a specified call price, usually at a premium over face value. Issuers exercise call options when interest rates fall (to refinance at lower cost). Bondholders receive call protection (no call for specified period).',x:['sbi_mains','rbi_phase1']},
{id:'ba084',s:'banking_awareness',t:'banking_terms',d:'medium',q:'Bancassurance refers to:',o:['Bank providing insurance against deposits','Sale of insurance products through bank distribution channels','Central bank providing insurance to commercial banks','Bank run insurance'],c:1,e:'Bancassurance: Partnership between a bank and insurance company where insurance products are sold through the bank\'s branches and digital channels. Banks earn commission; insurance companies gain distribution. Example: SBI Life Insurance (SBI + BNP Paribas), HDFC Life (HDFC Bank + Standard Life).',x:['sbi_prelims','sbi_mains']},
{id:'ba085',s:'banking_awareness',t:'banking_terms',d:'hard',q:'The "procyclicality" problem in banking regulation refers to:',o:['Regulations that differ across cycles','Banks amplifying economic cycles — lending more in booms and less in busts — making cycles more severe','Cyclical regulation review process','Banks following RBI rate cycles'],c:1,e:'Procyclicality: Regulations and bank behavior that amplify economic cycles rather than stabilizing them. During boom: banks have high profits, low NPAs → lend aggressively → inflates bubble. During bust: losses, high NPAs → reduce lending → deepens recession. Basel III\'s countercyclical capital buffer (CCyB) aims to address this by building capital in good times to absorb losses in bad times.',x:['rbi_phase1','rbi_phase2']},
{id:'ba086',s:'banking_awareness',t:'rbi_functions',d:'medium',q:'RBI\'s "Operation Twist" involves:',o:['Twisting bank licenses','Simultaneously buying long-term G-secs and selling short-term T-bills to lower long-term yields','Adjusting CRR and SLR simultaneously','Changing both repo and reverse repo rates'],c:1,e:'Operation Twist: RBI simultaneously buys long-tenor government bonds (increasing prices, reducing yields) and sells short-term T-bills (increasing supply, raising short-term yields). Goal: Flatten or invert the yield curve — lower long-term yields to support long-term investment and credit. Named after similar US Fed operation in 1960s.',x:['rbi_phase1','rbi_phase2']},
{id:'ba087',s:'banking_awareness',t:'capital_markets',d:'medium',q:'A "Green Bond" specifically funds:',o:['Government bonds with green cover','Bonds whose proceeds are used exclusively for environment-friendly projects','Bonds with low interest rates','Bonds that can be traded in international markets only'],c:1,e:'Green bonds are debt instruments where proceeds are exclusively used for climate-positive projects: renewable energy, energy efficiency, clean transportation, sustainable water management, green buildings. India issued sovereign green bonds (₹16,000 crore in FY23). SEBI has green bond listing regulations.',x:['sbi_mains','rbi_phase1','rbi_phase2']},
{id:'ba088',s:'banking_awareness',t:'banking_terms',d:'hard',q:'"Debt-to-income ratio" (DTI) in lending means:',o:['Total bank debt divided by total income','Borrower\'s total monthly debt payments divided by gross monthly income','Company\'s total debt divided by EBITDA','Long-term debt as percent of equity'],c:1,e:'DTI ratio measures a borrower\'s debt obligations relative to income. Total monthly debt payments (EMIs, rent, other loans) / Gross monthly income. Generally, DTI below 40-43% is considered acceptable for home loans. RBI\'s guidelines use Debt Service Coverage Ratio (DSCR) for project finance — similar concept.',x:['sbi_mains','rbi_phase1']},
{id:'ba089',s:'banking_awareness',t:'banking_terms',d:'medium',q:'What is "Yield to Maturity" (YTM) of a bond?',o:['Interest rate printed on the bond','Total return if held to maturity, accounting for current price, interest payments, and face value repayment','Annual interest income only','Rate of return only if sold before maturity'],c:1,e:'YTM is the total expected return from a bond if held to maturity, expressed as an annual rate. It accounts for: current market price (if different from face value), coupon payments, time value of money. If current price < face value (discount bond), YTM > coupon rate. If current price > face value (premium bond), YTM < coupon rate.',x:['sbi_mains','rbi_phase1']},
{id:'ba090',s:'banking_awareness',t:'banking_terms',d:'hard',q:'In cross-border banking, "transfer pricing" issue refers to:',o:['Transferring money between countries','Mispricing of transactions between related parties in different tax jurisdictions to shift profits to low-tax locations','Price of wire transfers','Central bank transfer of reserves'],c:1,e:'Transfer pricing: When a multinational corporation sets prices for transactions between its subsidiaries in different countries to minimize overall tax. E.g., high royalty payments from high-tax India subsidiary to low-tax Mauritius subsidiary reduces taxable income in India. OECD BEPS (Base Erosion and Profit Shifting) framework and India\'s transfer pricing regulations address this.',x:['rbi_phase2']},
// More Economics
{id:'ec041',s:'economics',t:'monetary_policy',d:'hard',q:'The "Trilemma" in international economics states countries CANNOT simultaneously maintain:',o:['High growth, low unemployment, and price stability','Fixed exchange rate, capital mobility, and independent monetary policy','Low taxes, high spending, and fiscal balance','Trade surplus, current account balance, and capital account balance'],c:1,e:'Mundell-Fleming Trilemma (Impossible Trinity): Countries can choose only 2 of 3: (1) Fixed exchange rate, (2) Free capital mobility, (3) Autonomous monetary policy. India\'s choice: Managed float + Independent monetary policy + Managed (not free) capital flows.',x:['rbi_phase1','rbi_phase2']},
{id:'ec042',s:'economics',t:'gdp_growth',d:'medium',q:'Gross Value Added (GVA) at basic prices is related to GDP by:',o:['GVA = GDP + taxes - subsidies','GDP = GVA at basic prices + net product taxes','GDP = GVA + inflation','GVA = GDP / price level'],c:1,e:'GDP at market prices = GVA at basic prices + Product taxes - Product subsidies. GVA measures output before adding taxes and subtracting subsidies. This is why GDP is slightly higher than GVA in most economies (net taxes are positive).',x:['rbi_phase1','rbi_phase2']},
{id:'ec043',s:'economics',t:'fiscal_policy',d:'medium',q:'Revenue expenditure that creates productive assets is defined as:',o:['Capital expenditure','Effective Revenue Expenditure','Grants for capital creation','Development expenditure'],c:2,e:'Effective Revenue Expenditure = Revenue Expenditure + Grants-in-Aid for capital creation to states. This is deducted from Revenue Deficit to get "Effective Revenue Deficit" — the truly unproductive revenue spending. Example: Grants to states for hospitals and schools are technically revenue expenditure but create capital assets.',x:['rbi_phase1','rbi_phase2']},
{id:'ec044',s:'economics',t:'banking_sector',d:'hard',q:'The term "secular stagnation" (Larry Summers) describes:',o:['Slowdown during religious festivals','Prolonged period of slow growth, low inflation, and near-zero interest rates in developed economies','Stagnation limited to developing countries','Agricultural sector stagnation'],c:1,e:'Secular stagnation: Hypothesis that advanced economies face a prolonged period of slow growth, below-target inflation, and persistently low interest rates. Causes: demographic aging (lower investment demand), technological deflation, excess savings, inequality. Implications: Even zero interest rates may not stimulate growth sufficiently — needs fiscal policy or structural reform.',x:['rbi_phase2']},
{id:'ec045',s:'economics',t:'international_bodies',d:'medium',q:'The UN\'s Sustainable Development Goals (SDGs) include:',o:['Only environmental goals','17 interlinked goals covering economic, social, and environmental dimensions','5 goals focused on poverty','Only the goals relevant to developing countries'],c:1,e:'SDGs (2015-2030): 17 goals, 169 targets covering all dimensions of development — poverty, hunger, health, education, gender equality, clean water, energy, economic growth, industry, inequality, sustainable cities, consumption, climate, ocean, land, peace, and partnership. All 193 UN member countries have adopted them.',x:['sbi_mains','rbi_phase1']},
{id:'ec046',s:'economics',t:'monetary_policy',d:'hard',q:'Forward guidance in monetary policy means:',o:['Guidance about past monetary policy','Central bank communicating future monetary policy intentions to influence expectations today','Publishing guidelines for commercial banks','Currency forward contracts guidance'],c:1,e:'Forward guidance: Central banks communicate their future policy intentions (interest rate path) to help shape market expectations and thereby influence current economic conditions. Types: Calendar-based ("rates will stay low until 2026"), State-contingent ("rates will stay low until unemployment falls below 4%"). RBI\'s "accommodative stance" is a form of forward guidance.',x:['rbi_phase1','rbi_phase2']},
// More Quantitative
{id:'qa096',s:'quantitative_aptitude',t:'number_series',d:'easy',q:'1, 8, 27, 64, 125, ?',o:['196','216','225','256'],c:1,e:'Perfect cubes: 1³,2³,3³,4³,5³,6³. Next = 6³ = 216.',x:['sbi_prelims']},
{id:'qa097',s:'quantitative_aptitude',t:'number_series',d:'medium',q:'3, 5, 11, 29, 83, ?',o:['243','245','247','249'],c:1,e:'Pattern: 3×2-1=5, 5×2+1=11, 11×3-4=29, 29×3-4=83, 83×3-4=245.',x:['sbi_prelims','sbi_mains']},
{id:'qa098',s:'quantitative_aptitude',t:'percentage',d:'easy',q:'What percent of 150 is 120?',o:['75%','80%','85%','90%'],c:1,e:'120/150 × 100 = 80%.',x:['sbi_prelims']},
{id:'qa099',s:'quantitative_aptitude',t:'simple_interest',d:'easy',q:'SI on Rs.4000 at 5% for 4 years?',o:['Rs.700','Rs.750','Rs.800','Rs.850'],c:2,e:'SI = 4000×5×4/100 = Rs.800.',x:['sbi_prelims']},
{id:'qa100',s:'quantitative_aptitude',t:'compound_interest',d:'medium',q:'Amount on Rs.5000 at 8% CI for 2 years?',o:['Rs.5620','Rs.5730','Rs.5832','Rs.5920'],c:2,e:'A = 5000×(1.08)² = 5000×1.1664 = 5832.',x:['sbi_prelims']},
{id:'qa101',s:'quantitative_aptitude',t:'averages',d:'easy',q:'Average of 8 numbers is 45. If 60 is added, new average?',o:['44.4','46.7','47','48'],c:1,e:'Total = 8×45+60 = 420. New average = 420/9 = 46.67 ≈ 46.7.',x:['sbi_prelims']},
{id:'qa102',s:'quantitative_aptitude',t:'profit_loss',d:'easy',q:'CP = Rs.200, SP = Rs.170. Loss percent?',o:['12%','13%','15%','17%'],c:2,e:'Loss = 30. Loss% = 30/200 × 100 = 15%.',x:['sbi_prelims']},
{id:'qa103',s:'quantitative_aptitude',t:'ratio_proportion',d:'easy',q:'Divide Rs.1260 in ratio 3:4:5.',o:['Rs.270,360,450','Rs.280,380,490','Rs.315,420,525','Rs.300,400,500'],c:2,e:'Total parts=12. 1260/12=105. Parts: 3×105=315, 4×105=420, 5×105=525.',x:['sbi_prelims']},
{id:'qa104',s:'quantitative_aptitude',t:'time_work',d:'easy',q:'A does work in 8 days, B does in 12 days. Together?',o:['4.2 days','4.6 days','4.8 days','5 days'],c:2,e:'1/8+1/12=3/24+2/24=5/24. Time=24/5=4.8 days.',x:['sbi_prelims']},
{id:'qa105',s:'quantitative_aptitude',t:'time_distance',d:'easy',q:'Train 300m long at 90 km/h. Time to cross a 200m platform?',o:['16 sec','18 sec','20 sec','22 sec'],c:2,e:'Speed=90×5/18=25 m/s. Distance=300+200=500m. Time=500/25=20 sec.',x:['sbi_prelims']},
{id:'qa106',s:'quantitative_aptitude',t:'mensuration',d:'easy',q:'Volume of cube with side 5cm?',o:['75 cu cm','100 cu cm','125 cu cm','150 cu cm'],c:2,e:'Volume = 5³ = 125 cubic cm.',x:['sbi_prelims']},
{id:'qa107',s:'quantitative_aptitude',t:'number_system',d:'easy',q:'LCM of 4, 6, and 8 is:',o:['12','16','24','36'],c:2,e:'LCM(4,6)=12. LCM(12,8)=24.',x:['sbi_prelims']},
{id:'qa108',s:'quantitative_aptitude',t:'approximation',d:'easy',q:'Approximate: 19.97 × 10.03 ≈ ?',o:['195','200','205','210'],c:1,e:'≈ 20 × 10 = 200.',x:['sbi_prelims']},
{id:'qa109',s:'quantitative_aptitude',t:'quadratic_equations',d:'medium',q:'x²-9x+20=0 and y²-5y+6=0. Relation between x and y?',o:['x>y','x<y','x≥y','x≤y'],c:2,e:'x: (x-4)(x-5)=0, x=4,5. y: (y-2)(y-3)=0, y=2,3. Minimum x=4>max y=3. So x≥y (x is always ≥ y). Actually x>y always since min x=4>max y=3. So x>y.',x:['sbi_prelims','sbi_mains']},
{id:'qa110',s:'quantitative_aptitude',t:'permutation_combination',d:'medium',q:'In how many ways can word \'BANKS\' be arranged?',o:['60','90','120','150'],c:2,e:'BANKS has 5 distinct letters. 5! = 120 arrangements.',x:['sbi_prelims','sbi_mains']},
// Reasoning
{id:'ra046',s:'reasoning',t:'analogy',d:'easy',q:'Book : Library :: Money : ?',o:['Safe','Bank','Rupee','Paper'],c:1,e:'Books are stored in a Library. Money is stored/managed in a Bank.',x:['sbi_prelims']},
{id:'ra047',s:'reasoning',t:'analogy',d:'easy',q:'Pen : Paper :: Mouse : ?',o:['Cat','Computer','Keyboard','Screen'],c:1,e:'A pen writes on paper. A computer mouse is used with a computer.',x:['sbi_prelims']},
{id:'ra048',s:'reasoning',t:'analogy',d:'medium',q:'ACME : BDNF :: PQRS : ?',o:['QRST','RTSU','RSTU','RUST'],c:2,e:'A+1=B,C+1=D,M+1=N,E+1=F. Similarly P+1=Q,Q+1=R,R+1=S,S+1=T → QRST. Wait: A→B,C→D,M→N,E→F (each +1). P→Q,Q→R,R→S,S→T = QRST. Answer A.',x:['sbi_prelims','sbi_mains']},
{id:'ra049',s:'reasoning',t:'classification',d:'easy',q:'Odd one out: January, March, May, June, July',o:['January','March','June','July'],c:2,e:'January (31), March (31), May (31), July (31) all have 31 days. June has 30 days. June is odd.',x:['sbi_prelims']},
{id:'ra050',s:'reasoning',t:'ranking',d:'medium',q:'In a class of 50, Anil is 10th from bottom. What is his rank from top?',o:['39','40','41','42'],c:2,e:'From top = 50-10+1 = 41.',x:['sbi_prelims']},
{id:'ra051',s:'reasoning',t:'blood_relations',d:'easy',q:'John\'s mother\'s mother is Peter\'s grandmother. How is Peter related to John?',o:['Brother','Cousin','Uncle','Cannot determine'],c:1,e:'John\'s mother\'s mother = John\'s maternal grandmother = also Peter\'s grandmother. They share a grandmother → they are cousins.',x:['sbi_prelims']},
{id:'ra052',s:'reasoning',t:'syllogism',d:'easy',q:'All lions are animals. Some animals are dangerous. Conclusion: Some lions may be dangerous.',o:['Follows','Does not follow','Data inadequate','Both I and II'],c:0,e:'All lions → animals. Some animals → dangerous. This means some of the lions (who are animals) may fall in the "dangerous" category → possibility conclusion follows.',x:['sbi_prelims']},
{id:'ra053',s:'reasoning',t:'directions',d:'easy',q:'From a bus stop facing North, you board bus going East, get off after 10 minutes. Which direction do you walk to reach your home which is to the South of the bus stop?',o:['North','South','East','West'],c:3,e:'Bus went East from bus stop. You are now East of the bus stop. Home is South of bus stop. To reach home from your current position (East of bus stop), go West first to reach bus stop, then South. But if home is directly South of bus stop, from East side you go in a direction that has both West and South component = Southwest. However in exam terms: you need to go West to return to the bus stop area, so the primary direction is West.',x:['sbi_prelims']},
{id:'ra054',s:'reasoning',t:'inequalities',d:'easy',q:'A>B>C and C>D. Which is definitely true?',o:['A>D','D>B','B>D','A>C only'],c:0,e:'A>B>C>D → A>D is definitely true.',x:['sbi_prelims']},
{id:'ra055',s:'reasoning',t:'alphanumeric_series',d:'easy',q:'B2, D4, F6, H8, ?',o:['J10','I9','K11','J9'],c:0,e:'Letters: B,D,F,H,J (every other letter +2). Numbers: 2,4,6,8,10 (+2 each). Next: J10.',x:['sbi_prelims']},
// English
{id:'en046',s:'english',t:'vocabulary',d:'easy',q:'Synonym of ABUNDANT:',o:['Scarce','Plentiful','Valuable','Rare'],c:1,e:'Abundant = existing in large quantities. Synonym = Plentiful.',x:['sbi_prelims']},
{id:'en047',s:'english',t:'vocabulary',d:'easy',q:'Antonym of TRANSPARENT:',o:['Clear','See-through','Opaque','Honest'],c:2,e:'Transparent = easy to see through; honest. Antonym = Opaque (not transparent) or Dishonest.',x:['sbi_prelims']},
{id:'en048',s:'english',t:'fill_blanks',d:'easy',q:'The bank __ its doors to customers at 9 AM.',o:['opens','open','opened','opening'],c:0,e:'Present tense (habitual action). "The bank opens its doors" — third person singular present.',x:['sbi_prelims']},
{id:'en049',s:'english',t:'error_detection',d:'easy',q:'Find error: "She don\'t know how to operate the ATM machine."',o:['She','don\'t know','how to operate','the ATM machine'],c:1,e:'"She" is third person singular. "don\'t" → "doesn\'t." Correct: "She doesn\'t know..."',x:['sbi_prelims']},
{id:'en050',s:'english',t:'grammar',d:'easy',q:'Choose the correct sentence:',o:['There is few people in the bank today.','There are few people in the bank today.','There is a few people in the bank today.','There were few people in bank today.'],c:1,e:'"People" is plural → "There are few people." "There is" takes singular noun. "A few" is correct with countable plural nouns. "Few" (without "a") means very little, almost none.',x:['sbi_prelims']},
// GK
{id:'gk041',s:'general_knowledge',t:'economy',d:'easy',q:'In which year was India\'s first Five Year Plan launched?',o:['1947','1950','1951','1956'],c:2,e:'India\'s First Five Year Plan (1951-1956) was launched in 1951. It focused on agriculture, irrigation, and power sector development.',x:['sbi_prelims']},
{id:'gk042',s:'general_knowledge',t:'national_facts',d:'easy',q:'India\'s National Bird is:',o:['Sparrow','Crane','Peacock','Parrot'],c:2,e:'Indian Peacock (Pavo cristatus) is India\'s National Bird, adopted in 1963.',x:['sbi_prelims']},
{id:'gk043',s:'general_knowledge',t:'national_facts',d:'easy',q:'India\'s National Fruit is:',o:['Banana','Apple','Mango','Guava'],c:2,e:'Mango (Mangifera indica) is India\'s National Fruit.',x:['sbi_prelims']},
{id:'gk044',s:'general_knowledge',t:'awards',d:'easy',q:'Which award is considered India\'s highest gallantry award?',o:['Ashok Chakra','Vir Chakra','Param Vir Chakra','Kirti Chakra'],c:2,e:'Param Vir Chakra (PVC) is India\'s highest military decoration, awarded for the most conspicuous bravery or some daring or pre-eminent act of valour or self-sacrifice in the presence of the enemy.',x:['sbi_prelims']},
{id:'gk045',s:'general_knowledge',t:'important_days',d:'easy',q:'World Environment Day is observed on:',o:['April 22','May 5','June 5','July 11'],c:2,e:'World Environment Day is observed on June 5 every year, established by the United Nations.',x:['sbi_prelims']},
{id:'gk046',s:'general_knowledge',t:'national_facts',d:'easy',q:'India became independent from British rule on:',o:['August 15, 1947','January 26, 1950','November 26, 1949','October 2, 1947'],c:0,e:'India gained independence on August 15, 1947. Republic Day (January 26, 1950) marks when the Constitution came into force.',x:['sbi_prelims']},
{id:'gk047',s:'general_knowledge',t:'economy',d:'easy',q:'Which body prepares India\'s Union Budget?',o:['RBI','NITI Aayog','Ministry of Finance','Parliament'],c:2,e:'The Union Budget is prepared by the Ministry of Finance (specifically the Department of Economic Affairs and Department of Revenue) and presented by the Finance Minister in Parliament.',x:['sbi_prelims']},
{id:'gk048',s:'general_knowledge',t:'national_facts',d:'easy',q:'The currency of India is issued by:',o:['Ministry of Finance','SBI','RBI','Government of India'],c:2,e:'RBI issues all currency notes. Only one-rupee notes/coins are issued by the Ministry of Finance. But RBI manages and distributes all currency.',x:['sbi_prelims']},
{id:'gk049',s:'general_knowledge',t:'economy',d:'easy',q:'Indian Railways is under which Ministry?',o:['Ministry of Transport','Ministry of Railways','Ministry of Infrastructure','Ministry of Commerce'],c:1,e:'Indian Railways is under the Ministry of Railways, Government of India.',x:['sbi_prelims']},
{id:'gk050',s:'general_knowledge',t:'national_facts',d:'easy',q:'India\'s Constitution has how many schedules?',o:['8','10','12','14'],c:2,e:'India\'s Constitution originally had 8 schedules; currently has 12 schedules (additions through amendments).',x:['sbi_prelims']},
// Computer
{id:'comp041',s:'computer',t:'hardware_software',d:'easy',q:'Which key is used to permanently delete a file (bypassing Recycle Bin) in Windows?',o:['Delete','Shift+Delete','Ctrl+Delete','Alt+Delete'],c:1,e:'Shift+Delete permanently deletes a file in Windows, bypassing the Recycle Bin. Regular Delete moves file to Recycle Bin.',x:['sbi_prelims']},
{id:'comp042',s:'computer',t:'ms_office',d:'easy',q:'Ctrl+C is used for:',o:['Cut','Copy','Close','Create'],c:1,e:'Ctrl+C = Copy selected text/item to clipboard. Ctrl+X = Cut. Ctrl+V = Paste. Ctrl+Z = Undo.',x:['sbi_prelims']},
{id:'comp043',s:'computer',t:'internet_basics',d:'easy',q:'HTML stands for:',o:['High Text Markup Language','HyperText Markup Language','HyperText Module Language','High Transfer Module Language'],c:1,e:'HTML (HyperText Markup Language) is the standard markup language for creating web pages. It structures the content of a webpage.',x:['sbi_prelims']},
{id:'comp044',s:'computer',t:'internet_basics',d:'easy',q:'Email is a system for sending:',o:['Voice messages only','Digital messages over internet/network','Only images and videos','Physical letters via computer'],c:1,e:'Email (Electronic Mail) is a method of sending digital messages over the internet or computer networks. Can include text, attachments (documents, images, videos).',x:['sbi_prelims']},
{id:'comp045',s:'computer',t:'hardware_software',d:'easy',q:'Which of the following is an example of system software?',o:['MS Word','Chrome Browser','Windows Operating System','WhatsApp'],c:2,e:'System software manages computer hardware and provides platform for applications. Operating System (Windows, Linux, macOS) is the core system software. MS Word, Chrome, WhatsApp are application software.',x:['sbi_prelims']},
);

// Additional Flashcards
FC.push(
{id:'fc171',cat:'Quick Facts',front:'Current Affairs: G20 Presidency Sequence',back:'India 2023 (New Delhi Summit) → Brazil 2024 (Rio de Janeiro) → South Africa 2025 → USA 2026.\nIndia\'s G20 2023 theme: "Vasudhaiva Kutumbakam" — One Earth, One Family, One Future.\nKey outcomes: African Union joined G20 as permanent member.',difficulty:'medium',tags:['g20','current-affairs']},
{id:'fc172',cat:'Quick Facts',front:'India\'s Major Banking Scams',back:'PNB-Nirav Modi Scam (2018): ₹14,000+ crore — fraudulent LoUs via SWIFT.\nVijay Mallya-Kingfisher Airlines: ₹9,000 crore bank fraud.\nABG Shipyard: ₹22,842 crore — largest bank fraud in India.\nDHFL Scam: ₹34,000 crore — Dewan Housing Finance Corporation.\nAll led to reforms: Enhanced SWIFT monitoring, beneficial ownership disclosure.',difficulty:'medium',tags:['banking-scams','history']},
{id:'fc173',cat:'Quick Facts',front:'Banking Regulation Act Key Provisions',back:'Banking Regulation Act 1949:\n• Section 5: Defines banking company\n• Section 11: Minimum capital requirement\n• Section 17: Statutory reserves (20% of profit transferred to reserve fund)\n• Section 18: Cash reserve with RBI\n• Section 24: SLR maintenance\n• Section 35A: RBI power to issue directions to banks\n• Section 36AA: RBI power to remove directors/officers\n• Section 45: RBI power to apply for moratorium',difficulty:'hard',tags:['regulation','legal']},
{id:'fc174',cat:'Quick Facts',front:'Key Differences: Co-operative vs Commercial Banks',back:'Commercial Banks: Registered under Companies Act or Banking Cos Act. Profit motive. Regulated by RBI. Examples: SBI, HDFC, Axis.\nCo-operative Banks: Registered under State Co-operative Societies Act. Member-driven, limited profit. RBI regulates (since 2020 UCBs). Examples: Saraswat Bank, TJSB Sahakari Bank.\nKey: 2020 amendment brought Urban Co-operative Banks under RBI\'s regulation.',difficulty:'medium',tags:['banking-types','regulation']},
{id:'fc175',cat:'Quick Facts',front:'Priority Sector Weaker Sections (who qualifies?)',back:'Weaker sections target (10% of ANBC):\n• Small/marginal farmers (land ≤ 2 ha)\n• Artisans (credit up to ₹1L)\n• SC/ST/Women/Minorities/Persons with Disability\n• Self-Help Groups (SHGs)\n• Distressed persons (up to ₹1L)\n• Individual borrowers under various government schemes\nKey: 10% must go specifically to weaker sections within PSL target.',difficulty:'hard',tags:['psl','priority-sector']},
{id:'fc176',cat:'Exam Strategy',front:'SBI PO Mock Test Score Interpretation',back:'Prelims (100Q): 60-65+ = Very good. 55-60 = Good (need to check cutoffs). Below 50 = Work needed.\nPer section (35/35/30): Need ~60% per section minimum.\nNegative marking: -0.25 per wrong. Skip if not sure.\nKey: Accuracy > Attempts. Better to attempt 80 with 85% accuracy than 95 with 70% accuracy.',difficulty:'easy',tags:['exam-strategy','sbi']},
{id:'fc177',cat:'Exam Strategy',front:'Reading Comprehension Time Management',back:'SBI PO Mains RC: 2-3 passages, 5-7 Q each.\nTarget: 7-8 minutes per passage (skim 90 sec + Q reading 1 min + answering 5-6 min).\nPriority: vocabulary and direct fact questions first (less time).\nSkip inference questions if passage unclear — return after facts.\nRBI Grade B RC: 600-800 words on economics topics. Expect 2 passages at 5-7 questions each.',difficulty:'easy',tags:['exam-strategy','english']},
{id:'fc178',cat:'Current Affairs 2024',front:'Key Events 2024',back:'Jan: BRICS expanded to 9 members (Egypt, Ethiopia, Iran, Saudi Arabia, UAE joined)\nFeb: India\'s Interim Budget 2024-25 — fiscal deficit target 5.1%\nMar: SEBI introduced new Chairperson (Tuhin Kanta Pandey)\nApr: India\'s GDP Q4 FY24: 7.8% growth\nMay-Jun: 2024 Lok Sabha Elections — NDA returned to power\nJul: Union Budget 2024-25 — Fiscal deficit 4.9%\nAug: Paris Olympics — India: 1 silver + 5 bronze medals\nSep: RBI: No rate change; stance: Withdrawal of Accommodation\nOct: RBI stance changed to Neutral\nNov-Dec: Sanjay Malhotra became new RBI Governor',difficulty:'medium',tags:['current-affairs','2024']},
{id:'fc179',cat:'Current Affairs 2025',front:'Key Banking Events Early 2025',back:'Feb 2025: RBI MPC cut repo rate by 25 bps to 6.25% (first cut in 5 years) — Neutral stance\nMar 2025: India\'s Q3 FY25 GDP growth: 6.4%\nBanking: PSB profits at record; credit growth moderating to 12-13%\nUPI: Monthly transactions cross 16 billion (Jan 2025)\nCBDC: e₹ users cross 5 million\nINSAR: NISAR satellite (NASA-ISRO) scheduled for launch\nFintech: DPDP Act implementation rules expected 2025',difficulty:'medium',tags:['current-affairs','2025']},
{id:'fc180',cat:'Finance Formula',front:'Quick Reference — All Key Ratios',back:'Capital Ratios: CRAR = Capital/RWA; CET1/Tier1/Total\nLiquidity: LCR = HQLA/Net Outflows; NSFR = ASF/RSF\nProfitability: ROA = NP/Assets; ROE = NP/Equity; NIM = NII/EA\nCredit Quality: Gross NPA% = Gross NPA/Gross Advances; PCR = Provisions/Gross NPA\nBusiness: CASA = (CA+SA)/Total Deposits; CD Ratio = Advances/Deposits\nEfficiency: Cost-to-Income = Operating Costs/Operating Income (lower = better)',difficulty:'hard',tags:['ratios','banking-health']}
);

// Final Reference Data
const BANKING_SECTOR_DATA={
title:'India Banking Sector — Key Statistics 2024',
psbRanking:[
{rank:1,bank:'State Bank of India',totalAssets:'₹61+ lakh crore',branches:'22,000+',note:'Largest bank by all metrics'},
{rank:2,bank:'Punjab National Bank',totalAssets:'₹15+ lakh crore',branches:'10,000+',note:'After merger with OBC and United Bank'},
{rank:3,bank:'Bank of Baroda',totalAssets:'₹13+ lakh crore',branches:'9,500+',note:'After merger with Dena Bank and Vijaya Bank'},
{rank:4,bank:'Canara Bank',totalAssets:'₹12+ lakh crore',branches:'9,500+',note:'After merger with Syndicate Bank'},
{rank:5,bank:'Union Bank of India',totalAssets:'₹11+ lakh crore',branches:'8,500+',note:'After merger with Andhra Bank and Corporation Bank'},
{rank:6,bank:'Bank of India',totalAssets:'₹8+ lakh crore',branches:'5,100+',note:'Standalone PSB'},
{rank:7,bank:'Central Bank of India',totalAssets:'₹5.5+ lakh crore',branches:'4,700+',note:'Standalone PSB'},
{rank:8,bank:'Indian Bank',totalAssets:'₹7+ lakh crore',branches:'6,000+',note:'After merger with Allahabad Bank'},
{rank:9,bank:'UCO Bank',totalAssets:'₹3.5+ lakh crore',branches:'3,000+',note:''},
{rank:10,bank:'Indian Overseas Bank',totalAssets:'₹3.5+ lakh crore',branches:'3,200+',note:''},
{rank:11,bank:'Bank of Maharashtra',totalAssets:'₹3+ lakh crore',branches:'2,600+',note:''},
{rank:12,bank:'Punjab & Sind Bank',totalAssets:'₹2+ lakh crore',branches:'1,600+',note:'Smallest PSB post-merger'}
],
privateRanking:[
{rank:1,bank:'HDFC Bank',totalAssets:'₹36+ lakh crore',branches:'8,200+',note:'Largest private bank; merged with HDFC Ltd 2023'},
{rank:2,bank:'ICICI Bank',totalAssets:'₹22+ lakh crore',branches:'6,600+',note:'Second largest private bank'},
{rank:3,bank:'Axis Bank',totalAssets:'₹14+ lakh crore',branches:'5,000+',note:'Third largest private bank'},
{rank:4,bank:'Kotak Mahindra Bank',totalAssets:'₹8+ lakh crore',branches:'2,700+',note:'Founded by Uday Kotak'},
{rank:5,bank:'IndusInd Bank',totalAssets:'₹5+ lakh crore',branches:'2,700+',note:''},
{rank:6,bank:'Yes Bank',totalAssets:'₹4+ lakh crore',branches:'1,200+',note:'Rescued by SBI-led consortium in 2020'},
{rank:7,bank:'Federal Bank',totalAssets:'₹3+ lakh crore',branches:'1,600+',note:'Headquartered in Kerala'},
{rank:8,bank:'IDFC First Bank',totalAssets:'₹2.5+ lakh crore',branches:'950+',note:'Formed by IDFC Bank-Capital First merger'}
]};
