// ═══ COMPREHENSIVE GK & CURRENT AFFAIRS DATA BANK ═══

const GK_ONELINERS={
title:'500+ One-Liner Facts for Bank Exams',
banking_finance:[
'RBI was established on April 1, 1935, under the Reserve Bank of India Act, 1934.',
'RBI was nationalized on January 1, 1949.',
'RBI headquarters: Mumbai. First headquarters: Calcutta (1935-1937).',
'First Governor of RBI: Sir Osborne Smith (British). First Indian Governor: C.D. Deshmukh (1943).',
'Current (26th) RBI Governor: Sanjay Malhotra (appointed December 2024).',
'Repo Rate (Feb 2025): 6.25% — first rate cut in 5 years.',
'Reverse Repo Rate: 3.35% (SDF rate = 6.00% is more relevant now).',
'Cash Reserve Ratio (CRR): 4.00%.',
'Statutory Liquidity Ratio (SLR): 18.00%.',
'RBI\'s inflation target: 4% CPI (±2%), i.e., 2%-6% band.',
'Monetary Policy Committee (MPC): 6 members — 3 from RBI + 3 external, meets 6 times/year.',
'Current MPC chairperson: RBI Governor (Sanjay Malhotra).',
'DICGC insures deposits up to ₹5 lakh per depositor per bank (raised from ₹1L in 2020).',
'DICGC was established in 1961; it is a subsidiary of RBI.',
'SBI was established on July 1, 1955, by taking over Imperial Bank of India.',
'Imperial Bank of India was formed in 1921 by merging 3 presidency banks (Bengal, Bombay, Madras).',
'SBI associates merged with SBI: 5 associate banks + Bharatiya Mahila Bank (April 1, 2017).',
'Current SBI Chairman: Challa Sreenivasulu Setty (appointed August 2024).',
'PMJDY launched on August 28, 2014, with zero-balance savings account.',
'PMJDY accounts: 530+ crore (as of 2024); 53% held by women.',
'PMJDY provides: RuPay debit card, ₹2 lakh accident insurance, ₹30,000 life insurance, ₹10,000 overdraft.',
'MUDRA YOJANA (PMMY) launched in April 2015; Loans: Shishu (up to ₹50K), Kishore (₹50K-5L), Tarun (₹5L-10L).',
'Pradhan Mantri Suraksha Bima Yojana (PMSBY): ₹2 lakh accident cover, ₹20/year premium.',
'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY): ₹2 lakh life cover (any cause), ₹436/year.',
'Atal Pension Yojana (APY): Guaranteed pension ₹1,000-₹5,000/month; for unorganized sector, age 18-40.',
'Stand Up India: Loan ₹10L-₹1Cr to SC/ST and women entrepreneurs for greenfield enterprises.',
'UPI (Unified Payments Interface) launched in April 2016 by NPCI.',
'NPCI: National Payments Corporation of India — not-for-profit, promoted by RBI and IBA.',
'India\'s UPI transactions: 130+ billion in FY2024 (₹200+ lakh crore value).',
'RTGS: Real Time Gross Settlement — minimum ₹2 lakh; 24×7 since December 2020.',
'NEFT: National Electronic Fund Transfer — no minimum; 24×7; 48 half-hourly batches.',
'IMPS: Immediate Payment Service — up to ₹5 lakh; 24×7×365.',
'e₹ (Digital Rupee/CBDC): e₹-W (Wholesale, Nov 2022); e₹-R (Retail, Dec 2022).',
'SWIFT: Society for Worldwide Interbank Financial Telecommunication — international bank messaging.',
'SFMS: Structured Financial Messaging System — India\'s domestic equivalent of SWIFT.',
'CIBIL score range: 300-900; Score 750+ considered good for loans.',
'CIBIL TransUnion was India\'s first Credit Information Company, established 2000.',
'CICs (Credit Information Companies) regulated under CIC Regulation Act 2005.',
'Four CICs in India: CIBIL, Equifax, Experian, CRIF High Mark.',
'Priority Sector Lending (PSL) target: 40% of ANBC for domestic banks.',
'Agriculture PSL sub-target: 18% of ANBC (8% to small/marginal farmers).',
'Weaker sections PSL sub-target: 10% of ANBC.',
'PSL certificate (PSLC) trading platform: Banks can buy/sell PSL compliance certificates.',
'Basel III: Minimum CRAR 8% globally; India mandates 9%.',
'Basel III introduced: Capital Conservation Buffer (2.5%), Leverage Ratio (3%), LCR, NSFR.',
'CRAR average for Indian banks (2024): ~14.8% (well above 9% minimum).',
'D-SIBs (Domestic Systemically Important Banks): SBI (bucket 3), HDFC Bank (bucket 1), ICICI Bank (bucket 1).',
'IBC (Insolvency and Bankruptcy Code) enacted in 2016; Resolution timeline: 180 days (extendable to 270).',
'SARFAESI Act 2002: Banks can seize secured assets without court order for NPAs.',
'Gross NPA peaked at 11.5% (March 2018); reduced to ~3.2% (March 2024).',
'Net NPA: ~0.8% (March 2024) — significant improvement.',
'NPA definition: Loan unpaid for 90+ days.',
'NCLT (National Company Law Tribunal): Handles IBC insolvency cases.',
'Payments Banks: Can accept deposits up to ₹2 lakh (raised from ₹1L in Oct 2023); cannot lend.',
'First Payments Banks: Airtel Payments Bank, Paytm Payments Bank, India Post Payments Bank.',
'RBI cancelled Paytm Payments Bank\'s license for new transactions in early 2024.',
'Small Finance Banks: Full banking including lending; focused on unserved/underserved segments.',
'NABARD: National Bank for Agriculture and Rural Development — apex institution for rural credit.',
'NABARD established: July 12, 1982; HQ: Mumbai.',
'SIDBI: Small Industries Development Bank of India — apex for MSME finance; HQ: Lucknow.',
'NHB: National Housing Bank — regulates housing finance companies; subsidiary of RBI.',
'EXIM Bank: Export Import Bank of India — provides trade finance; government-owned.',
'SEBI established: 1988 (non-statutory); SEBI Act 1992 (statutory).',
'SEBI regulates: Stock exchanges (BSE, NSE), mutual funds, FPIs, brokers, depositories.',
'BSE (Bombay Stock Exchange): World\'s largest by number of listed companies; Sensex tracks 30 stocks.',
'NSE: Second largest by market cap; Nifty 50 index tracks 50 stocks.',
'NSE launched Nifty 50 in 1996.',
'NSDL: National Securities Depository Limited — first depository in India (1996).',
'CDSL: Central Depository Services Limited — second depository (1999).',
'IRDAI: Insurance Regulatory and Development Authority of India; HQ: Hyderabad.',
'India\'s insurance penetration: ~4% of GDP (life 3.2%, non-life 1%).',
'PFRDA: Pension Fund Regulatory and Development Authority — regulates NPS and APY.',
'NPS (National Pension System): Market-linked pension; mandatory for central govt employees from 2004.',
'IFSCA: International Financial Services Centres Authority — regulates GIFT City.',
'GIFT City (Gujarat International Finance Tec-City): India\'s first International Financial Services Centre.',
'FDI in India: Not counted by vote percentage but by equity stake (FDI = 10%+ stake with management control).',
'FPI limit in Indian private banks: 74%.',
'FPI limit in PSBs: 20%.',
'External Commercial Borrowings (ECB): Indian companies borrowing from foreign lenders; regulated by RBI.',
'Repo transactions (LAF): RBI lends overnight to banks (repo) or absorbs (reverse repo/SDF).',
'Open Market Operations (OMO): RBI buys/sells G-secs to manage systemic liquidity.',
'Market Stabilization Scheme (MSS): RBI issues T-bills/bonds to sterilize excess forex inflows.',
'Call money rate: Short-term (overnight) interbank lending rate; typically around repo rate.',
'T-Bills: Short-term government securities (91-day, 182-day, 364-day); issued at discount, redeemed at par.',
'G-secs: Long-term (2-40 years) government bonds; used for SLR compliance.',
'Current account: Zero minimum balance; withdrawal by cheque; no interest (or nominal).',
'Savings account: Minimum balance requirement; withdrawal limited; interest 3-4% p.a.',
'Fixed Deposit: Fixed period, predetermined rate; premature withdrawal penalty applies.',
'Recurring Deposit: Fixed monthly deposit, fixed period, typically 6 months to 10 years.',
'KYC: Know Your Customer — mandatory for all bank accounts; includes Aadhaar, PAN, address proof.',
'AML: Anti-Money Laundering — three stages: Placement, Layering, Integration.',
'PMLA (Prevention of Money Laundering Act) 2002: Key AML legislation.',
'FIU-IND: Financial Intelligence Unit — India; receives and analyzes STRs from banks; under Ministry of Finance.',
'STR: Suspicious Transaction Report — filed by banks for suspicious transactions regardless of amount.',
'CTR: Cash Transaction Report — filed for cash transactions ≥₹10 lakh.',
'Wire Transfer Report: Filed for domestic/international wire transfers ≥₹50,000 (without full KYC).',
'Bank holidays: RBI Act mandates banks close on: Republic Day, Independence Day, Gandhi Jayanti, and state-specified holidays.',
'Wilful defaulter: Has capacity to repay but doesn\'t; or has diverted/siphoned funds.',
'Fugitive Economic Offender Act 2018: Allows confiscation of assets of economic offenders who flee India.',
'Vijay Mallya (Kingfisher Airlines) and Nirav Modi (PNB scam) are high-profile fugitive economic offenders.',
'PNB Scam (2018): Fraudulent Letters of Undertaking (LoUs) worth $2 billion+; exposed by Punjab National Bank.',
'SWIFT messaging: Used for international fund transfers; must be authenticated by bank officials.',
'Nostro account: Our account maintained abroad in foreign currency.',
'Vostro account: Foreign bank\'s account maintained with us in Indian rupees.',
'FEMA 1999: Foreign Exchange Management Act — replaced FERA 1973; civil in nature.',
'Section 80C: Income tax deduction up to ₹1.5 lakh for specified investments (PPF, ELSS, NSC, etc.).',
'PPF: Public Provident Fund — 15-year tenure; tax-free interest (currently 7.1%); ₹500-₹1.5L per year.',
'NSC: National Savings Certificate — 5-year tenure; sold at post offices; taxable interest.',
'Sukanya Samriddhi Account: For girl child (below 10 years); 21-year maturity; high interest rate (~8.2%).',
'Senior Citizens Savings Scheme (SCSS): 5 years; 8.2% interest; for 60+ years.',
'India Post Payments Bank (IPPB): Launched 2018; uses postal network for banking.',
],
economy:[
'India\'s GDP (FY2023-24): $3.73 trillion — 5th largest economy globally.',
'India\'s GDP growth rate FY24: 8.2% (fastest among major economies).',
'India\'s GDP growth target FY25: 6.4-6.8%.',
'India will surpass Japan and Germany to become 3rd largest economy by ~2030 (IMF projections).',
'India\'s per capita GDP (FY24): ~$2,800 (nominal); ~$9,200 (PPP).',
'India\'s Savings Rate: ~29-30% of GDP (down from 37% peak in 2007-08).',
'India\'s Investment Rate (GFCF): ~31-32% of GDP.',
'India\'s services sector: ~55% of GDP — IT/ITES, finance, telecom, transport.',
'Manufacturing sector: ~17% of GDP — target is 25% under Make in India.',
'Agriculture sector: ~18% of GDP — employs ~47% of workforce.',
'India\'s CPI inflation (FY24 average): ~5.4%.',
'India\'s WPI (Wholesale Price Index) base year: 2011-12.',
'India\'s CPI base year: 2012.',
'Core inflation excludes: Food and fuel prices.',
'India\'s fiscal deficit (FY25 budget): 4.9% of GDP.',
'India\'s revenue deficit (FY25): 2.0% of GDP.',
'India\'s government debt: ~83% of GDP (Centre + States combined).',
'India\'s central government debt: ~56% of GDP.',
'FRBM Act 2003: Targets fiscal deficit at 3% of GDP (deadline repeatedly revised).',
'Escape clause under FRBM: Allows deviation due to national calamity, war, or economic crisis.',
'India\'s GST: Implemented July 1, 2017 (One Nation One Tax).',
'GST slabs: 0%, 5%, 12%, 18%, 28% (plus cess on luxury/demerit goods).',
'GST collections FY24: ₹20.18 lakh crore (first time crossing ₹20 lakh crore).',
'GST Council: Chaired by Union Finance Minister; all state FMs are members.',
'India\'s gross tax revenue FY24: ₹34+ lakh crore.',
'Direct tax-to-GDP ratio in India: ~6.5%.',
'India\'s National Infrastructure Pipeline (NIP): ₹111 lakh crore investment (2019-25).',
'PM Gati Shakti: Multi-modal connectivity master plan integrating 16 ministries.',
'India\'s power generation capacity (2024): 440+ GW (Renewable: 190+ GW).',
'India\'s renewable energy target: 500 GW by 2030.',
'India\'s solar capacity: 85+ GW (3rd largest solar capacity globally in 2024).',
'India\'s oil production: ~0.8 mbpd; imports ~85% of crude oil needs.',
'OPEC+: Group of oil-producing nations; India is a major oil consumer (world\'s 3rd largest).',
'India\'s coal reserves: 4th largest globally; produces ~900 MT annually.',
'Green Hydrogen Mission: India aims to produce 5 MT of green hydrogen by 2030.',
'India\'s forex reserves (2024): $640+ billion — 4th largest globally.',
'India\'s current account deficit (FY24): ~0.9% of GDP.',
'India\'s merchandise trade deficit: ~$240 billion (FY24).',
'India\'s services trade surplus: ~$160 billion (FY24).',
'India\'s remittances (FY24): $120 billion+ — world\'s largest recipient.',
'India\'s FDI inflows (FY24): $44.4 billion.',
'India\'s largest FDI source: Mauritius (due to treaty shopping), then Singapore, USA.',
'India\'s top export destination: USA (~17% of exports).',
'India\'s top import source: China (~15% of imports).',
'India\'s PLI (Production Linked Incentive) for 14 sectors: Total outlay ₹1.97 lakh crore.',
'India\'s credit-to-GDP ratio: ~55% — significantly below China (~165%) and USA (~80%).',
'India\'s HDI rank: 132 (out of 193) — Medium Human Development (score 0.644).',
'India\'s adult literacy rate: ~77.7%.',
'India\'s primary school enrollment rate: ~95%+ (near-universal).',
'India\'s population (2024): ~1.44 billion — most populous country (surpassed China in 2023).',
'India\'s working-age population (15-64): ~68% — peak demographic dividend period.',
'India\'s urbanization rate: ~37% (to reach 50%+ by 2040).',
'India\'s life expectancy: 67.7 years (2023).',
'India\'s IMR: 27 per 1,000 live births (2020).',
'India\'s MMR: 97 per 100,000 live births (2018-20).',
'India\'s out-of-pocket health expenditure: ~48% of total health expenditure.',
'Ayushman Bharat PM-JAY: ₹5 lakh health insurance for bottom 40% (~55 crore beneficiaries).',
'India\'s public health expenditure: ~2.1% of GDP.',
'MGNREGS (Mahatma Gandhi National Rural Employment Guarantee Scheme): 100 days guaranteed employment to rural adults; enacted 2005, effective 2006.',
'PM Awas Yojana-Urban: Housing for all urban poor; target 1.18 crore houses.',
'PM Awas Yojana-Gramin: Target 2.95 crore rural houses under Pradhan Mantri Grameen Awaas Yojana.',
'AMRUT: Atal Mission for Rejuvenation and Urban Transformation — urban infrastructure in 500 cities.',
'Smart Cities Mission: 100 cities selected for comprehensive development.',
'Swachh Bharat Mission (SBM): Launched October 2, 2014; aimed to eliminate open defecation; Phase 2 focuses on solid waste management.',
'PM Kisan Samman Nidhi (PM-KISAN): ₹6,000/year to small/marginal farmers with ≤2 hectare land.',
'Total PM-KISAN beneficiaries: 110+ million farmers.',
'e-NAM (National Agriculture Market): 1,361+ APMCs digitally linked (2024); facilitates pan-India trading.',
'MSP (Minimum Support Price): Announced for 23 crops; CACP recommends based on A2+FL+50% formula.',
'India\'s irrigation coverage: ~45% of gross cropped area.',
'India is world\'s largest milk producer: 230+ million metric tonnes (2024).',
'India is world\'s largest producer of pulses, banana, mango, spices.',
'India is world\'s 2nd largest producer of rice, wheat, sugarcane, cotton.',
'National Mission for Sustainable Agriculture (NMSA): Focuses on soil health, water conservation.',
'Soil Health Card scheme: More than 22 crore soil health cards issued.',
'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY): "Har khet ko pani, More crop per drop."',
'Pradhan Mantri Fasal Bima Yojana (PMFBY): Crop insurance; premium 2% for kharif, 1.5% for rabi.',
'Doubling Farmers\' Income target (original 2022): Target missed; new target aligned with 2025.',
'National Food Security Act 2013: Subsidized food grain to 75% rural and 50% urban population.',
],
international:[
'G7: USA, UK, France, Germany, Italy, Canada, Japan.',
'G20: G7 + Argentina, Australia, Brazil, China, India, Indonesia, Mexico, Russia, Saudi Arabia, South Africa, South Korea, Turkey, EU. India hosted G20 in 2023.',
'G20 2023 theme (India): Vasudhaiva Kutumbakam — One Earth, One Family, One Future.',
'G20 2024 host: Brazil (Rio de Janeiro).',
'G20 2025 host: South Africa.',
'BRICS: Brazil, Russia, India, China, South Africa (original 5). Expanded January 2024: Added Egypt, Ethiopia, Iran, Saudi Arabia, UAE.',
'BRICS NDB (New Development Bank): HQ Shanghai; President Dilma Rousseff.',
'IMF (International Monetary Fund): 190 member countries; HQ Washington D.C.; provides financial assistance and policy advice.',
'IMF Special Drawing Rights (SDR): International reserve asset; basket of USD, EUR, CNY, JPY, GBP.',
'World Bank: IBRD + IDA + IFC + MIGA + ICSID; HQ Washington D.C.',
'IBRD: International Bank for Reconstruction and Development — lends to middle-income countries.',
'IDA: International Development Association — concessional lending to poorest countries.',
'India\'s voting share at World Bank: ~3%.',
'ADB (Asian Development Bank): 68 members; HQ Manila; India is 2nd largest shareholder.',
'WTO: World Trade Organization; 164 members; HQ Geneva; DG Ngozi Okonjo-Iweala.',
'UNCTAD: UN Conference on Trade and Development; advocates for developing countries in trade.',
'AIIB (Asian Infrastructure Investment Bank): China-led multilateral; 105+ members; HQ Beijing.',
'NDB (New Development Bank) or BRICS Bank: HQ Shanghai; funded by BRICS nations.',
'SCO (Shanghai Cooperation Organisation): India joined in 2017; 9 members; HQ Beijing.',
'SAARC: South Asian Association for Regional Cooperation; 8 members; HQ Kathmandu (inactive since 2016).',
'ASEAN: 10 SE Asian nations; HQ Jakarta; India is Dialogue Partner.',
'QUAD: Quadrilateral Security Dialogue — USA, India, Japan, Australia.',
'Paris Agreement (2015): Limit global warming to 1.5°C above pre-industrial levels; India\'s NDC targets 50% non-fossil energy by 2030.',
'India\'s Net Zero target: 2070 (later than USA/EU\'s 2050).',
'COP28 (2023): Dubai, UAE — first global stocktake of Paris Agreement implementation.',
'COP29 (2024): Baku, Azerbaijan.',
'Kyoto Protocol (1997): First binding international treaty on GHG emissions; USA never ratified.',
'UNFCCC: UN Framework Convention on Climate Change; established 1992.',
'India\'s NDC (2022 updated): 45% reduction in GDP emission intensity (from 2005), 50% non-fossil electricity by 2030, create carbon sink of 2.5-3 billion tonnes through forests.',
'India\'s green hydrogen mission: 5 MT production by 2030; ₹19,744 crore outlay.',
'UK-India FTA negotiations: Ongoing as of 2024.',
'India-UAE CEPA (Comprehensive Economic Partnership Agreement): Signed 2022; reduced tariffs.',
'India-Australia ECTA (Economic Cooperation and Trade Agreement): Interim since 2022.',
'OECD: Organisation for Economic Co-operation and Development; 38 members; HQ Paris; India not a member but dialogue partner.',
'FATF (Financial Action Task Force): Anti-money laundering watchdog; 39 members; HQ Paris.',
'India\'s FATF status: Regular member (not on grey/blacklist).',
'BIS (Bank for International Settlements): Central bank of central banks; HQ Basel, Switzerland.',
'Basel Committee on Banking Supervision (BCBS): Sets global banking standards; operates under BIS.',
'FSB (Financial Stability Board): G20 body for global financial regulation; HQ Basel.',
'SWIFT: Facilitates 5 billion+ financial messages/year among 11,000+ member institutions.',
],
important_dates:[
'January 1: Global Family Day',
'January 26: Republic Day (India); International Customs Day',
'February 2: World Wetlands Day',
'February 4: World Cancer Day',
'February 11: International Day of Women and Girls in Science',
'February 20: World Day of Social Justice',
'February 21: International Mother Language Day',
'March 4: World Obesity Day',
'March 8: International Women\'s Day',
'March 14: Pi Day; International Day of Action for Rivers',
'March 15: World Consumer Rights Day',
'March 20: International Day of Happiness; World Sparrow Day',
'March 21: World Forestry Day; World Down Syndrome Day; International Day for the Elimination of Racial Discrimination',
'March 22: World Water Day',
'March 23: World Meteorological Day',
'March 24: World Tuberculosis Day',
'April 2: World Autism Awareness Day',
'April 5: National Maritime Day (India)',
'April 7: World Health Day',
'April 11: National Safe Motherhood Day',
'April 18: World Heritage Day',
'April 22: Earth Day',
'April 23: World Book and Copyright Day',
'May 1: International Labour Day (Workers\' Day)',
'May 3: World Press Freedom Day',
'May 4: International Firefighters\' Day',
'May 8: World Red Cross Day',
'May 11: National Technology Day (India)',
'May 15: International Day of Families',
'May 17: World Telecommunication Day (World Information Society Day)',
'May 21: National Anti-Terrorism Day (India); World Tea Day',
'May 22: International Day for Biological Diversity',
'May 25: World Thyroid Day',
'May 31: World No Tobacco Day',
'June 1: Global Day of Parents; World Milk Day',
'June 5: World Environment Day',
'June 7: World Food Safety Day',
'June 8: World Oceans Day',
'June 12: World Day Against Child Labour',
'June 14: World Blood Donor Day',
'June 15: World Elder Abuse Awareness Day',
'June 17: World Day to Combat Desertification',
'June 19: World Sickle Cell Day',
'June 20: World Refugee Day',
'June 21: International Day of Yoga',
'June 23: International Olympic Day; United Nations Public Service Day',
'June 26: International Day Against Drug Abuse',
'July 1: National Doctors\' Day (India); World Doctors\' Day',
'July 4: Independence Day (USA)',
'July 11: World Population Day',
'July 17: World Day for International Justice',
'July 18: Nelson Mandela International Day',
'July 26: Kargil Vijay Diwas (India); UN System-wide Action Plan on the Decade for Action on Nutrition',
'July 28: World Hepatitis Day',
'July 29: International Tiger Day',
'August 1: World Breastfeeding Week (first week of August)',
'August 6: Hiroshima Day',
'August 9: International Day of the World\'s Indigenous Peoples; Nagasaki Day',
'August 12: International Youth Day',
'August 15: Independence Day (India)',
'September 5: International Day of Charity; Teachers\' Day (India)',
'September 8: International Literacy Day',
'September 10: World Suicide Prevention Day',
'September 11: National Forest Martyrs Day (India)',
'September 14: Hindi Diwas (India)',
'September 15: International Day of Democracy; Engineers\' Day (India)',
'September 16: World Ozone Day',
'September 21: International Day of Peace (World Peace Day)',
'September 22: World Rhino Day',
'September 26: International Day for the Total Elimination of Nuclear Weapons',
'September 27: World Tourism Day',
'September 28: World Rabies Day',
'September 29: World Heart Day',
'October 1: International Day of Older Persons; World Vegetarian Day',
'October 2: Gandhi Jayanti (India); International Day of Non-Violence; World Animal Welfare Day',
'October 4: World Animal Day; World Habitat Day (1st Monday of October)',
'October 5: World Teachers\' Day',
'October 8: Indian Air Force Day',
'October 9: World Post Day',
'October 10: World Mental Health Day',
'October 11: International Day of the Girl Child',
'October 14: World Standards Day',
'October 15: International Day of Rural Women; World Students\' Day (India - APJ Abdul Kalam birthday)',
'October 16: World Food Day',
'October 17: International Day for the Eradication of Poverty',
'October 24: United Nations Day',
'October 31: Rashtriya Ekta Diwas (National Unity Day, India - Sardar Patel Birthday)',
'November 1: World Vegan Day',
'November 5: World Tsunami Awareness Day',
'November 9: Legal Services Day (India)',
'November 10: World Science Day for Peace and Development',
'November 11: National Education Day (India)',
'November 14: Children\'s Day (India); World Diabetes Day',
'November 16: International Day for Tolerance',
'November 17: International Students\' Day',
'November 19: International Men\'s Day; World Toilet Day',
'November 20: Universal Children\'s Day',
'November 21: World Fisheries Day',
'November 25: International Day for the Elimination of Violence Against Women',
'November 26: Constitution Day (Samvidhan Divas, India)',
'December 1: World AIDS Day',
'December 2: International Day for the Abolition of Slavery; National Pollution Control Day (India)',
'December 3: International Day of Persons with Disabilities',
'December 4: Indian Navy Day',
'December 7: International Civil Aviation Day',
'December 9: International Anti-Corruption Day',
'December 10: Human Rights Day',
'December 11: International Mountain Day',
'December 14: National Energy Conservation Day (India)',
'December 16: Vijay Diwas (India)',
'December 18: International Migrants\' Day',
'December 20: International Human Solidarity Day',
'December 22: National Mathematics Day (India - Ramanujan Birthday)',
'December 23: Kisan Diwas (National Farmers\' Day, India)',
],
important_awards:[
'Bharat Ratna: Highest civilian award; not given annually. 2024 recipients: LK Advani, MS Swaminathan (posthumous), PV Narasimha Rao (posthumous), Charan Singh (posthumous), Karpoori Thakur (posthumous).',
'Padma Vibhushan: Second highest civilian award.',
'Padma Bhushan: Third highest civilian award.',
'Padma Shri: Fourth highest civilian award.',
'Rajiv Gandhi Khel Ratna (now Major Dhyan Chand Khel Ratna): Highest sports award; renamed 2021.',
'Arjuna Award: For outstanding sports performance over 4 consecutive years.',
'Dronacharya Award: For sports coaches.',
'Param Vir Chakra: Highest wartime gallantry award.',
'Ashok Chakra: Highest peacetime gallantry award.',
'Saraswati Samman: Highest literary award for Indian literature (by K.K. Birla Foundation).',
'Jnanpith Award: Highest literary award given by Bharatiya Jnanpith for Indian language literature.',
'Dada Saheb Phalke Award: Highest award in Indian cinema (given by Government of India).',
'Nobel Prize: Awarded by Nobel Committee (Sweden/Norway); Nobel Economics: Swedish Riksbank Prize.',
'Nobel Peace Prize 2023: Narges Mohammadi (Iran).',
'Nobel Economics 2024: Daron Acemoglu, Simon Johnson, James Robinson (for study on institutions and prosperity).',
'Nobel Literature 2024: Han Kang (South Korea).',
'Grammy Award: Music; Academy Award (Oscar): Film; Emmy Award: Television.',
'Pulitzer Prize: Excellence in journalism and arts (USA).',
'Man Booker Prize (now Booker Prize): English language fiction.',
'Ramon Magsaysay Award: "Nobel of Asia"; given to Asians for public service.',
'Ballon d\'Or: Best football player.',
'FIFA World Cup 2022: Argentina (winner); 2026 USA, Canada, Mexico.',
'ICC Cricket World Cup 2023: Australia (winner). India hosted; India lost to Australia in final.',
'Paris Olympics 2024: India won 6 medals (1 silver + 5 bronze). Neeraj Chopra: silver medal (javelin).',
'Commonwealth Games 2022: Birmingham; India ranked 4th (22 gold, 16 silver, 23 bronze).',
],
science_technology:[
'ISRO: Indian Space Research Organisation; HQ Bengaluru; Chairman Sreedhara Panicker Somanath.',
'Chandrayaan-3: India\'s 3rd lunar mission; landed on Moon\'s south pole on August 23, 2023 — first country to soft-land near lunar south pole.',
'Chandrayaan-3 lander: Vikram; rover: Pragyan.',
'Aditya-L1: India\'s first solar mission; launched September 2, 2023; arrived at L1 Lagrange point Jan 2024.',
'Gaganyaan: India\'s human spaceflight mission; planned for 2025 (manned). Unmanned test flights ongoing.',
'GSAT-20: India\'s heaviest satellite; launched by SpaceX Falcon-9 (November 2024).',
'SpaDeX (Space Docking Experiment): Launched Dec 30, 2024; India 4th country to achieve in-space docking.',
'PSLV: Polar Satellite Launch Vehicle — India\'s workhorse rocket; 60+ successful launches.',
'GSLV Mk III (LVM3): India\'s heaviest rocket; can carry 10 tonnes to LEO.',
'OneWeb satellites: India\'s LVM3 launched 36 OneWeb satellites in multiple missions (UK company).',
'AstroSat: India\'s first dedicated astronomy satellite (2015).',
'Mangalyaan (Mars Orbiter Mission): India\'s Mars mission; 2013 launch; first Asian country to reach Mars orbit.',
'NISAR: NASA-ISRO Synthetic Aperture Radar joint mission; planned 2024 launch.',
'5G in India: Launched October 2022; Jio and Airtel first to roll out.',
'India\'s semiconductor mission: ₹76,000 crore outlay for domestic chip manufacturing.',
'AI in India: National AI Strategy (NITI Aayog); IndiaAI Mission (₹10,372 crore); target for AI compute infrastructure.',
'DPDP Act 2023: Digital Personal Data Protection Act — India\'s first comprehensive data protection law.',
'ChatGPT: OpenAI\'s large language model (LLM); launched November 2022.',
'Generative AI: AI that can create text, images, music, code — based on large language models.',
'UPI LITE: Works offline for small transactions (up to ₹500 per transaction).',
'Account Aggregator framework: Allows sharing financial data with consent; RBI-regulated.',
'ONDC (Open Network for Digital Commerce): Government initiative to democratize e-commerce like UPI did for payments.',
'Drone Rules 2021: India liberalized drone regulations; aim to create drone hub.',
'National Quantum Mission: ₹6,003 crore over 2023-2031; quantum computing, communication, sensing.',
'Semiconductor Fabrication Plant (Fab): Tata Electronics Plant in Dholera (Gujarat); Tata and CG Power plants in Sanand; Micron Technology in Sanand.',
'India Stack: Aadhaar + UPI + DigiLocker + eSign + Account Aggregator = Digital Public Infrastructure.',
'Aadhaar: World\'s largest biometric identity system; 1.35+ billion enrolled.',
'DigiLocker: Digital document wallet; 250+ crore documents stored (2024).',
'CoWIN: COVID vaccination management platform; delivered 2.2 billion vaccine doses.',
'UMANG (Unified Mobile Application for New-age Governance): Single platform for 1,700+ government services.',
'GeM (Government e-Marketplace): Online procurement for government entities; ₹4 lakh crore+ orders (FY24).',
'e-RUPI: Voucher-based digital payment for targeted benefit delivery.',
]};

const IMPORTANT_PERSONS={
title:'Key Personalities in Banking & Finance',
persons:[
{name:'Sanjay Malhotra',role:'26th RBI Governor (December 2024 onwards)',note:'Former Revenue Secretary; first IAS officer as RBI Governor in recent times'},
{name:'Shaktikanta Das',role:'25th RBI Governor (December 2018 - December 2024)',note:'Under him: COVID relief, inflation targeting challenges, digital payment growth'},
{name:'Urjit Patel',role:'24th RBI Governor (2016-2018)',note:'Established MPC; resigned over differences with government (rare in RBI history)'},
{name:'Raghuram Rajan',role:'23rd RBI Governor (2013-2016)',note:'Predicted 2008 financial crisis; focused on inflation targeting and financial inclusion'},
{name:'Y.V. Reddy',role:'21st RBI Governor (2003-2008)',note:'Kept Indian banks away from risky CDOs; India relatively unscathed in 2008 crisis'},
{name:'C.D. Deshmukh',role:'First Indian RBI Governor (1943-1949)',note:'Later became Finance Minister of India'},
{name:'Nirmala Sitharaman',role:'Finance Minister of India (2019-present)',note:'Presented 6 consecutive Union Budgets; first woman to present full Budget'},
{name:'Manmohan Singh',role:'Finance Minister 1991-96; Prime Minister 2004-14',note:'Architect of 1991 LPG reforms; changed India\'s economic trajectory'},
{name:'Madhabi Puri Buch',role:'SEBI Chairperson (2022-2024)',note:'First woman SEBI chief; resigned after Hindenburg allegations'},
{name:'Tuhin Kanta Pandey',role:'SEBI Chairperson (from 2025)',note:'IAS officer; succeeded Madhabi Puri Buch'},
{name:'Debasish Panda',role:'IRDAI Chairman (2022-present)',note:'Under him: liberalization of insurance regulations'},
{name:'Deepak Mohanty',role:'Former RBI ED; chaired committee on PSL',note:'Committees on financial inclusion and priority sector lending'},
{name:'Nachiket Mor',role:'Former RBI Board member; financial inclusion expert',note:'Chaired committee on comprehensive financial services for small businesses'},
{name:'M.S. Narasimham',role:'13th RBI Governor (1977); Banking Reform Committee Chair',note:'Narasimham Committee I (1991) and II (1998) transformed Indian banking'},
{name:'Y. Venugopal Reddy',role:'Not to be confused with Y.V. Reddy',note:'Different person — check context carefully in exams'},
{name:'Amartya Sen',role:'Nobel Prize in Economics 1998; development economist',note:'Capability Approach to development; Poverty and Famines; founded HDR approach'},
{name:'Ragnar Nurkse',role:'Estonian economist; Balanced Growth Theory',note:'Circular flow of poverty; Need simultaneous investment across sectors'},
{name:'Albert Hirschman',role:'German-American economist; Unbalanced Growth Theory',note:'Invest in key sectors to generate linkages and imbalances that drive growth'},
{name:'Milton Friedman',role:'Nobel 1976; Monetarism founder',note:'Money supply growth causes inflation; "Inflation is always and everywhere a monetary phenomenon"'},
{name:'John Maynard Keynes',role:'British economist; Keynesian economics',note:'Government spending can stimulate demand during recessions; Founder of macroeconomics'},
{name:'Paul Samuelson',role:'Nobel 1970; Neoclassical synthesis',note:'First American to win Nobel in Economics; wrote foundational "Economics" textbook'},
{name:'Robert Solow',role:'Nobel 1987; Solow Growth Model',note:'Long-run growth depends on technological progress, not just capital accumulation'},
{name:'Arthur Lewis',role:'Nobel 1979; Dual Sector Model',note:'Labor surplus theory; Lewis Turning Point; development economics pioneer'},
{name:'A.P.J. Abdul Kalam',role:'11th President of India (2002-2007)',note:'Missile Man of India; Children\'s Day (India) now observed on his birthday (Oct 15) — actually birthday was Oct 15 not Nov 14 which remains Nehru birthday'},
]};
