// ═══ QUANTITATIVE APTITUDE — Comprehensive Tricks & Shortcuts ═══

const QUANT_GUIDE={
title:'Complete Quantitative Aptitude Strategy — Shortcuts, Tricks, and Patterns',
topics:[
{
topic:'Percentage — Speed Math Techniques',
shortcuts:[
'Convert to fractions for quick calculation: 10%=1/10, 12.5%=1/8, 20%=1/5, 25%=1/4, 33.33%=1/3, 50%=1/2',
'To find X% of Y: Move decimal place (10% of 450 = 45), then adjust (15% = 10% + 5% = 45+22.5=67.5)',
'Successive discount of a% and b%: Effective = a+b-ab/100',
'Price rise by r%, consumption decrease to maintain expenditure: r/(100+r) × 100',
'If A is r% more than B, then B is r/(100+r) × 100% less than A',
'If A is r% less than B, then B is r/(100-r) × 100% more than A',
'Percentage change = (New-Old)/Old × 100 (always use OLD as base)',
'Population after n years with growth rate r%: P×(1+r/100)^n',
'Population decreased by r% for n years: P×(1-r/100)^n',
'Two successive changes: a% then b%: Single change = (a+b+ab/100)%',
'Exam trick: If passing marks = X% and student gets P marks and fails by F marks, then P+F = X%×Total',
'Shortcut for 66.67% of 900: 2/3 of 900 = 600',
'Shortcut for 83.33% of 720: 5/6 of 720 = 600',
'Shortcut: Find 37.5% of a number = 3/8 of that number',
'If x% of A = y% of B, then A/B = y/x'
],
patternQs:[
{q:'A man\'s salary is increased by 20% and then decreased by 20%. Net change?',
steps:['Using formula: a% increase then a% decrease = a²/100 % decrease','= 20×20/100 = 4% decrease'],
trick:'Whenever same % increase then decrease (or vice versa), there\'s always a NET LOSS = (a²/100)%',
ans:'4% net decrease'},
{q:'30% of A = 20% of B. A:B = ?',
steps:['30A/100 = 20B/100','3A = 2B','A/B = 2/3 → A:B = 2:3'],
trick:'Cross multiply percentages and flip: A:B = 20:30 = 2:3',
ans:'A:B = 2:3'}
]},{
topic:'Profit, Loss, and Discount — Key Formulas',
shortcuts:[
'SP = CP × (100+P%)/100 or CP × (100-L%)/100',
'CP = SP × 100/(100+P%) or SP × 100/(100-L%)',
'Profit% always calculated on CP (never on SP)',
'Discount% always calculated on Marked Price (MP), not CP',
'If discount is d% and profit is p%, then MP/CP = (100+p)/(100-d)',
'Dishonest trader using false weight: Profit% = (True weight - False weight)/False weight × 100',
'Two items sold at same SP — one at a% gain and other at a% loss: Always a NET LOSS = a²/100 %',
'Single equivalent discount for successive discounts d1, d2: = d1+d2 - d1×d2/100',
'If article sold at SP1 gives r1% and at SP2 gives r2%, then CP = (SP1×r2 - SP2×r1)/(r2-r1)',
'Cost price formula when gain% and loss% on two transactions are given: use weighted average carefully',
'Shortcut: If CP ratio is p:q and SP ratio is r:s, and one is at gain of x%, find other\'s status',
'Breakeven SP = CP (0% profit)',
'Percentage profit on SP: If profit is P%, profit on SP = P/(100+P) × 100'
],
patternQs:[
{q:'Trader marks 40% above cost and allows 20% discount. Profit%?',
steps:['Let CP=100','MP = 140','SP = 140 × 0.8 = 112','Profit = 12%'],
trick:'Profit% = (1 + markup%/100)(1 - discount%/100) - 1 × 100 = 1.4×0.8 - 1 = 0.12 = 12%',
ans:'12% profit'},
{q:'Selling 45 oranges for ₹40, profit 25%. To gain 25% on 60 oranges, sell at what price?',
steps:['At 25% profit on 45 oranges selling for 40: CP of 45 = 40/1.25 = 32','CP per orange = 32/45','To gain 25% on 60: SP = 60 × (32/45) × 1.25 = 60×32×1.25/45 = 2400/45 = 53.33'],
trick:'Use CP per unit carefully',
ans:'₹53.33'}
]},{
topic:'Simple Interest — Complete Framework',
shortcuts:[
'SI = PRT/100 where P=Principal, R=Rate%, T=Time in years',
'Amount = P(1 + RT/100)',
'If SI = P (sum doubles), then RT = 100',
'If SI = 2P (sum triples), then RT = 200',
'To find P: P = (SI × 100)/(R × T)',
'To find R: R = (SI × 100)/(P × T)',
'To find T: T = (SI × 100)/(P × R)',
'If A doubles in x years, it triples in 2x years (linear growth under SI)',
'Effective rate for half-year compounding converted to annual SI: Annual equivalent',
'SI for n months = PRT/1200 (when R is annual %)',
'Difference in SI when rate changes from R1 to R2: P(R2-R1)T/100',
'When total SI on two amounts P1 and P2 at rates R1 and R2 for time T is given, find either P or R',
'Sum borrowed at different rates for different periods: calculate each SI separately and add',
'Installment formula under SI: Each equal installment = (P×100)/(100T + RT²/2)'
],
patternQs:[
{q:'₹5000 lent at 6% for 4 years and ₹3000 at 8% for 3 years. Total SI?',
steps:['SI1 = 5000×6×4/100 = 1200','SI2 = 3000×8×3/100 = 720','Total = 1920'],
trick:'Just calculate each separately and add. Very straightforward.',
ans:'₹1920'},
{q:'A sum doubles in 10 years at SI. In how many years will it become 5 times?',
steps:['Doubles: P = SI for 10 years → RT = 100 → rate = 10%','5 times: SI = 4P → 4P = P×10×T/100 → T = 40 years'],
trick:'If doubles in n years, becomes k times in (k-1)n years',
ans:'40 years'}
]},{
topic:'Compound Interest — Time-Saving Methods',
shortcuts:[
'Amount = P(1+R/100)^n',
'For 2 years: CI = P[R/100](2 + R/100) = PR/100 × (2+r) where r=R/100',
'CI-SI for 2 years = P(R/100)² = PR²/10000',
'CI-SI for 3 years = P(R/100)²(R/100 + 3) = PR²(R+300)/1000000',
'Difference method: If A3-A2 = CI3rd year interest; This divided by A2 gives rate',
'Half-yearly: Use R/2 and 2n instead of R and n',
'Quarterly: Use R/4 and 4n',
'To find CI when Amount and Principal given: CI = A - P',
'Rule of 72: Time to double ≈ 72/R% at compound interest',
'Rule of 114: Time to triple ≈ 114/R%',
'If CI of year 3 is ₹x and CI of year 2 is ₹y, then Rate = (x-y)/y × 100',
'Sum becomes P×(1+r)^n; if we know this, we can find r or n using logarithms',
'Effective annual rate for half-yearly compounding at R%: (1+R/200)² - 1',
'Present Value of FV received after n years: PV = FV/(1+r)^n'
],
patternQs:[
{q:'CI on ₹10000 at 10% for 3 years?',
steps:['Method 1: Direct formula: 10000×(1.1)³ - 10000 = 13310-10000 = 3310',
'Method 2: Year 1 interest = 1000. Year 2 = 1100. Year 3 = 1210. Total = 3310',
'Method 3: SI for 3 years = 3000. Difference = 3310-3000 = 310 = P(R/100)²(R/100+3) = 10000×0.01×(0.1+3) = 310✓'],
trick:'Always know how to verify using the difference between CI and SI formula',
ans:'₹3310'},
{q:'A sum becomes ₹2160 in 2 years and ₹2592 in 3 years at CI. Find the rate.',
steps:['Ratio: 2592/2160 = 1.2 = 1 + r/100','r/100 = 0.2','Rate = 20%'],
trick:'CI of any two consecutive years: A(n+1)/A(n) = 1 + R/100',
ans:'20% per annum'}
]},{
topic:'Time & Work — Systematic Approach',
shortcuts:[
'Always convert to 1-day work: If A does in n days, A does 1/n per day',
'LCM method: Find LCM of all days; total work = LCM units',
'A and B together: 1/T = 1/a + 1/b; T = ab/(a+b)',
'A, B, C together: 1/T = 1/a + 1/b + 1/c',
'A alone = 1/(combined rate) - (B+C)\'s rate → then find A alone',
'Efficiency: If A is twice as efficient as B, A takes half the time B takes',
'MDH formula: M₁D₁H₁ = M₂D₂H₂ (Men × Days × Hours = constant for same work)',
'Wages are distributed in ratio of work done = efficiency × time worked',
'Alternate working: A works day 1, B works day 2, etc. — find daily rates separately',
'Pipe filling: Addition gives combined rate; draining pipe is negative',
'If A fills in x hours and B drains in y hours (x<y), net rate = 1/x - 1/y',
'Work efficiency formula: If A does x% of work per day, he completes in 100/x days',
'Fraction of work remaining after k days = 1 - k × (combined rate)',
'Work done approach: Set total work = LCM of given days for cleaner numbers'
],
patternQs:[
{q:'A, B, C can do work in 10, 15, 20 days. They work together for 4 days, then C leaves. When is work done?',
steps:['LCM(10,15,20) = 60. A=6/day, B=4/day, C=3/day, Together=13/day',
'In 4 days: 4×13=52 units done. Remaining=8 units.',
'A+B = 10/day. Time = 8/10 = 0.8 days',
'Total time = 4.8 days'],
trick:'Use LCM method for cleaner numbers. Find remaining work then apply reduced team rate.',
ans:'4 days 19.2 hours ≈ 4.8 days'},
{q:'A is 50% more efficient than B. Together they do work in 6 days. B alone takes?',
steps:['A is 50% more efficient: if B=x per day, A=1.5x per day',
'Together: x+1.5x = 2.5x per day; in 6 days: 15x units done = total work',
'B alone: 15x/x = 15 days'],
trick:'Express efficiency as B=1, A=1.5; combined=2.5; total work=2.5×6=15; B alone=15/1=15',
ans:'15 days'}
]},{
topic:'Speed, Distance & Time — Exam Pattern Mastery',
shortcuts:[
'D=S×T; S=D/T; T=D/S',
'km/h to m/s: multiply by 5/18. m/s to km/h: multiply by 18/5',
'Average speed for EQUAL DISTANCES: Harmonic mean = 2ab/(a+b)',
'Average speed for EQUAL TIMES: Arithmetic mean = (a+b)/2',
'Relative speed: Opposite directions = S1+S2; Same direction = |S1-S2|',
'Train crossing pole/standing person: Time = Length of train / Speed',
'Train crossing platform: Time = (Length of train + Length of platform) / Speed',
'Two trains crossing: Time = (L1+L2) / Relative Speed',
'Train overtaking a person walking: Time = (Length of train) / (Train speed - person speed) [same direction]',
'Boat downstream speed = Boat speed + Current speed (D = B+S)',
'Boat upstream speed = Boat speed - Current speed (U = B-S)',
'Boat speed = (D+U)/2; Current speed = (D-U)/2',
'If boat\'s ratio of downstream to upstream speed = n:1, ratio of (B+C):(B-C) = n:1',
'Distance problems with multiple parts: Use time = distance/speed for each part separately',
'If trains start simultaneously from A and B toward each other and meet at point P, then: PA/PB = SA/SB',
'Race problems: If A gives B a start of x meters or x seconds, handle these as separate initial conditions'
],
patternQs:[
{q:'Train A (100m) at 60 km/h meets Train B (150m) at 90 km/h coming from opposite direction. Time to cross?',
steps:['Relative speed = 60+90 = 150 km/h = 150×5/18 = 41.67 m/s',
'Total length = 100+150 = 250m',
'Time = 250/41.67 = 6 seconds'],
trick:'Always: (1) Convert to same units, (2) Add lengths for crossing problems, (3) Add speeds for opposite direction',
ans:'6 seconds'},
{q:'A boat covers 40 km upstream and returns. Total time: 20 hours. Speed of water = 2 km/h. Speed of boat in still water?',
steps:['Let boat speed = B. D = 40/(B-2) + 40/(B+2) = 20',
'40[(B+2)+(B-2)] / (B²-4) = 20',
'40×2B / (B²-4) = 20',
'4B = B²-4','B²-4B-4=0... Hmm, let me try B=6: 40/4+40/8=10+5=15≠20. B=5: 40/3+40/7≠20. B=4: 40/2+40/6=20+6.67≠20. B=9: 40/7+40/11≠20. B=10: 40/8+40/12=5+3.33=8.33≠20.',
'Let me try again: D=20. (B-2)=upstream, (B+2)=downstream. 40/(B-2)+40/(B+2)=20. 40(2B)/(B²-4)=20. 80B=20(B²-4). 4B=B²-4. B²-4B-4=0. B=(4±√32)/2=2±2√2. B=2+2√2≈4.83 km/h'],
trick:'Set up equation carefully. For boat problems: Always write both legs of journey.',
ans:'Boat speed = 2+2√2 ≈ 4.83 km/h'}
]},{
topic:'Ratio, Proportion & Mixture — Advanced Techniques',
shortcuts:[
'To combine ratios: Make common term equal (LCM method)',
'A:B:C from A:B and B:C: Make B equal by LCM',
'Compounded ratio of a:b and c:d = ac:bd',
'Duplicate ratio of a:b = a²:b²; Triplicate = a³:b³',
'Inverse ratio of a:b = b:a',
'Partnership: Simple (same time) → profit ∝ capital; Compound (different time) → profit ∝ capital×time',
'Alligation rule: (Cheaper)(Dearer) mixed at mean price: ratio = (Dearer-Mean):(Mean-Cheaper)',
'Drawing and adding milk/water: Concentration after n operations = C₀×((V-v)/V)^n',
'where C₀=initial concentration, V=total volume, v=volume replaced each time',
'If three quantities are in proportion a:b:c, then a/b = b/c → b² = ac (b is geometric mean)',
'Continued proportion: a:b = b:c → a, b, c are in GP; a:b:c = a:ar:ar²',
'Mean proportional of a and c = √(ac)',
'Third proportional to a, b = b²/a'
],
patternQs:[
{q:'Mix milk worth ₹18/L and ₹26/L to get mixture worth ₹22/L. Ratio?',
steps:['By alligation: Dearer-Mean = 26-22=4; Mean-Cheaper = 22-18=4',
'Ratio = 4:4 = 1:1'],
trick:'Draw alligation cross: Place higher price and lower price at top; mean price at center; cross-subtract',
ans:'Equal parts (1:1)'},
{q:'Vessel A has milk:water = 3:1. Vessel B has milk:water = 4:1. Mixed in ratio 2:3. Final ratio of milk to water?',
steps:['Milk from A = 3/4; Water from A = 1/4',
'Milk from B = 4/5; Water from B = 1/5',
'Mixed 2:3: Total milk = 2×(3/4) + 3×(4/5) = 1.5+2.4 = 3.9',
'Total water = 2×(1/4) + 3×(1/5) = 0.5+0.6 = 1.1',
'Ratio = 3.9:1.1 = 39:11'],
trick:'Calculate contribution from each vessel separately, then combine',
ans:'39:11'}
]},{
topic:'Number System — Essential Concepts',
shortcuts:[
'Divisibility rules: by 2 (last digit even), by 3 (digit sum divisible by 3), by 4 (last 2 digits), by 5 (last digit 0 or 5), by 6 (div by 2 AND 3), by 7 (double last digit, subtract from rest; repeat), by 8 (last 3 digits), by 9 (digit sum), by 11 (alternating digit difference = 0 or 11)',
'Sum of first n natural numbers: n(n+1)/2',
'Sum of first n even numbers: n(n+1)',
'Sum of first n odd numbers: n²',
'Sum of squares 1 to n: n(n+1)(2n+1)/6',
'Sum of cubes 1 to n: [n(n+1)/2]²',
'Perfect squares: n² -- Remember: units digits of squares can only be 0,1,4,5,6,9',
'Perfect cubes: n³ -- Units digits can be anything 0-9',
'LCM × HCF = Product of two numbers',
'HCF of fractions = HCF of numerators / LCM of denominators',
'LCM of fractions = LCM of numerators / HCF of denominators',
'Number of factors: If n = a^p × b^q × c^r, factors = (p+1)(q+1)(r+1)',
'Sum of all factors: [(a^(p+1)-1)/(a-1)] × [(b^(q+1)-1)/(b-1)] × ...',
'Number of ways to express n as product of 2 factors: (1/2)(p+1)(q+1)(r+1) for non-perfect square; +1/2 for perfect square',
'Remainder theorem: If f(x) is divided by (x-a), remainder = f(a)',
'Cyclicity of units digits: 1→1,2→2,4,8,6,2, 3→3,9,7,1,3, 4→4,6,4, 5→5, 6→6, 7→7,9,3,1,7, 8→8,4,2,6,8, 9→9,1,9'
],
patternQs:[
{q:'What is the units digit of 7^95?',
steps:['Cyclicity of 7: 7,9,3,1 (cycle of 4)','95 = 4×23 + 3','Third in cycle = 3'],
trick:'Always find cycle length first, then find remainder when power is divided by cycle length',
ans:'Units digit = 3'},
{q:'How many numbers from 1-200 are divisible by 4 but NOT by 8?',
steps:['Divisible by 4: 200/4 = 50 numbers','Divisible by 8: 200/8 = 25 numbers','Divisible by 4 not 8 = 50-25 = 25'],
trick:'Numbers divisible by 4 but not 8 are exactly half of those divisible by 4',
ans:'25 numbers'}
]},{
topic:'Data Interpretation — Speed Reading Techniques',
shortcuts:[
'Read the question before studying the chart/table in detail',
'Identify the metric asked: absolute value, % change, ratio, rank',
'Approximate when options are far apart — saves calculation time',
'For % change: approximate numerically then compare to options',
'For ratio comparison: convert to decimals OR cross multiply',
'When comparing multiple ratios: find the odd-looking one and verify only that one',
'For DI tables: Scan all rows and columns before solving — understand structure',
'Identify units carefully (Cr vs L, %, absolute number)',
'For pie charts: check if question asks for sector value or % of total',
'For bar charts: height comparison vs actual values — be careful',
'Caselet DI: Draw own mini-table from given text before attempting questions',
'If DI has many decimal calculations, look for integer approximations in options',
'For % share problems: part/total × 100; identify the total correctly',
'Trend analysis: note whether values increasing/decreasing consistently or with outliers'
],
patternQs:[
{q:'Company profit: 2019=₹120Cr, 2020=₹105Cr, 2021=₹135Cr, 2022=₹150Cr, 2023=₹180Cr. Average profit?',
steps:['Sum = 120+105+135+150+180 = 690','Average = 690/5 = ₹138 Crore'],
trick:'Quick sum: notice 120+180=300, 105+135=240, 150 standalone. 300+240+150=690. Divide by 5=138.',
ans:'₹138 Crore'},
{q:'If 2020 profit fell 25% from 2019 and 2021 rose to ₹140Cr from ₹105Cr, % increase?',
steps:['2020=105 (25% below 120: 120×0.75=90, but given as 105 — contradiction. Using given: 2020=105.)',
'2021=140','% increase from 2020 to 2021 = (140-105)/105 × 100 = 35/105 × 100 = 33.33%'],
trick:'% change = (New-Old)/Old × 100. Always use OLD (earlier value) as base.',
ans:'33.33% increase'}
]},{
topic:'Algebra & Equations — Exam-Focused Approach',
shortcuts:[
'For ax+by=c type: Try substitution method for simple values; elimination for two equations',
'Quadratic x²-5x+6=0: factors as (x-2)(x-3), roots 2,3. Product=c/a, Sum=-b/a',
'Sum of roots of ax²+bx+c = -b/a; Product of roots = c/a',
'If roots are given (α,β): equation is x² - (α+β)x + αβ = 0',
'Nature of roots: Discriminant D = b²-4ac. D>0: two real roots; D=0: equal real roots; D<0: complex roots',
'Word to equation: "3 more than twice a number" = 2x+3; "number divided by 5 equals 7" = x/5=7',
'Age problems: Always set up as present ages, then use given info to form equations',
'For work-rate equations: rates add (workers working together), not times',
'For cost problems: cost = price × quantity; total cost = sum of individual costs',
'Algebraic identities: (a+b)²=a²+2ab+b²; (a-b)²=a²-2ab+b²; a²-b²=(a+b)(a-b)',
'(a+b)³=a³+3a²b+3ab²+b³; (a-b)³=a³-3a²b+3ab²-b³',
'a³+b³=(a+b)(a²-ab+b²); a³-b³=(a-b)(a²+ab+b²)',
'If x+y=S and xy=P, then x²+y²=S²-2P; x³+y³=S³-3SP; (x-y)²=S²-4P'
],
patternQs:[
{q:'If x+1/x=4, find x⁴+1/x⁴',
steps:['Square: x²+2+1/x²=16 → x²+1/x²=14',
'Square again: x⁴+2+1/x⁴=196 → x⁴+1/x⁴=194'],
trick:'These "if x+1/x=k" patterns appear frequently. Build up: first find x²+1/x², then x⁴+1/x⁴.',
ans:'194'}
]},{
topic:'Permutation, Combination & Probability — Clear Approach',
shortcuts:[
'nPr = n!/(n-r)! : ORDERED selection (where arrangement matters)',
'nCr = n!/[r!(n-r)!] : UNORDERED selection (where only selection matters)',
'nCr = nC(n-r) : Choosing r from n is same as leaving out n-r',
'nPr = nCr × r! : Permutations = Combinations × arrangements of selected items',
'Circular arrangements: (n-1)! for n distinct items; if clockwise=counterclockwise: (n-1)!/2',
'Items always together: Treat as single unit; (n-k+1)! × k! if they can rearrange among themselves',
'Items never together: Total - (always together arrangements)',
'Partition: Divide n items into groups of r1, r2, r3... : n!/(r1!×r2!×r3!)',
'Probability P(A) = Favorable outcomes / Total outcomes',
'P(A∪B) = P(A) + P(B) - P(A∩B)',
'P(A∩B) = P(A) × P(B) for independent events',
'P(not A) = 1 - P(A)',
'P(A|B) = P(A∩B)/P(B) for conditional probability',
'Binomial probability: P(exactly r successes in n trials) = nCr × p^r × (1-p)^(n-r)',
'For "at least one": use complement: P(at least 1) = 1 - P(none)'
],
patternQs:[
{q:'5 men and 3 women. Committee of 3 with at least 1 woman?',
steps:['Total committees = C(8,3) = 56',
'Committees with no women = C(5,3) = 10',
'At least 1 woman = 56-10 = 46'],
trick:'Complement method is faster when "at least" and "none" situations contrast.',
ans:'46 committees'},
{q:'Two cards drawn from pack of 52. P(both aces)?',
steps:['P = C(4,2)/C(52,2) = 6/1326 = 1/221'],
trick:'Always use combinations for drawing cards (order doesn\'t matter).',
ans:'1/221'}
]}
]};
