if(typeof Q==='undefined')window.Q=[];

// ═══════════════════════════════════════════════════════════
// STATIC GK — Awards, Appointments, Sports, Summits, Schemes, Science
// Covers SBI PO Prelims/Mains and RBI Grade B Phase 1
// ═══════════════════════════════════════════════════════════

const STATIC_GK_DATA = {
  section: 'general_knowledge',
  version: '2024-2025',
  totalQuestions: 105,
  topics: ['awards_honours','appointments','sports','summits_organisations','schemes_policies','science_technology'],
  exams: ['sbi_prelims','sbi_mains','rbi_phase1'],
  description: 'Static GK for Indian Banking Exams covering Nobel Prizes 2023-2024, Bharat Ratna 2024, Key Appointments, Paris Olympics 2024, G20, BRICS, Government Schemes, ISRO Missions'
};

// ─────────────────────────────────────────────────────────────
// 1. AWARDS & HONOURS (20 questions) — IDs: sgk_awards_1 to sgk_awards_20
// ─────────────────────────────────────────────────────────────
Q.push(
{id:'sgk_awards_1',s:'general_knowledge',t:'awards_honours',d:'medium',q:'Who won the Nobel Prize in Physiology or Medicine 2023?',o:['Jennifer Doudna & Emmanuelle Charpentier','Katalin Karikó & Drew Weissman','Victor Ambros & Gary Ruvkun','Svante Pääbo & Robert Malone'],c:1,e:'Katalin Karikó and Drew Weissman won the 2023 Nobel Prize in Medicine for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_2',s:'general_knowledge',t:'awards_honours',d:'medium',q:'The 2023 Nobel Prize in Physics was awarded for discoveries about attosecond pulses of light used to study electron dynamics. Who were the laureates?',o:['Pierre Agostini, Ferenc Krausz and Anne L\'Huillier','John Clauser, Alain Aspect and Anton Zeilinger','Roger Penrose, Reinhard Genzel and Andrea Ghez','Syukuro Manabe, Klaus Hasselmann and Giorgio Parisi'],c:0,e:'Pierre Agostini, Ferenc Krausz and Anne L\'Huillier won the 2023 Nobel Prize in Physics for experimental methods that generate attosecond pulses of light to study the motion of electrons in matter.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_3',s:'general_knowledge',t:'awards_honours',d:'medium',q:'The 2023 Nobel Prize in Chemistry was awarded for the discovery and synthesis of quantum dots. Which scientists received this prize?',o:['Moungi Bawendi, Louis Brus and Alexei Ekimov','David Baker, Demis Hassabis and John Jumper','Carolyn Bertozzi, Morten Meldal and Barry Sharpless','Benjamin List and David MacMillan'],c:0,e:'Moungi Bawendi, Louis Brus and Alexei Ekimov won the 2023 Nobel Prize in Chemistry for the discovery and synthesis of quantum dots — nanoparticles so tiny that their size determines their properties.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_4',s:'general_knowledge',t:'awards_honours',d:'easy',q:'Who won the Nobel Prize in Literature 2023?',o:['Han Kang','Jon Fosse','Annie Ernaux','Abdulrazak Gurnah'],c:1,e:'Jon Fosse, a Norwegian author and playwright, won the 2023 Nobel Prize in Literature "for his innovative plays and prose which give voice to the unsayable." He is known for works like Septology.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_5',s:'general_knowledge',t:'awards_honours',d:'medium',q:'The 2023 Nobel Peace Prize was awarded to Narges Mohammadi. She is a human rights activist from which country?',o:['Afghanistan','Iran','Saudi Arabia','Turkey'],c:1,e:'Narges Mohammadi, an Iranian human rights activist, won the 2023 Nobel Peace Prize for her fight against the oppression of women in Iran and her efforts to promote human rights and freedom for all.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_6',s:'general_knowledge',t:'awards_honours',d:'medium',q:'Who won the 2023 Nobel Prize in Economics (Nobel Memorial Prize in Economic Sciences)?',o:['Ben Bernanke, Douglas Diamond and Philip Dybvig','Claudia Goldin','Paul Milgrom and Robert Wilson','Abhijit Banerjee and Esther Duflo'],c:1,e:'Claudia Goldin won the 2023 Nobel Prize in Economics "for having advanced our understanding of women\'s labour market outcomes," making her the third woman to receive this prize.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_awards_7',s:'general_knowledge',t:'awards_honours',d:'medium',q:'The 2024 Nobel Prize in Physiology or Medicine was awarded for the discovery of microRNA. Who were the laureates?',o:['Katalin Karikó & Drew Weissman','Victor Ambros & Gary Ruvkun','Jennifer Doudna & Emmanuelle Charpentier','Craig Mello & Andrew Fire'],c:1,e:'Victor Ambros and Gary Ruvkun won the 2024 Nobel Prize in Medicine for the discovery of microRNA (miRNA) and its role in post-transcriptional gene regulation.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_8',s:'general_knowledge',t:'awards_honours',d:'hard',q:'The 2024 Nobel Prize in Physics was awarded for foundational discoveries and inventions that enable machine learning with artificial neural networks. Who received it?',o:['Geoffrey Hinton & Yann LeCun','John Hopfield & Geoffrey Hinton','Yoshua Bengio & Geoffrey Hinton','John Hopfield & Yoshua Bengio'],c:1,e:'John Hopfield and Geoffrey Hinton won the 2024 Nobel Prize in Physics for foundational discoveries and inventions enabling machine learning with artificial neural networks. Hopfield invented the Hopfield network; Hinton developed the Boltzmann machine.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_awards_9',s:'general_knowledge',t:'awards_honours',d:'hard',q:'The 2024 Nobel Prize in Chemistry was awarded for protein structure prediction and design. Who were the three laureates?',o:['David Baker, Demis Hassabis and John Jumper','Moungi Bawendi, Louis Brus and Alexei Ekimov','Frances Arnold, George Smith and Gregory Winter','Jennifer Doudna, Emmanuelle Charpentier and David Liu'],c:0,e:'David Baker (protein design), Demis Hassabis and John Jumper (AlphaFold AI protein structure prediction) won the 2024 Nobel Prize in Chemistry. Hassabis and Jumper are from Google DeepMind.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_awards_10',s:'general_knowledge',t:'awards_honours',d:'easy',q:'Who won the Nobel Prize in Literature 2024?',o:['Jon Fosse','Han Kang','Olga Tokarczuk','Abdulrazak Gurnah'],c:1,e:'Han Kang, a South Korean author, won the 2024 Nobel Prize in Literature "for her intense poetic prose that confronts historical traumas and exposes the fragility of human life." She is known for The Vegetarian and Human Acts.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_11',s:'general_knowledge',t:'awards_honours',d:'medium',q:'The 2024 Nobel Peace Prize was awarded to Nihon Hidankyo. What is Nihon Hidankyo?',o:['A Japanese environmental organisation','A Japanese survivor organisation of the Hiroshima and Nagasaki atomic bombings','A South Korean human rights group','A Chinese peace movement'],c:1,e:'Nihon Hidankyo, a Japanese grassroots organisation of atomic bomb survivors (Hibakusha), won the 2024 Nobel Peace Prize for their efforts towards a world free of nuclear weapons.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_12',s:'general_knowledge',t:'awards_honours',d:'hard',q:'The 2024 Nobel Prize in Economics was awarded for studies on how institutions are formed and affect prosperity. Who were the laureates?',o:['Abhijit Banerjee, Esther Duflo and Michael Kremer','Daron Acemoglu, Simon Johnson and James A. Robinson','Paul Milgrom, Robert Wilson and Alvin Roth','Claudia Goldin, Raj Chetty and Lawrence Katz'],c:1,e:'Daron Acemoglu, Simon Johnson and James A. Robinson won the 2024 Nobel Prize in Economics for studies on how institutions are formed and affect prosperity. Their book "Why Nations Fail" is widely cited.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_awards_13',s:'general_knowledge',t:'awards_honours',d:'easy',q:'How many Bharat Ratna awards were announced in January–February 2024, which was a record?',o:['3','4','5','6'],c:2,e:'Five Bharat Ratna awards were announced in January–February 2024 — a record number at one time. The recipients were Karpoori Thakur, LK Advani, PV Narasimha Rao, MS Swaminathan and Chaudhary Charan Singh.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_14',s:'general_knowledge',t:'awards_honours',d:'medium',q:'Which former Prime Minister of India was posthumously awarded the Bharat Ratna in 2024?',o:['Atal Bihari Vajpayee','PV Narasimha Rao','IK Gujral','HD Deve Gowda'],c:1,e:'PV Narasimha Rao, the 9th Prime Minister of India (1991–1996) who steered India\'s economic liberalisation, was posthumously awarded the Bharat Ratna in 2024.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_15',s:'general_knowledge',t:'awards_honours',d:'medium',q:'MS Swaminathan, who received the Bharat Ratna 2024 (posthumously), is known as the father of which revolution in India?',o:['White Revolution','Blue Revolution','Green Revolution','Golden Revolution'],c:2,e:'MS Swaminathan (1925–2023) is known as the "Father of Green Revolution in India" for his role in introducing high-yielding variety wheat seeds that transformed Indian agriculture in the 1960s.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_16',s:'general_knowledge',t:'awards_honours',d:'medium',q:'Karpoori Thakur, who received the Bharat Ratna 2024 (posthumously), was the Chief Minister of which state?',o:['Uttar Pradesh','Bihar','Jharkhand','Madhya Pradesh'],c:1,e:'Karpoori Thakur was a socialist leader who served as Chief Minister of Bihar twice (1970–71 and 1977–79). He was known as "Jan Nayak" (People\'s Leader).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_17',s:'general_knowledge',t:'awards_honours',d:'easy',q:'Who won the Booker Prize 2023 for the novel "Prophet Song"?',o:['Samantha Harvey','Paul Lynch','Richard Powers','Jonathan Escoffery'],c:1,e:'Paul Lynch, an Irish author, won the 2023 Booker Prize for his novel "Prophet Song," a dystopian story set in a near-future Ireland descending into totalitarianism.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_18',s:'general_knowledge',t:'awards_honours',d:'easy',q:'Who won the Booker Prize 2024 for the novel "Orbital"?',o:['Paul Lynch','Samantha Harvey','Rachel Kushner','Percival Everett'],c:1,e:'Samantha Harvey, a British author, won the 2024 Booker Prize for her novel "Orbital," a meditative story following six astronauts on the International Space Station over 24 hours.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_19',s:'general_knowledge',t:'awards_honours',d:'medium',q:'LK Advani, who received the Bharat Ratna 2024, was the Deputy Prime Minister of India under which Prime Minister?',o:['PV Narasimha Rao','HD Deve Gowda','Atal Bihari Vajpayee','Manmohan Singh'],c:2,e:'LK Advani served as Deputy Prime Minister of India from 2002 to 2004 under Prime Minister Atal Bihari Vajpayee. He is a senior leader of the Bharatiya Janata Party (BJP).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_awards_20',s:'general_knowledge',t:'awards_honours',d:'medium',q:'Chaudhary Charan Singh, who received the Bharat Ratna 2024, served as the Prime Minister of India during which period?',o:['1977–1979','1979–1980','1984–1989','1989–1991'],c:1,e:'Chaudhary Charan Singh served as the 5th Prime Minister of India from July 1979 to January 1980. He was a prominent farmer leader and was known as "Kisan Neta" (Farmer\'s Leader).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

// ─────────────────────────────────────────────────────────────
// 2. IMPORTANT APPOINTMENTS (20 questions) — IDs: sgk_appt_1 to sgk_appt_20
// ─────────────────────────────────────────────────────────────

{id:'sgk_appt_1',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the 26th Governor of the Reserve Bank of India, appointed in December 2024?',o:['Urjit Patel','Shaktikanta Das','Sanjay Malhotra','Raghuram Rajan'],c:2,e:'Sanjay Malhotra became the 26th Governor of the Reserve Bank of India in December 2024, succeeding Shaktikanta Das. He was previously the Revenue Secretary of India.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_2',s:'general_knowledge',t:'appointments',d:'easy',q:'Who was the 25th Governor of the Reserve Bank of India?',o:['Sanjay Malhotra','Urjit Patel','Raghuram Rajan','Shaktikanta Das'],c:3,e:'Shaktikanta Das was the 25th Governor of the Reserve Bank of India from December 2018 to December 2024. He served two terms and oversaw India\'s monetary policy during COVID-19.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_3',s:'general_knowledge',t:'appointments',d:'easy',q:'Who became the President of the World Bank in June 2023?',o:['Jim Yong Kim','David Malpass','Ajay Banga','Kristalina Georgieva'],c:2,e:'Ajay Banga, an Indian-American businessman (former CEO of Mastercard), became the 14th President of the World Bank Group in June 2023. He was nominated by US President Biden.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_4',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the Managing Director of the International Monetary Fund (IMF)?',o:['Christine Lagarde','Ajay Banga','Kristalina Georgieva','Ngozi Okonjo-Iweala'],c:2,e:'Kristalina Georgieva, a Bulgarian economist, has been the Managing Director (MD) of the IMF since October 2019. She was re-appointed for a second term in 2024.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_5',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Director-General of the World Trade Organisation (WTO)?',o:['Roberto Azevêdo','Pascal Lamy','Ngozi Okonjo-Iweala','Mike Moore'],c:2,e:'Ngozi Okonjo-Iweala of Nigeria became the first woman and first African to serve as Director-General of the WTO in March 2021. She was re-appointed for a second term in 2024.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_6',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the first woman Chairperson of SEBI (Securities and Exchange Board of India)?',o:['Shyamala Gopinath','Usha Thorat','Madhabi Puri Buch','Naina Lal Kidwai'],c:2,e:'Madhabi Puri Buch became the first woman Chairperson of SEBI in March 2022. She was previously an executive director at SEBI and has worked in private equity and ICICI Securities.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_7',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Chairman of Insurance Regulatory and Development Authority of India (IRDAI)?',o:['Subhash Chandra Khuntia','T.S. Vijayan','Debasish Panda','N. Kumar'],c:2,e:'Debasish Panda is the Chairman of IRDAI (Insurance Regulatory and Development Authority of India). He is a retired IAS officer who was previously Secretary of the Department of Financial Services.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_appt_8',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the first tribal woman to become President of India?',o:['Pratibha Patil','Sonia Gandhi','Smriti Irani','Droupadi Murmu'],c:3,e:'Droupadi Murmu became the 15th President of India on July 25, 2022, making her the first tribal woman and the second woman (after Pratibha Patil) to hold this office.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_9',s:'general_knowledge',t:'appointments',d:'medium',q:'Who became the Chief Justice of India (CJI) in November 2024?',o:['DY Chandrachud','Sanjiv Khanna','UU Lalit','NV Ramana'],c:1,e:'Justice Sanjiv Khanna became the 51st Chief Justice of India on November 11, 2024, succeeding Justice DY Chandrachud. He presided over several landmark judgments.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_10',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the Secretary-General of the United Nations?',o:['Ban Ki-moon','Kofi Annan','António Guterres','Boutros Boutros-Ghali'],c:2,e:'António Guterres of Portugal has been the Secretary-General of the United Nations since January 2017. He was re-appointed for a second term from January 2022 to December 2026.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_11',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the President of FIFA (Fédération Internationale de Football Association)?',o:['Sepp Blatter','Michel Platini','Gianni Infantino','Lennart Johansson'],c:2,e:'Gianni Infantino of Switzerland/Italy has been the President of FIFA since February 2016. He was re-elected for a third term in March 2023 at the FIFA Congress in Kigali, Rwanda.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_12',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the President of the International Olympic Committee (IOC)?',o:['Jacques Rogge','Juan Antonio Samaranch','Thomas Bach','Avery Brundage'],c:2,e:'Thomas Bach of Germany has been the President of the IOC since 2013. He was re-elected in 2021 for a final term and presided over the Tokyo 2020 and Paris 2024 Olympic Games.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_13',s:'general_knowledge',t:'appointments',d:'medium',q:'Who became the President of the Asian Development Bank (ADB) in 2025?',o:['Masatsugu Asakawa','Takehiko Nakao','Masato Kanda','Jin Liqun'],c:2,e:'Masato Kanda became the President of the Asian Development Bank (ADB) in 2025. He was previously Japan\'s Vice Minister of Finance for International Affairs.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_appt_14',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Vice President of India?',o:['Venkaiah Naidu','Hamid Ansari','Jagdeep Dhankhar','Muppavarapu Venkaiah Naidu'],c:2,e:'Jagdeep Dhankhar became the 14th Vice President of India on August 11, 2022. He was previously the Governor of West Bengal. As VP, he is also the ex-officio Chairman of Rajya Sabha.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_15',s:'general_knowledge',t:'appointments',d:'easy',q:'Who is the Prime Minister of India?',o:['Manmohan Singh','Atal Bihari Vajpayee','Narendra Modi','Rahul Gandhi'],c:2,e:'Narendra Modi has been the Prime Minister of India since May 2014. He was re-elected for a third consecutive term in June 2024 after the 18th General Elections.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_16',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Governor of the State Bank of India (SBI) is not applicable — who is the Chairman of SBI?',o:['Rajnish Kumar','Dinesh Kumar Khara','Challa Sreenivasulu Setty','Arundhati Bhattacharya'],c:2,e:'Challa Sreenivasulu Setty (CS Setty) became the Chairman of the State Bank of India (SBI) in August 2024, succeeding Dinesh Kumar Khara. He is the 27th Chairman of SBI.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_appt_17',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Chief Election Commissioner of India (as of 2024)?',o:['Sunil Arora','Sushil Chandra','Rajiv Kumar','OP Rawat'],c:2,e:'Rajiv Kumar is the 25th Chief Election Commissioner of India, appointed in May 2022. He oversaw the conduct of the 2024 Lok Sabha General Elections.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_appt_18',s:'general_knowledge',t:'appointments',d:'medium',q:'Who became the Comptroller and Auditor General (CAG) of India in 2024?',o:['Girish Chandra Murmu','Rajiv Mehrishi','K.V. Chowdary','Sashi Kant Sharma'],c:0,e:'Girish Chandra Murmu is the Comptroller and Auditor General (CAG) of India, appointed in August 2020. He was previously the first Lieutenant Governor of Jammu & Kashmir (Union Territory).',x:['sbi_mains','rbi_phase1']},

{id:'sgk_appt_19',s:'general_knowledge',t:'appointments',d:'hard',q:'Who is the Director of the Intelligence Bureau (IB) of India (2024)?',o:['Arvind Kumar','Tapan Kumar Deka','Dineshwar Sharma','Rajiv Jain'],c:1,e:'Tapan Kumar Deka is the Director of the Intelligence Bureau (IB) of India. He was appointed in June 2021 and his tenure was extended. IB is India\'s primary internal intelligence agency.',x:['rbi_phase1']},

{id:'sgk_appt_20',s:'general_knowledge',t:'appointments',d:'medium',q:'Who is the Chairperson of the National Bank for Agriculture and Rural Development (NABARD) as of 2024?',o:['Harsh Kumar Bhanwala','GR Chintala','Shaji KV','PC Mohanan'],c:2,e:'Shaji KV is the Chairperson of NABARD (National Bank for Agriculture and Rural Development) as of 2024. NABARD was established in 1982 and is headquartered in Mumbai.',x:['sbi_mains','rbi_phase1']},

// ─────────────────────────────────────────────────────────────
// 3. SPORTS (20 questions) — IDs: sgk_sports_1 to sgk_sports_20
// ─────────────────────────────────────────────────────────────

{id:'sgk_sports_1',s:'general_knowledge',t:'sports',d:'easy',q:'How many medals did India win at the Paris Olympics 2024?',o:['4','5','6','7'],c:2,e:'India won 6 medals at the Paris Olympics 2024: 1 Silver (Neeraj Chopra - Javelin) and 5 Bronze (Manu Bhaker - 10m Air Pistol, Manu Bhaker & Sarabjot Singh - Mixed Team 10m Air Pistol, Swapnil Kusale - 50m Rifle 3 Positions, Men\'s Hockey Team, Aman Sehrawat - Wrestling 57kg).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_2',s:'general_knowledge',t:'sports',d:'easy',q:'Neeraj Chopra won which medal at Paris Olympics 2024?',o:['Gold in Javelin Throw','Silver in Javelin Throw','Bronze in Javelin Throw','Gold in Shot Put'],c:1,e:'Neeraj Chopra won the Silver medal in Men\'s Javelin Throw at the Paris Olympics 2024 with a throw of 89.45 metres. Anderson Peters of Grenada won the Gold. Neeraj had won Gold at Tokyo 2020.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_3',s:'general_knowledge',t:'sports',d:'medium',q:'Manu Bhaker created history at Paris Olympics 2024 by winning two medals. Which events did she medal in?',o:['10m Air Rifle and 25m Pistol','10m Air Pistol and Mixed Team 10m Air Pistol','50m Rifle 3P and 10m Air Pistol','25m Pistol and Mixed Team Pistol'],c:1,e:'Manu Bhaker won Bronze in the Women\'s 10m Air Pistol individual event and another Bronze in the 10m Air Pistol Mixed Team event (with Sarabjot Singh). She became the first Indian to win two medals at a single Olympics.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_4',s:'general_knowledge',t:'sports',d:'medium',q:'Who won the Bronze medal in the 50m Rifle 3 Positions event at Paris Olympics 2024?',o:['Anjum Moudgil','Aishwary Pratap Singh Tomar','Swapnil Kusale','Sanjeev Rajput'],c:2,e:'Swapnil Kusale won the Bronze medal in the Men\'s 50m Rifle 3 Positions event at Paris Olympics 2024. This was India\'s first Olympic medal in this event.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_5',s:'general_knowledge',t:'sports',d:'medium',q:'Aman Sehrawat won a Bronze medal at Paris Olympics 2024 in which sport?',o:['Boxing (60kg)','Judo','Wrestling (Freestyle 57kg)','Weightlifting'],c:2,e:'Aman Sehrawat won the Bronze medal in Men\'s Freestyle Wrestling 57kg at Paris Olympics 2024. At 21, he became the youngest Indian to win an Olympic wrestling medal.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_6',s:'general_knowledge',t:'sports',d:'easy',q:'Which team did India beat to win the ICC T20 World Cup 2024 final?',o:['Pakistan','Australia','England','South Africa'],c:3,e:'India beat South Africa in the final of the ICC T20 World Cup 2024 held in Barbados, West Indies on June 29, 2024, winning by 7 runs. It was India\'s second T20 World Cup title (first in 2007).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_7',s:'general_knowledge',t:'sports',d:'easy',q:'Which team won the ICC ODI World Cup 2023 held in India?',o:['India','England','New Zealand','Australia'],c:3,e:'Australia won the ICC ODI World Cup 2023 on November 19, 2023, defeating India by 6 wickets in the final held at Narendra Modi Stadium, Ahmedabad. Travis Head won the Player of the Match award.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_8',s:'general_knowledge',t:'sports',d:'medium',q:'D Gukesh became the youngest World Chess Champion in December 2024. How old was he?',o:['16 years','17 years','18 years','19 years'],c:2,e:'D Gukesh (Dommaraju Gukesh) became the youngest World Chess Champion at the age of 18 years in December 2024, defeating the reigning champion Ding Liren of China in Singapore.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_9',s:'general_knowledge',t:'sports',d:'medium',q:'India finished in which position at the Asian Games 2023 (Hangzhou, China)?',o:['2nd','3rd','4th','5th'],c:2,e:'India finished 4th at the Asian Games 2023 in Hangzhou, China, winning 107 medals (28 Gold, 38 Silver, 41 Bronze). This was India\'s best-ever performance at the Asian Games.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_10',s:'general_knowledge',t:'sports',d:'medium',q:'Where were the Asian Games 2023 held?',o:['Tokyo, Japan','Jakarta, Indonesia','Hangzhou, China','Kuala Lumpur, Malaysia'],c:2,e:'The 19th Asian Games were held in Hangzhou, China from September 23 to October 8, 2023. China topped the medals tally with 201 Gold medals.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_11',s:'general_knowledge',t:'sports',d:'easy',q:'Where were the Paris Olympics 2024 held?',o:['2023','2024','2025','2022'],c:1,e:'The Paris Summer Olympics 2024 were held from July 26 to August 11, 2024, in Paris, France. It was the third time Paris hosted the Summer Olympics (also 1900 and 1924). USA topped the medals tally.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_12',s:'general_knowledge',t:'sports',d:'medium',q:'India\'s Men\'s Hockey Team won which medal at Paris Olympics 2024?',o:['Gold','Silver','Bronze','Did not medal'],c:2,e:'India\'s Men\'s Hockey Team won the Bronze medal at Paris Olympics 2024, defeating Spain. This was India\'s second consecutive Olympic Bronze in hockey (also Bronze at Tokyo 2020).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_13',s:'general_knowledge',t:'sports',d:'medium',q:'Who won the Wimbledon Men\'s Singles title 2024?',o:['Novak Djokovic','Rafael Nadal','Carlos Alcaraz','Jannik Sinner'],c:2,e:'Carlos Alcaraz of Spain won the Wimbledon Men\'s Singles title 2024, defeating Novak Djokovic in the final. It was his second consecutive Wimbledon title (2023 and 2024).',x:['sbi_prelims','sbi_mains']},

{id:'sgk_sports_14',s:'general_knowledge',t:'sports',d:'medium',q:'Which country won the UEFA Euro 2024 football championship?',o:['France','Germany','England','Spain'],c:3,e:'Spain won the UEFA Euro 2024, defeating England 2-1 in the final held in Berlin, Germany on July 14, 2024. Spain became the first team to win four European Championship titles.',x:['sbi_prelims','sbi_mains']},

{id:'sgk_sports_15',s:'general_knowledge',t:'sports',d:'hard',q:'PV Sindhu, Lakshya Sen and Srikanth Kidambi represent India in which sport?',o:['Table Tennis','Badminton','Squash','Tennis'],c:1,e:'PV Sindhu, Lakshya Sen and Srikanth Kidambi are prominent Indian badminton players. PV Sindhu is a two-time Olympic medallist (Silver 2016, Bronze 2020) and former World Champion.',x:['sbi_prelims','sbi_mains']},

{id:'sgk_sports_16',s:'general_knowledge',t:'sports',d:'medium',q:'Which cricketer scored the fastest century in ODI history?',o:['Virat Kohli','AB de Villiers','Chris Gayle','Glenn Maxwell'],c:1,e:'AB de Villiers (South Africa) scored the fastest ODI century off just 31 balls against West Indies in 2015. He also holds the record for fastest 50 (16 balls) and fastest 150 (64 balls) in ODIs.',x:['sbi_prelims','sbi_mains']},

{id:'sgk_sports_17',s:'general_knowledge',t:'sports',d:'medium',q:'Who hosted the ICC Men\'s T20 World Cup 2024?',o:['India and Sri Lanka','Australia and New Zealand','USA and West Indies','England and Ireland'],c:2,e:'The ICC Men\'s T20 World Cup 2024 was co-hosted by USA and West Indies, held from June 1 to June 29, 2024. It was the first major ICC event hosted (partly) in the United States.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_18',s:'general_knowledge',t:'sports',d:'easy',q:'Rohit Sharma captained India to win which ICC tournament in 2024?',o:['ICC World Test Championship','ICC ODI World Cup','ICC Men\'s T20 World Cup','ICC Champions Trophy'],c:2,e:'Rohit Sharma captained India to win the ICC Men\'s T20 World Cup 2024, defeating South Africa in the final. The tournament was held in USA and West Indies.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_19',s:'general_knowledge',t:'sports',d:'medium',q:'India won how many Gold medals at the Asian Games 2023?',o:['22','25','28','30'],c:2,e:'India won 28 Gold medals at the Asian Games 2023 in Hangzhou, its best-ever Gold medal haul. Overall India won 107 medals (28G-38S-41B), finishing 4th in the overall tally.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_sports_20',s:'general_knowledge',t:'sports',d:'medium',q:'Where will the 2028 Summer Olympics be held?',o:['Brisbane, Australia','Los Angeles, USA','Tokyo, Japan','Mumbai, India'],c:1,e:'The 2028 Summer Olympics (Games of the XXXIV Olympiad) will be held in Los Angeles (LA), USA from July 14 to July 30, 2028. It will be the third time LA hosts the Summer Olympics (1932, 1984, 2028).',x:['sbi_prelims','sbi_mains']},

// ─────────────────────────────────────────────────────────────
// 4. SUMMITS & ORGANISATIONS (20 questions) — IDs: sgk_summit_1 to sgk_summit_20
// ─────────────────────────────────────────────────────────────

{id:'sgk_summit_1',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Which country hosted the G20 Summit in 2023 and what was its theme?',o:['Indonesia — Recover Together','India — Vasudhaiva Kutumbakam','Japan — Hiroshima Vision','Italy — People, Planet, Prosperity'],c:1,e:'India hosted the G20 Summit in New Delhi on September 9-10, 2023 under the theme "Vasudhaiva Kutumbakam" (One Earth, One Family, One Future). The New Delhi Declaration was adopted by consensus.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_2',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Which country hosted the G20 Summit in 2024?',o:['South Africa','Germany','Brazil','China'],c:2,e:'Brazil hosted the G20 Summit in Rio de Janeiro in November 2024. South Africa will host the G20 Summit in 2025.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_3',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'Which country will host the G20 Summit in 2025?',o:['South Africa','Canada','France','Indonesia'],c:0,e:'South Africa will host the G20 Summit in 2025. The G20 presidency rotates among member countries. South Africa is the first African country to hold the G20 presidency.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_4',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'Where was the SCO (Shanghai Cooperation Organisation) Summit 2024 held?',o:['Moscow, Russia','Beijing, China','Astana, Kazakhstan','New Delhi, India'],c:2,e:'The SCO Summit 2024 was held in Astana, Kazakhstan in July 2024. Belarus was admitted as the newest member. India chaired the SCO Summit in 2023 (virtual format).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_5',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'How many new countries joined BRICS in January 2024?',o:['4','5','6','3'],c:1,e:'Five new countries officially joined BRICS on January 1, 2024: Egypt, Ethiopia, Iran, Saudi Arabia and the United Arab Emirates (UAE). Argentina was also invited but declined to join.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_6',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'What are the Sustainable Development Goals (SDGs) target year set by the United Nations?',o:['2025','2030','2035','2050'],c:1,e:'The 17 Sustainable Development Goals (SDGs) were adopted by all UN member states in 2015 as part of the 2030 Agenda for Sustainable Development. The target year for achieving all SDGs is 2030.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_7',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'How many Sustainable Development Goals (SDGs) were adopted by the UN?',o:['15','16','17','18'],c:2,e:'The United Nations adopted 17 Sustainable Development Goals (SDGs) in September 2015 as part of the 2030 Agenda for Sustainable Development, replacing the Millennium Development Goals (MDGs).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_8',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Where is the headquarters of the World Health Organisation (WHO)?',o:['New York, USA','Washington DC, USA','Geneva, Switzerland','Vienna, Austria'],c:2,e:'The World Health Organisation (WHO) is headquartered in Geneva, Switzerland. WHO was established in 1948 and Tedros Adhanom Ghebreyesus of Ethiopia is the current Director-General.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_9',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Where is the headquarters of UNICEF (United Nations Children\'s Fund)?',o:['Geneva','Paris','Vienna','New York'],c:3,e:'UNICEF (United Nations Children\'s Fund) is headquartered in New York City, USA. It was established in 1946 to provide humanitarian and developmental aid to children worldwide.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_10',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Where are the headquarters of the World Bank and IMF located?',o:['New York, USA','Geneva, Switzerland','Washington DC, USA','London, UK'],c:2,e:'Both the World Bank and the International Monetary Fund (IMF) are headquartered in Washington DC, USA. They were established through the Bretton Woods Agreement in 1944.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_11',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'Where is UNESCO (UN Educational, Scientific and Cultural Organisation) headquartered?',o:['London','Paris','Brussels','Geneva'],c:1,e:'UNESCO is headquartered in Paris, France. It was established in 1945 and promotes international collaboration in education, science, culture and communication.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_12',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'Where is the Food and Agriculture Organisation (FAO) headquartered?',o:['Geneva','New York','Rome','Brussels'],c:2,e:'The Food and Agriculture Organisation (FAO) of the United Nations is headquartered in Rome, Italy. It was established in 1945 to defeat hunger and improve nutrition worldwide.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_13',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'Where is the International Labour Organisation (ILO) headquartered?',o:['Geneva, Switzerland','New York, USA','Paris, France','Vienna, Austria'],c:0,e:'The International Labour Organisation (ILO) is headquartered in Geneva, Switzerland. It is the only tripartite UN agency that brings together governments, employers and workers. Founded in 1919.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_14',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'What is the headquarters of SAARC (South Asian Association for Regional Cooperation)?',o:['New Delhi, India','Dhaka, Bangladesh','Kathmandu, Nepal','Islamabad, Pakistan'],c:2,e:'The SAARC Secretariat is located in Kathmandu, Nepal. SAARC was established in 1985 and has 8 member states: Afghanistan, Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan and Sri Lanka.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_15',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'Where is the headquarters of BIMSTEC (Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation)?',o:['New Delhi','Bangkok, Thailand','Dhaka, Bangladesh','Colombo, Sri Lanka'],c:2,e:'BIMSTEC Secretariat is headquartered in Dhaka, Bangladesh. BIMSTEC has 7 members: Bangladesh, Bhutan, India, Myanmar, Nepal, Sri Lanka and Thailand. It was established in 1997.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_16',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'The African Union (AU) has how many member states?',o:['48','50','54','55'],c:3,e:'The African Union (AU) has 55 member states, making it the only continental organisation with all countries on the continent as members (including Morocco which rejoined in 2017). AU HQ is in Addis Ababa, Ethiopia.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_summit_17',s:'general_knowledge',t:'summits_organisations',d:'easy',q:'The theme of India\'s G20 Presidency 2023 "Vasudhaiva Kutumbakam" is taken from which ancient text?',o:['Bhagavad Gita','Upanishads','Maha Upanishad','Arthashastra'],c:2,e:'"Vasudhaiva Kutumbakam" (The World is One Family) is taken from the Maha Upanishad (an ancient Sanskrit text). India\'s G20 logo featured a lotus with the Earth globe and this motto.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_18',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'The African Union joined the G20 as a permanent member in which year?',o:['2022','2023','2024','2025'],c:1,e:'The African Union (AU) joined the G20 as a permanent member during India\'s G20 Presidency in September 2023, at the New Delhi Summit. This expanded G20 from 20 to 21 permanent members.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_19',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'ASEAN (Association of Southeast Asian Nations) has how many member countries?',o:['8','9','10','11'],c:2,e:'ASEAN has 10 member countries: Brunei, Cambodia, Indonesia, Laos, Malaysia, Myanmar, Philippines, Singapore, Thailand and Vietnam. ASEAN was established in 1967 and is headquartered in Jakarta, Indonesia.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_summit_20',s:'general_knowledge',t:'summits_organisations',d:'medium',q:'The original BRICS countries before 2024 expansion were Brazil, Russia, India, China and which other country?',o:['Saudi Arabia','South Africa','Egypt','UAE'],c:1,e:'The original 5 BRICS nations were Brazil, Russia, India, China and South Africa. South Africa joined in 2010, expanding the group from BRIC to BRICS. From January 2024, five more countries joined.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

// ─────────────────────────────────────────────────────────────
// 5. IMPORTANT SCHEMES & POLICIES (15 questions) — IDs: sgk_scheme_1 to sgk_scheme_15
// ─────────────────────────────────────────────────────────────

{id:'sgk_scheme_1',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'PM Vishwakarma Yojana was launched in 2023 to benefit which category of people?',o:['Farmers','Gig workers','Traditional artisans and craftspeople','Women entrepreneurs'],c:2,e:'PM Vishwakarma Yojana was launched on September 17, 2023 (Vishwakarma Jayanti). It supports traditional artisans and craftspeople (18 trades) with training, tools, credit up to ₹3 lakh at 5% interest.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_2',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'Under PM Surya Ghar Muft Bijli Yojana (2024), how many free electricity units per month does the scheme aim to provide?',o:['100 units','200 units','300 units','500 units'],c:2,e:'PM Surya Ghar Muft Bijli Yojana, launched in February 2024, aims to provide up to 300 units of free electricity per month to 1 crore households through rooftop solar installations.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_3',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'Under PM Kisan Samman Nidhi, how much financial assistance is provided to farmers per year?',o:['₹4,000','₹5,000','₹6,000','₹8,000'],c:2,e:'PM Kisan Samman Nidhi provides ₹6,000 per year (₹2,000 every four months) directly to small and marginal farmers\' bank accounts through DBT (Direct Benefit Transfer). Launched in 2019.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_4',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'Ayushman Bharat - PM-JAY provides health insurance coverage of how much per family per year?',o:['₹3 lakh','₹5 lakh','₹7 lakh','₹10 lakh'],c:1,e:'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY) provides health coverage of ₹5 lakh per family per year for secondary and tertiary hospitalisation. It is the world\'s largest government-funded health insurance scheme.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_5',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'Digital India programme was launched in which year?',o:['2013','2014','2015','2016'],c:2,e:'Digital India programme was launched on July 1, 2015 by PM Narendra Modi. Its vision is to transform India into a digitally empowered society and knowledge economy. Key pillars include broadband infrastructure, digital literacy and e-Governance.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_6',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'Make in India initiative was launched in which year?',o:['2013','2014','2015','2016'],c:1,e:'Make in India was launched on September 25, 2014 by PM Narendra Modi to encourage multinational and domestic companies to manufacture in India. The logo is a lion made of cogs (representing manufacturing).',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_7',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'How many cities were selected under the Smart Cities Mission launched in 2015?',o:['50 cities','75 cities','100 cities','120 cities'],c:2,e:'100 cities were selected under the Smart Cities Mission launched in June 2015. The mission aims to develop sustainable and inclusive cities providing core infrastructure and a clean and sustainable environment.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_8',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'Stand Up India scheme was launched to provide bank loans to which groups?',o:['Small farmers and rural poor','SC/ST entrepreneurs and women entrepreneurs','Students and youth','MSMEs and startups'],c:1,e:'Stand Up India scheme was launched on April 5, 2016 to promote entrepreneurship among SC/ST and women borrowers. It provides loans between ₹10 lakh and ₹1 crore for setting up greenfield enterprises.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_9',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'Startup India initiative was launched in which year?',o:['2014','2015','2016','2017'],c:2,e:'Startup India was launched on January 16, 2016 by PM Narendra Modi to build a strong ecosystem for startups, drive sustainable economic growth and generate large-scale employment opportunities.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_10',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'The concept of "One Nation One Election" refers to holding simultaneous elections to which bodies?',o:['Lok Sabha and all State Assemblies','Lok Sabha, State Assemblies and local bodies','Lok Sabha and Rajya Sabha','All Municipal and Panchayat elections'],c:0,e:'One Nation One Election proposes holding simultaneous elections to the Lok Sabha and all State Legislative Assemblies. The Ram Nath Kovind-led committee submitted its report in 2024 recommending a two-phase synchronisation.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_11',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'PM Jan Dhan Yojana (PMJDY) was launched primarily to achieve which goal?',o:['Skill development','Financial inclusion — bank account for every household','Health insurance for all','Rural electrification'],c:1,e:'PM Jan Dhan Yojana (PMJDY) was launched on August 28, 2014 to ensure access to financial services (banking accounts, remittances, credit, insurance, pension) for excluded sections of society.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_12',s:'general_knowledge',t:'schemes_policies',d:'easy',q:'Pradhan Mantri Mudra Yojana (PMMY) provides loans up to how much for non-corporate non-farm small/micro enterprises?',o:['₹5 lakh','₹10 lakh','₹20 lakh','₹50 lakh'],c:1,e:'PM Mudra Yojana provides loans up to ₹10 lakh under three categories: Shishu (up to ₹50,000), Kishore (₹50,001 to ₹5 lakh), and Tarun (₹5 lakh to ₹10 lakh) for small businesses.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_13',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'Atal Pension Yojana (APY) is regulated by which body?',o:['SEBI','IRDAI','PFRDA','RBI'],c:2,e:'Atal Pension Yojana (APY) is regulated by the Pension Fund Regulatory and Development Authority (PFRDA). Launched in 2015, it provides a guaranteed minimum pension of ₹1,000 to ₹5,000 per month after age 60, mainly for unorganised sector workers.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_14',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'UDAN (Ude Desh ka Aam Nagrik) scheme is related to which sector?',o:['Rural roads','Regional air connectivity','Inland waterways','Affordable housing'],c:1,e:'UDAN (Ude Desh ka Aam Nagrik) is a regional connectivity scheme for aviation, launched in 2016 under the National Civil Aviation Policy. It aims to make air travel affordable for common citizens and boost regional airports.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_scheme_15',s:'general_knowledge',t:'schemes_policies',d:'medium',q:'The Jal Jeevan Mission aims to provide tap water connection to how many rural households by 2024?',o:['10 crore','15 crore','19.27 crore (every rural household)','25 crore'],c:2,e:'Jal Jeevan Mission (JJM), launched in 2019, aims to provide functional household tap connections (FHTC) to every rural household (19.27 crore) by 2024. By 2024, over 14 crore connections were provided.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

// ─────────────────────────────────────────────────────────────
// 6. SCIENCE & TECHNOLOGY (10 questions) — IDs: sgk_tech_1 to sgk_tech_10
// ─────────────────────────────────────────────────────────────

{id:'sgk_tech_1',s:'general_knowledge',t:'science_technology',d:'easy',q:'Chandrayaan-3 landed near the Moon\'s south pole on which date?',o:['August 14, 2023','August 23, 2023','September 2, 2023','July 14, 2023'],c:1,e:'Chandrayaan-3\'s Vikram lander successfully soft-landed near the Moon\'s south pole on August 23, 2023, making India the first country to achieve a soft landing near the lunar south pole. The Pragyan rover was deployed from the lander.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_2',s:'general_knowledge',t:'science_technology',d:'easy',q:'What were the names of the lander and rover of Chandrayaan-3?',o:['Pragyan (lander) and Vikram (rover)','Vikram (lander) and Pragyan (rover)','Shakti (lander) and Prayas (rover)','Akash (lander) and Bhumi (rover)'],c:1,e:'Chandrayaan-3 consisted of Vikram lander and Pragyan rover. Vikram is named after Dr Vikram Sarabhai (father of Indian space programme) and Pragyan means "Wisdom" in Sanskrit.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_3',s:'general_knowledge',t:'science_technology',d:'easy',q:'Aditya-L1, India\'s first solar observation mission, was launched on which date?',o:['August 23, 2023','September 2, 2023','October 15, 2023','November 5, 2023'],c:1,e:'Aditya-L1, India\'s first dedicated solar observation mission, was launched on September 2, 2023 by ISRO. It studies the Sun from the Lagrange Point 1 (L1), located 1.5 million km from Earth.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_4',s:'general_knowledge',t:'science_technology',d:'medium',q:'Aditya-L1 studies the Sun from which Lagrange point?',o:['L1','L2','L4','L5'],c:0,e:'Aditya-L1 operates from the Sun-Earth Lagrange Point 1 (L1), which is at a distance of about 1.5 million km from Earth. From L1, the satellite can observe the Sun continuously without any occultation.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_5',s:'general_knowledge',t:'science_technology',d:'easy',q:'UPI (Unified Payments Interface) was developed and is managed by which organisation?',o:['Reserve Bank of India (RBI)','State Bank of India (SBI)','NPCI (National Payments Corporation of India)','Ministry of Finance'],c:2,e:'UPI was developed and is managed by the National Payments Corporation of India (NPCI). Launched in April 2016, UPI has become the world\'s largest real-time payment system by volume of transactions.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_6',s:'general_knowledge',t:'science_technology',d:'easy',q:'5G services were commercially launched in India in which month and year?',o:['March 2022','October 2022','January 2023','June 2023'],c:1,e:'5G services were officially launched in India on October 1, 2022 by PM Narendra Modi at the India Mobile Congress in New Delhi. Reliance Jio and Airtel were the first to launch 5G services.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_7',s:'general_knowledge',t:'science_technology',d:'medium',q:'India became the 4th country in the world to achieve a soft landing on the Moon with Chandrayaan-3. Which countries achieved it before India?',o:['USA, Russia, China','USA, Russia, Japan','USA, China, Japan','Russia, USA, European Union'],c:0,e:'Before India, only USA (1966 - Surveyor 1), USSR/Russia (1966 - Luna 9) and China (2013 - Chang\'e 3) had achieved soft landings on the Moon. India became the 4th in 2023.',x:['sbi_prelims','sbi_mains','rbi_phase1']},

{id:'sgk_tech_8',s:'general_knowledge',t:'science_technology',d:'medium',q:'ISRO\'s mission to study the Earth\'s magnetic field and ionosphere is called:',o:['Aditya-L1','INSAT-3DS','IRNSS (NavIC)','EOS-06'],c:2,e:'NavIC (Navigation with Indian Constellation), also known as IRNSS, is India\'s independent regional navigation satellite system developed by ISRO. It provides position accuracy of better than 20 metres over India and surrounding region up to 1500 km.',x:['sbi_mains','rbi_phase1']},

{id:'sgk_tech_9',s:'general_knowledge',t:'science_technology',d:'medium',q:'India\'s nuclear triad capability means India can launch nuclear weapons from which three platforms?',o:['Land, Air and Sea','Land, Air and Space','Air, Sea and Underground','Land, Submarine and Satellite'],c:0,e:'India\'s nuclear triad means the capability to launch nuclear weapons from land (Agni missiles), air (Mirage 2000, Jaguar, Rafale) and sea (INS Arihant submarine - K-15/K-4 missiles), ensuring second-strike capability.',x:['rbi_phase1']},

{id:'sgk_tech_10',s:'general_knowledge',t:'science_technology',d:'medium',q:'The Gaganyaan mission by ISRO aims to send how many astronauts to space and for how many days?',o:['2 astronauts for 3 days','3 astronauts for 3 days','4 astronauts for 7 days','2 astronauts for 7 days'],c:1,e:'Gaganyaan is India\'s first crewed orbital spacecraft mission by ISRO, planned to send 3 Indian astronauts (Gagannauts) to Low Earth Orbit for a 3-day mission. It will make India the 4th country to send humans to space independently.',x:['sbi_prelims','sbi_mains','rbi_phase1']}
);

// Total: adds ~105 questions to Q[]
