// ═══ VOCABULARY BANK ═══
const VOCAB_BANK={
banking_terms:{
title:'Essential Banking & Finance Vocabulary',
words:[
{word:'Accrual',meaning:'Recognition of revenue/expense when earned/incurred, not when cash received/paid',usage:'Banks use accrual accounting for interest income.',antonym:'Cash basis accounting'},
{word:'Adjudication',meaning:'Legal process of resolving a dispute by judge or arbitrator',usage:'Loan default cases go for adjudication under DRT.',antonym:'Negotiation'},
{word:'Amortization',meaning:'Gradual repayment of a loan through periodic installments covering both principal and interest',usage:'Home loan amortization schedule shows how EMI splits between principal and interest over time.',antonym:'Bullet repayment (pay all at end)'},
{word:'Annuity',meaning:'Series of equal payments made at regular intervals over time',usage:'Life insurance annuity provides monthly income post-retirement.',antonym:'Lump sum'},
{word:'Arbitrage',meaning:'Simultaneous purchase and sale of same asset in different markets to profit from price difference',usage:'Currency arbitrage exploits exchange rate differences across forex markets.',antonym:'Speculation'},
{word:'Asset Liability Mismatch',meaning:'When maturity/rate profile of assets doesn\'t match liabilities, creating liquidity/interest rate risk',usage:'Banks borrowing short-term and lending long-term face ALM risk.',antonym:'Perfectly matched book'},
{word:'Asymmetric Information',meaning:'Situation where one party has more/better information than another in a transaction',usage:'Adverse selection in credit markets: borrowers know more about their creditworthiness than banks.',antonym:'Perfect information'},
{word:'Bear Market',meaning:'Market condition where securities prices fall 20%+ from recent highs over sustained period',usage:'Indian equities entered bear market during COVID-19 in March 2020.',antonym:'Bull market'},
{word:'Benchmark Rate',meaning:'Reference interest rate used to set prices of other financial instruments',usage:'MCLR is the benchmark for most bank loans; repo rate is the policy benchmark.',antonym:'Contractual/fixed rate'},
{word:'Bridge Loan',meaning:'Short-term loan to bridge financing gap until permanent financing arranged',usage:'Developer took a bridge loan between construction and final mortgage arrangement.',antonym:'Term loan'},
{word:'Brownfield Investment',meaning:'Investment in existing facilities/plant, typically through acquisition or expansion',usage:'FDI through acquiring an existing Indian company = brownfield investment.',antonym:'Greenfield investment (new facility from scratch)'},
{word:'Callable Bond',meaning:'Bond that issuer can redeem before maturity at specified price',usage:'Government may issue callable bonds to refinance at lower rates if interest rates fall.',antonym:'Non-callable (bullet) bond'},
{word:'Capitalization',meaning:'1) Total value of company\'s outstanding securities. 2) Recording expense as an asset to be amortized',usage:'SBI\'s market capitalization exceeded ₹7 lakh crore in 2024.',antonym:'Expensing (writing off immediately)'},
{word:'Collateral',meaning:'Asset pledged by borrower as security for a loan',usage:'Home serves as collateral for a home loan; bank can seize it if borrower defaults.',antonym:'Unsecured loan'},
{word:'Contagion',meaning:'Spread of financial distress from one institution/market to others',usage:'2008 financial crisis showed how contagion spread from US subprime to global markets.',antonym:'Containment/Ring-fencing'},
{word:'Convertible Bond',meaning:'Bond that can be converted into equity shares at bondholder\'s option at predetermined price',usage:'Startup issued convertible bonds to early investors who later converted to equity.',antonym:'Non-convertible debenture (NCD)'},
{word:'Covenant',meaning:'Condition in loan agreement requiring borrower to meet certain requirements',usage:'Loan covenant required borrower to maintain debt-equity ratio below 2:1.',antonym:'Unconditional loan'},
{word:'Crowding Out',meaning:'Government borrowing increases interest rates, reducing private sector investment',usage:'High fiscal deficit causes crowding out of private investment.',antonym:'Crowding in (expansionary effect)'},
{word:'Custodian',meaning:'Financial institution that holds/safeguards financial assets on behalf of others',usage:'SEBI-registered custodians hold securities for FPIs and mutual funds.',antonym:'Outright owner'},
{word:'Delinquency',meaning:'Failure to make scheduled loan payments by the due date',usage:'Loan becomes delinquent when first EMI is missed; becomes NPA after 90 days.',antonym:'Current/Performing loan'},
{word:'Denomination',meaning:'Face value of a currency note, bond, or other financial instrument',usage:'Government T-bills are issued in denomination of ₹100.',antonym:'Actual market value'},
{word:'Derivatives',meaning:'Financial instruments whose value derives from underlying asset (stock, bond, currency, commodity)',usage:'Interest rate swaps, currency futures, and options are common banking derivatives.',antonym:'Underlying asset itself'},
{word:'Disintermediation',meaning:'Bypassing financial intermediaries (banks) to access capital markets directly',usage:'Large corporations issue commercial paper directly, disintermediating banks.',antonym:'Financial intermediation'},
{word:'Dividend',meaning:'Portion of company\'s profits distributed to shareholders',usage:'SBI declared final dividend of ₹13.70 per share for FY24.',antonym:'Retained earnings'},
{word:'Due Diligence',meaning:'Comprehensive investigation/audit before executing a financial transaction',usage:'Bank conducts due diligence on project viability before sanctioning term loan.',antonym:'Blind faith investment'},
{word:'Duration',meaning:'Measure of bond\'s sensitivity to interest rate changes (weighted average time to receive cash flows)',usage:'Long-duration bonds are more sensitive to interest rate changes.',antonym:'Short maturity/duration'},
{word:'Encumbrance',meaning:'Claim or lien on an asset that limits its transfer',usage:'Mortgaged property has encumbrance that prevents its free sale.',antonym:'Unencumbered asset'},
{word:'Equity',meaning:'1) Shareholders\' ownership stake in company. 2) Residual interest after liabilities deducted from assets',usage:'Bank\'s equity capital includes paid-up capital + reserves + retained earnings.',antonym:'Debt/Liability'},
{word:'Escrow',meaning:'Financial arrangement where third party holds funds/assets until conditions are met',usage:'Home buyer deposits earnest money in escrow until property transfer conditions fulfilled.',antonym:'Direct payment'},
{word:'Factoring',meaning:'Financial service where company sells its receivables to third party at discount for immediate cash',usage:'MSME sold ₹50 lakh trade receivables to factoring company at 3% discount.',antonym:'Holding receivables till maturity'},
{word:'Fiduciary',meaning:'Person/institution acting in trust on behalf of another, obligated to act in their best interest',usage:'Banks act as fiduciaries for depositors\' money.',antonym:'Arm\'s length transaction'},
{word:'Floater',meaning:'Bond/security with variable (floating) interest rate, typically linked to benchmark rate',usage:'Floating rate bonds adjust every 6 months based on RBI repo rate.',antonym:'Fixed rate bond'},
{word:'Forbearance',meaning:'Allowing defaulting borrower temporary relief from full enforcement of loan terms',usage:'During COVID, RBI permitted loan forbearance through moratorium.',antonym:'Strict enforcement'},
{word:'Forfeiture',meaning:'Loss of rights/assets as consequence of failure to fulfill obligations',usage:'Forfeiture of collateral when borrower cannot repay under SARFAESI.',antonym:'Release of security'},
{word:'Franchise Value',meaning:'Intangible value from a bank\'s charter, customer base, brand, and regulatory license',usage:'A well-established bank\'s franchise value exceeds its book value significantly.',antonym:'Book/liquidation value only'},
{word:'Fungibility',meaning:'Property of goods/financial instruments where individual units are interchangeable',usage:'Money is fungible — one ₹100 note is equivalent to any other ₹100 note.',antonym:'Non-fungible (unique) asset'},
{word:'Garnishment',meaning:'Legal order directing third party holding debtor\'s funds to pay creditor',usage:'Bank account garnishment forces bank to transfer depositor\'s funds to judgment creditor.',antonym:'Voluntary payment'},
{word:'Gearing',meaning:'Ratio of debt to equity in a company\'s financial structure (UK term for leverage)',usage:'High gearing makes companies more vulnerable to interest rate increases.',antonym:'Low leverage/equity-funded'},
{word:'Gilt',meaning:'UK/India term for government securities (gilts = government bonds)',usage:'RBI uses gilts (G-secs) as collateral for repo operations.',antonym:'Corporate bonds'},
{word:'Goodwill',meaning:'Intangible asset representing value of business over its net assets, paid when one company acquires another',usage:'When bank A acquires bank B paying premium over net assets, excess is goodwill.',antonym:'Tangible assets'},
{word:'Guarantor',meaning:'Person/entity that guarantees another\'s debt/obligation',usage:'First-generation entrepreneur needed guarantor for MSME loan before MUDRA era.',antonym:'Principal borrower'},
{word:'Haircut',meaning:'Percentage reduction from market value of collateral for calculating loan value',usage:'RBI applies haircut on corporate bonds accepted as collateral in repo operations.',antonym:'Full value collateral'},
{word:'Hedge',meaning:'Investment to reduce risk of adverse price movements in an asset',usage:'Exporter hedges forex risk by selling forward contracts on expected dollar receipts.',antonym:'Speculation'},
{word:'Herd Behavior',meaning:'Tendency of investors to follow and mimic actions of larger group',usage:'Herd behavior amplifies market crashes as all investors sell simultaneously.',antonym:'Contrarian investing'},
{word:'Hypothecation',meaning:'Pledging asset as loan security without transferring possession or ownership',usage:'Car loan: vehicle hypothecated to bank but borrower keeps possession and use.',antonym:'Mortgage (transfers title) or pledge (transfers possession)'},
{word:'Illiquid',meaning:'Asset that cannot be quickly converted to cash without significant loss in value',usage:'Real estate is illiquid compared to listed equities.',antonym:'Liquid asset'},
{word:'Impairment',meaning:'Reduction in recoverable value of asset below its carrying value on books',usage:'Bank recognizes loan impairment when expected recovery falls below book value.',antonym:'Appreciation/enhancement'},
{word:'Indenture',meaning:'Formal legal agreement, especially bond indenture specifying terms and conditions',usage:'Bond indenture details coupon rate, maturity, covenants, and default clauses.',antonym:'Verbal agreement'},
{word:'Insider Trading',meaning:'Trading based on material, non-public information about a company',usage:'SEBI penalizes insider trading with fines up to ₹25 crore or 3× profits made.',antonym:'Fair market trading'},
{word:'Insolvency',meaning:'Inability to meet financial obligations as they become due',usage:'When a company becomes insolvent, IBC 2016 provides resolution framework.',antonym:'Solvency'},
{word:'Intermediation',meaning:'Process of channeling funds from savers to borrowers through financial institutions',usage:'Banks perform financial intermediation — taking deposits and making loans.',antonym:'Disintermediation'},
{word:'Intrinsic Value',meaning:'Actual underlying value of an asset based on fundamentals, not market price',usage:'Value investors seek stocks trading below their intrinsic value.',antonym:'Market/speculative value'},
{word:'Leverage',meaning:'Use of borrowed capital to increase potential return on investment (and risk)',usage:'Bank\'s leverage = Total assets / Equity capital. High leverage amplifies gains and losses.',antonym:'Unlevered/equity-only'},
{word:'Liquidity',meaning:'Ease with which asset can be converted to cash without significant price impact',usage:'Government securities are highly liquid; real estate is illiquid.',antonym:'Illiquidity'},
{word:'Liquidation',meaning:'Winding up a company by converting all assets to cash to pay creditors',usage:'IBC provides for liquidation of company if resolution fails within 270 days.',antonym:'Going concern'},
{word:'Mandate',meaning:'Authority given to one party to act on behalf of another',usage:'Investment mandate specifies asset classes and limits for fund manager.',antonym:'Self-directed'},
{word:'Margining',meaning:'Requiring additional collateral when existing margin falls below maintenance level',usage:'Stock brokers issue margin calls when portfolio value falls.',antonym:'No margin requirement'},
{word:'Mark-to-Market',meaning:'Valuing securities at current market price rather than historical cost',usage:'Trading portfolio must be marked-to-market daily; HTM portfolio is at cost.',antonym:'Historical cost accounting'},
{word:'Maturity Transformation',meaning:'Banks borrowing short-term (deposits) and lending long-term (loans), profiting from rate difference',usage:'Core banking function of maturity transformation creates liquidity risk.',antonym:'Matched book (same maturity on both sides)'},
{word:'Moral Hazard',meaning:'Tendency to take more risk when protected from consequences (like by insurance or government guarantee)',usage:'Too-big-to-fail banks exhibit moral hazard — taking risks knowing government will bail them out.',antonym:'Full accountability'},
{word:'Moratorium',meaning:'Temporary suspension of legally required obligation (like loan repayment)',usage:'COVID moratorium allowed borrowers to defer EMIs without NPA classification.',antonym:'Regular repayment schedule'},
{word:'Netting',meaning:'Process of offsetting gains/losses or claims from multiple contracts to arrive at single net amount',usage:'Bilateral netting reduces credit exposure in derivatives markets.',antonym:'Gross settlement'},
{word:'Non-Recourse Loan',meaning:'Loan where lender\'s recovery limited to specific collateral; borrower personally not liable',usage:'Infrastructure project finance often on non-recourse basis (repaid from project cash flows only).',antonym:'Full recourse loan'},
{word:'Open Position',meaning:'Exposure in currency, securities, or derivatives that has not been hedged or closed',usage:'Bank\'s open forex position creates exchange rate risk.',antonym:'Closed/hedged position'},
{word:'Origination',meaning:'Process of creating new loan or mortgage from application through documentation',usage:'Digital lending platforms reduced loan origination time from weeks to minutes.',antonym:'Servicing (managing existing loan)'},
{word:'Overcollateralization',meaning:'Providing collateral worth more than the loan amount as additional protection for lender',usage:'Securitization often uses overcollateralization as credit enhancement.',antonym:'Undercollateralization'},
{word:'Par Value',meaning:'Face value of security (bond or share) as stated on the certificate',usage:'Bond paying 8% coupon on ₹1000 par value pays ₹80/year.',antonym:'Market value'},
{word:'Pledge',meaning:'Handing over possession of asset to lender as security while ownership remains with borrower',usage:'Gold loan: gold pledged to bank; ownership stays with borrower.',antonym:'Hypothecation (no possession transfer)'},
{word:'Portfolio',meaning:'Collection of financial investments held by individual or institution',usage:'Bank\'s loan portfolio comprises all outstanding advances across sectors.',antonym:'Single concentrated investment'},
{word:'Provisioning',meaning:'Setting aside funds in income statement for anticipated losses on loans',usage:'Banks must provision at least 25% for sub-standard NPAs, 100% for loss assets.',antonym:'No provision (optimistic)'},
{word:'Proxy',meaning:'1) Authority to represent shareholder at company meeting. 2) Approximate measure',usage:'Inflation is often used as a proxy for the cost-of-living pressure on households.',antonym:'Direct measurement'},
{word:'Rescheduling',meaning:'Extending repayment period of a loan to reduce periodic payment amount',usage:'Farmer\'s loan rescheduled to allow repayment in smaller amounts over longer period.',antonym:'Pre-payment'},
{word:'Residual Risk',meaning:'Risk remaining after application of all risk mitigation measures',usage:'Even with insurance and collateral, bank faces residual credit risk.',antonym:'Fully mitigated risk'},
{word:'Restructuring',meaning:'Changing terms of a loan (rate, period, security) when borrower faces genuine difficulty',usage:'CDR (Corporate Debt Restructuring) helped banks restructure loans to large corporates.',antonym:'Normal repayment'},
{word:'Rollover',meaning:'Extending or renewing a maturing loan or investment',usage:'Short-term CPs are rolled over repeatedly to fund long-term needs — creates liquidity risk.',antonym:'Repayment at maturity'},
{word:'Securitization',meaning:'Converting illiquid assets (loans) into tradeable securities sold to investors',usage:'Mortgage-Backed Securities: banks pool home loans and sell to MF/insurance investors.',antonym:'Balance sheet retention'},
{word:'Settlement',meaning:'Completion of a financial transaction with exchange of payment and securities',usage:'T+1 settlement in Indian equity markets — completed next trading day.',antonym:'Non-settlement/default'},
{word:'Spread',meaning:'Difference between two rates or prices (interest rate spread, bid-ask spread)',usage:'Net Interest Margin = spread between lending rate and deposit rate.',antonym:'Single price/rate'},
{word:'Subordinated Debt',meaning:'Debt that ranks below senior debt in priority of claims in case of liquidation',usage:'Tier 2 capital includes subordinated debt instruments.',antonym:'Senior/secured debt'},
{word:'Syndication',meaning:'Group of banks jointly providing a large loan to a single borrower',usage:'NTPC\'s ₹10,000 crore loan was syndicated among 8 banks led by SBI.',antonym:'Bilateral loan'},
{word:'Tenor',meaning:'Period from issuance to maturity of a financial instrument',usage:'Commercial papers have tenor of 7 days to 1 year.',antonym:'Perpetual instrument'},
{word:'Tranche',meaning:'One of several portions or segments of a loan or bond offering',usage:'Infrastructure bond issued in three tranches: ₹500 Cr in Year 1, ₹800 Cr Year 2, ₹700 Cr Year 3.',antonym:'Single lump sum'},
{word:'Underwriting',meaning:'Process of evaluating and accepting financial risk for a fee (insurance, securities issuance)',usage:'Investment bank underwriting an IPO guarantees to buy unsold shares.',antonym:'Best efforts basis (no guarantee)'},
{word:'Valuation',meaning:'Process of determining present value of asset or company',usage:'Bank valuation uses book value, P/E multiple, and adjusted net asset value methods.',antonym:'Historical cost'},
{word:'Velocity of Money',meaning:'Rate at which money circulates in economy — how frequently a unit of currency is used in transactions',usage:'High velocity indicates active economy. Digital payments increase velocity.',antonym:'Hoarding (low velocity)'},
{word:'Volatility',meaning:'Measure of variation in price/return of financial instrument over time',usage:'VIX (Volatility Index) measures expected market volatility. High VIX = fear.',antonym:'Stability'},
{word:'Write-off',meaning:'Removing uncollectable asset from books as a loss',usage:'Banks write off fully provisioned NPAs; legal recovery efforts may continue.',antonym:'Recovery'}
]},
english_vocabulary:{
title:'High-Frequency Words for Bank Exams',
words:[
{word:'Aberration',meaning:'Deviation from what is normal or expected',antonym:'Conformity',usage:'The brief inflation spike was an aberration in the otherwise stable price environment.'},
{word:'Abscond',meaning:'Leave hurriedly and secretly, typically to escape legal consequences',antonym:'Remain/surrender',usage:'The promoter absconded with investor funds, prompting Sebi action.'},
{word:'Acrimony',meaning:'Bitterness or ill feeling',antonym:'Harmony',usage:'The board meeting ended in acrimony over the NPA classification.'},
{word:'Adroit',meaning:'Clever or skillful in using the hands or mind',antonym:'Clumsy/inept',usage:'The negotiator was adroit at finding middle ground between banks and borrowers.'},
{word:'Ambiguous',meaning:'Open to more than one interpretation; unclear',antonym:'Clear/unambiguous',usage:'The ambiguous contract clause led to litigation.'},
{word:'Ameliorate',meaning:'Make (something bad or unsatisfactory) better; improve',antonym:'Worsen/aggravate',usage:'RBI\'s measures ameliorated the liquidity crisis in the NBFC sector.'},
{word:'Anachronism',meaning:'A thing out of its proper time period; belonging to an earlier time',antonym:'Contemporary',usage:'Requiring physical presence for KYC is an anachronism in the digital age.'},
{word:'Analogous',meaning:'Comparable in certain respects; similar',antonym:'Different/dissimilar',usage:'The account aggregator model is analogous to open banking in Europe.'},
{word:'Anomaly',meaning:'Something that deviates from the expected norm',antonym:'Norm/standard',usage:'High inflation despite low growth was an economic anomaly.'},
{word:'Antipathy',meaning:'A deep-seated feeling of dislike; aversion',antonym:'Affinity/liking',usage:'Public antipathy toward loan sharks led to stricter microfinance regulation.'},
{word:'Approbation',meaning:'Approval or praise',antonym:'Disapproval/condemnation',usage:'The RBI Governor expressed approbation for banks\' digital initiative.'},
{word:'Arduous',meaning:'Involving or requiring strenuous effort; difficult',antonym:'Easy/effortless',usage:'The NPA resolution process was arduous, taking years under CDR.'},
{word:'Articulate',meaning:'Express fluently and coherently; (adj) having clear expression',antonym:'Inarticulate',usage:'The branch manager was articulate in explaining the loan terms to the farmer.'},
{word:'Assuage',meaning:'Make (an unpleasant feeling) less intense; soothe',antonym:'Aggravate/intensify',usage:'RBI\'s rate cut helped assuage market fears about economic slowdown.'},
{word:'Astute',meaning:'Having an ability to notice and understand things quickly; shrewdly perceptive',antonym:'Obtuse/foolish',usage:'The astute investor recognized the turnaround potential in the stressed bank.'},
{word:'Attrition',meaning:'Gradual reduction in strength/size through sustained process',antonym:'Augmentation',usage:'Staff attrition at private banks is a persistent challenge.'},
{word:'Audacious',meaning:'Showing a willingness to take bold risks; daring',antonym:'Timid/cautious',usage:'The audacious expansion plan of the NBFC ultimately led to its downfall.'},
{word:'Augment',meaning:'Make something greater by adding to it; increase',antonym:'Diminish/reduce',usage:'Technology augments banking reach without proportional cost increase.'},
{word:'Austere',meaning:'Severe or strict in manner; without luxury; economically restrained',antonym:'Lavish/indulgent',usage:'The government adopted austere fiscal measures to reduce the deficit.'},
{word:'Autonomous',meaning:'Having the freedom to act independently',antonym:'Dependent/controlled',usage:'RBI\'s monetary policy is autonomous from direct government instruction.'},
{word:'Bellwether',meaning:'A leader or indicator of trends; leading example',antonym:'Laggard/follower',usage:'SBI is a bellwether for the Indian banking sector\'s health.'},
{word:'Belligerent',meaning:'Hostile and aggressive; inclined to quarrel',antonym:'Peaceful/conciliatory',usage:'The belligerent borrower refused to cooperate with bank\'s recovery agent.'},
{word:'Beneficent',meaning:'Generous; doing good',antonym:'Malevolent/harmful',usage:'Government\'s beneficent schemes target upliftment of below-poverty-line population.'},
{word:'Boon',meaning:'A thing that is helpful; a benefit',antonym:'Bane/curse',usage:'UPI has been a boon for digital transactions in rural India.'},
{word:'Brevity',meaning:'Concise and exact use of words; shortness of time',antonym:'Verbosity/length',usage:'The circular was remarkable for its brevity yet comprehensiveness.'},
{word:'Burgeon',meaning:'Begin to grow or increase rapidly; flourish',antonym:'Decline/shrink',usage:'India\'s fintech sector has burgeoned in the last decade.'},
{word:'Buoyant',meaning:'Inclined to be cheerful; able to float; (market) showing a tendency to rise in prices',antonym:'Depressed/sinking',usage:'Credit growth remained buoyant despite global headwinds.'},
{word:'Cacophony',meaning:'A harsh, discordant mixture of sounds; (figurative) confused noise',antonym:'Harmony',usage:'Policy cacophony among regulators undermined market confidence.'},
{word:'Candid',meaning:'Truthful and straightforward; frank',antonym:'Deceitful/evasive',usage:'The MD was candid about the bank\'s NPA challenges in the press conference.'},
{word:'Capitulate',meaning:'Cease to resist; surrender',antonym:'Resist/persist',usage:'The promoter eventually capitulated and submitted the business plan for resolution.'},
{word:'Categorical',meaning:'Unambiguously explicit and direct; absolute',antonym:'Conditional/qualified',usage:'RBI was categorical that banks must comply with the new NPA recognition norms.'},
{word:'Caustic',meaning:'Able to burn or corrode; (of words) sharply critical',antonym:'Mild/gentle',usage:'The auditor\'s caustic report on the bank\'s governance shocked shareholders.'},
{word:'Charismatic',meaning:'Exercising a compelling charm that inspires devotion',antonym:'Unremarkable',usage:'The RBI Governor\'s charismatic communication calmed market anxieties.'},
{word:'Circumspect',meaning:'Wary and unwilling to take risks; careful to consider all consequences',antonym:'Reckless/impulsive',usage:'Banks must be circumspect about lending to highly leveraged borrowers.'},
{word:'Cognizant',meaning:'Having knowledge or awareness',antonym:'Ignorant/unaware',usage:'The bank was cognizant of the borrower\'s financial difficulties.'},
{word:'Commensurate',meaning:'Corresponding in size or degree; in proportion',antonym:'Disproportionate',usage:'Bank officer\'s salary must be commensurate with responsibility and performance.'},
{word:'Compliance',meaning:'Acting in accordance with rules or requests',antonym:'Non-compliance/defiance',usage:'Regulatory compliance has become the top priority for bank boards.'},
{word:'Conciliatory',meaning:'Intended or likely to make peace; reconciling',antonym:'Antagonistic',usage:'The regulator adopted a conciliatory tone while implementing the new norms.'},
{word:'Concomitant',meaning:'Naturally accompanying or associated; concurrent',antonym:'Separate/unrelated',usage:'High credit growth and concomitant NPA risk must be managed together.'},
{word:'Condescending',meaning:'Showing a patronizing feeling of superiority',antonym:'Respectful/humble',usage:'The bank officer\'s condescending attitude toward small borrowers prompted an RBI circular on fair treatment.'},
{word:'Confluence',meaning:'Junction of two or more rivers; the merging of multiple factors',antonym:'Divergence',usage:'A confluence of factors — rising rates, global slowdown, monsoon failure — stressed the sector.'},
{word:'Conjecture',meaning:'Formation of opinion without proof; guess',antonym:'Certainty/fact',usage:'Market participants engaged in conjecture about the next rate move before the MPC meeting.'},
{word:'Conspicuous',meaning:'Clearly visible; attracting notice',antonym:'Inconspicuous/subtle',usage:'The conspicuous absence of corporate investment despite low rates puzzled economists.'},
{word:'Contraction',meaning:'Decrease in size; economic downturn',antonym:'Expansion/growth',usage:'GDP contraction of 7.3% in 2020-21 was the worst in independent India\'s history.'},
{word:'Contrite',meaning:'Feeling or expressing remorse; penitent',antonym:'Unrepentant',usage:'The bank expressed contrite acknowledgment of its lapses in KYC compliance.'},
{word:'Contentious',meaning:'Causing or likely to cause argument; controversial',antonym:'Uncontroversial/harmonious',usage:'FRBM amendment remained contentious between government and fiscal hawks.'},
{word:'Convergence',meaning:'Coming together from different directions; tending toward same point',antonym:'Divergence',usage:'Global regulatory convergence through Basel III reduces regulatory arbitrage.'},
{word:'Corroborate',meaning:'Confirm or support a statement with evidence',antonym:'Contradict/refute',usage:'The auditor\'s findings corroborated the whistleblower\'s allegations.'},
{word:'Credence',meaning:'Belief in or acceptance of something as true',antonym:'Skepticism/disbelief',usage:'Successive missed targets gave little credence to the promoter\'s restructuring plan.'},
{word:'Culmination',meaning:'The highest or climactic point; the final result',antonym:'Beginning/inception',usage:'The RBI\'s financial stability report represents the culmination of year-long monitoring.'},
{word:'Dauntless',meaning:'Showing fearlessness and determination',antonym:'Cowardly/timid',usage:'The dauntless recovery officer tracked the absconding guarantor for 3 years.'},
{word:'Debacle',meaning:'A sudden, complete disaster or collapse',antonym:'Success/triumph',usage:'The PMC Bank debacle exposed weaknesses in cooperative bank supervision.'},
{word:'Decimate',meaning:'Kill or destroy a large proportion of; drastically reduce',antonym:'Multiply/expand',usage:'The COVID pandemic decimated MSME profits, leading to NPA spike.'},
{word:'Defer',meaning:'Put off action; postpone; (also) show respectful submission',antonym:'Expedite/advance',usage:'RBI deferred implementation of stricter provisioning norms by six months.'},
{word:'Delineate',meaning:'Describe or indicate precisely; mark the outline of',antonym:'Blur/confuse',usage:'The circular delineates permissible investments for payments banks.'},
{word:'Denounce',meaning:'Publicly declare as wrong or evil; condemn',antonym:'Praise/endorse',usage:'Opposition denounced the bank privatization plan as anti-people.'},
{word:'Deplore',meaning:'Feel or express strong disapproval of',antonym:'Applaud/approve',usage:'The committee deplored the bank\'s delay in recognizing stressed assets as NPAs.'},
{word:'Derogatory',meaning:'Showing a critical or disrespectful attitude',antonym:'Complimentary',usage:'Using derogatory language against loan defaulters violates RBI\'s fair practice code.'},
{word:'Deterrent',meaning:'A thing that discourages or prevents an action',antonym:'Incentive/encouragement',usage:'Strict penalties serve as a deterrent against KYC non-compliance.'},
{word:'Dictum',meaning:'A formal pronouncement from an authoritative source; a saying',antonym:'Suggestion/opinion',usage:'The court\'s dictum on wilful defaulter classification changed banking practices.'},
{word:'Diligent',meaning:'Careful and conscientious in one\'s work or duties',antonym:'Lazy/negligent',usage:'Diligent credit officers identify early warning signals of borrower stress.'},
{word:'Disarray',meaning:'Lack of order or organization; confusion',antonym:'Order/organization',usage:'The financial system was in disarray during the 2008 global crisis.'},
{word:'Discern',meaning:'Recognize or find out; perceive or understand',antonym:'Miss/overlook',usage:'The risk officer discerned red flags in the borrower\'s financials before others.'},
{word:'Discretion',meaning:'Freedom to decide what should be done; prudent behavior',antonym:'Indiscretion/compulsion',usage:'Bank managers have limited discretion in waiving processing fees.'},
{word:'Disparate',meaning:'Essentially different in kind; unlike',antonym:'Homogeneous/similar',usage:'India\'s disparate banking landscape ranges from global banks to tiny cooperative societies.'},
{word:'Dissent',meaning:'Hold or express opinions that differ from official position',antonym:'Concur/agree',usage:'One MPC member dissented from the majority decision to cut rates.'},
{word:'Divergent',meaning:'Tending to be different or develop in different directions',antonym:'Convergent/similar',usage:'Divergent growth paths: urban credit expansion vs rural credit stagnation.'},
{word:'Dubious',meaning:'Hesitant or doubting; not to be relied upon; suspect',antonym:'Reliable/trustworthy',usage:'The collateral documents appeared dubious, triggering an investigation.'},
{word:'Ebullience',meaning:'Cheerful enthusiasm; exuberance',antonym:'Despondency/gloom',usage:'Market ebullience following rate cuts can lead to asset bubbles.'},
{word:'Efficacy',meaning:'Ability to produce a desired or intended result',antonym:'Inefficacy/failure',usage:'The efficacy of monetary policy in stimulating growth is debated by economists.'},
{word:'Egregious',meaning:'Outstandingly bad; shocking',antonym:'Minor/acceptable',usage:'The bank\'s egregious violation of KYC norms warranted regulatory action.'},
{word:'Elusive',meaning:'Difficult to find, catch, or achieve',antonym:'Easily attained',usage:'Despite policy measures, credit growth to agriculture remained elusive.'},
{word:'Embezzle',meaning:'Steal or misappropriate funds in care',antonym:'Return/account properly',usage:'The branch manager embezzled depositors\' funds, triggering RBI action.'},
{word:'Eminent',meaning:'Respected; outstanding; prominent',antonym:'Obscure/unknown',usage:'Eminent economists were consulted before drafting the new monetary policy framework.'},
{word:'Empirical',meaning:'Based on observation or experience rather than theory',antonym:'Theoretical/abstract',usage:'Empirical evidence supports the link between financial inclusion and poverty reduction.'},
{word:'Enigmatic',meaning:'Difficult to interpret or understand; mysterious',antonym:'Clear/obvious',usage:'The central banker\'s enigmatic statement on rate trajectory confused markets.'},
{word:'Enumerate',meaning:'Mention a number of things one by one',antonym:'Summarize/generalize',usage:'The report enumerates the key risks facing the banking sector.'},
{word:'Ephemeral',meaning:'Lasting for a very short time; transitory',antonym:'Permanent/enduring',usage:'Market rally was ephemeral — indices fell sharply the next week.'},
{word:'Equivocal',meaning:'Open to more than one interpretation; ambiguous',antonym:'Unambiguous/clear',usage:'The regulator\'s equivocal stance on cryptocurrency confused industry participants.'},
{word:'Exacerbate',meaning:'Make a problem or situation worse',antonym:'Ameliorate/improve',usage:'Global commodity price rise exacerbated India\'s trade deficit.'},
{word:'Exorbitant',meaning:'Unreasonably high; excessive',antonym:'Reasonable/moderate',usage:'Banks charging exorbitant prepayment penalties was curbed by RBI.'},
{word:'Expedient',meaning:'Appropriate to a purpose; (n) a means of achieving result',antonym:'Principled/idealistic',usage:'Rate cuts were seen as politically expedient ahead of elections.'},
{word:'Explicit',meaning:'Stated clearly; leaving no room for doubt',antonym:'Implicit/vague',usage:'The Master Direction provides explicit guidance on NPA recognition.'},
{word:'Exuberant',meaning:'Filled with energy and enthusiasm',antonym:'Subdued/restrained',usage:'Exuberant credit growth in 2006-2010 planted seeds of the NPA crisis.'},
{word:'Facile',meaning:'Achieved easily and without effort; superficial',antonym:'Difficult/deep',usage:'The facile comparison between NBFC and bank regulation misses structural differences.'},
{word:'Fastidious',meaning:'Very attentive to accuracy and detail; difficult to please',antonym:'Careless/indifferent',usage:'The regulator\'s fastidious review uncovered multiple compliance violations.'},
{word:'Fledgling',meaning:'A person or organization that is immature or inexperienced; newly established',antonym:'Established/mature',usage:'Payments banks are fledgling institutions still finding their business model.'},
{word:'Formidable',meaning:'Inspiring fear or respect through being impressively large, powerful, or capable',antonym:'Weak/insignificant',usage:'India\'s forex reserves are a formidable buffer against external shocks.'},
{word:'Forthright',meaning:'Direct and outspoken; straightforward',antonym:'Evasive/indirect',usage:'The auditor was forthright about the deficiencies in the bank\'s risk management.'},
{word:'Frugal',meaning:'Sparing; economical with money or food; simple',antonym:'Extravagant/wasteful',usage:'India\'s frugal innovation in banking (USSD banking, low-cost ATMs) enables rural reach.'},
{word:'Fugitive',meaning:'Person who has fled, especially to escape legal action',antonym:'Law-abiding citizen',usage:'Vijay Mallya and Nirav Modi became fugitive economic offenders.'},
{word:'Gargantuan',meaning:'Enormous; gigantic',antonym:'Tiny/miniscule',usage:'India faces a gargantuan task of providing banking services to 1.4 billion people.'},
{word:'Germane',meaning:'Relevant to a subject under consideration',antonym:'Irrelevant/tangential',usage:'The report raised germane questions about regulatory overlap between RBI and SEBI.'},
{word:'Gravitas',meaning:'Dignity and seriousness of manner',antonym:'Frivolity/levity',usage:'The central banker\'s gravitas reassured markets during the crisis.'},
{word:'Gullible',meaning:'Easily persuaded to believe something; credulous',antonym:'Skeptical/wary',usage:'Gullible investors fell victim to the Ponzi scheme posing as a bank.'},
{word:'Hamper',meaning:'Hinder the movement or progress of',antonym:'Facilitate/assist',usage:'Red tape hampers credit flow to MSMEs.'},
{word:'Haphazard',meaning:'Lacking any obvious principle of organization; random',antonym:'Systematic/organized',usage:'Haphazard NPA recognition before the Asset Quality Review led to under-reporting.'},
{word:'Hegemony',meaning:'Leadership or dominance, especially of one state over others',antonym:'Equality/subordination',usage:'Dollar hegemony in international trade motivates India\'s push for rupee trade settlement.'},
{word:'Holistic',meaning:'Characterized by the treatment of the whole rather than parts',antonym:'Reductionist/partial',usage:'Holistic approach to financial inclusion addresses access, usage, and quality simultaneously.'},
{word:'Impasse',meaning:'A situation in which no progress is possible; a deadlock',antonym:'Breakthrough/resolution',usage:'The debt restructuring reached an impasse when promoter refused equity dilution.'},
{word:'Imperious',meaning:'Assuming power or authority without justification; arrogant',antonym:'Humble/submissive',usage:'The imperious bank chairman ignored the audit committee\'s warnings.'},
{word:'Impetuous',meaning:'Acting or done quickly without thought or care',antonym:'Cautious/deliberate',usage:'Impetuous lending decisions during the credit boom created massive NPAs.'},
{word:'Impunity',meaning:'Exemption from punishment or freedom from injurious consequences',antonym:'Accountability',usage:'Wilful defaulters operated with impunity before the Economic Offenders Act 2018.'},
{word:'Inadvertent',meaning:'Not resulting from or achieved through deliberate planning',antonym:'Deliberate/intentional',usage:'The bank\'s inadvertent release of customer data triggered DPDP Act enforcement.'},
{word:'Incipient',meaning:'In an initial stage; beginning to happen or develop',antonym:'Advanced/established',usage:'RBI detected incipient signs of stress in the NBFC sector early in 2018.'},
{word:'Incumbent',meaning:'Currently holding office; (n) current holder of office',antonym:'Challenger/newcomer',usage:'Incumbent banks face competition from fintech challengers.'},
{word:'Indeterminate',meaning:'Not exactly known, established, or defined',antonym:'Definite/precise',usage:'Timeline for NPA resolution remained indeterminate under CDR.'},
{word:'Insolvent',meaning:'Unable to pay debts as they become due; bankrupt',antonym:'Solvent',usage:'IBC 2016 provides a time-bound framework for resolving insolvent companies.'},
{word:'Intransigent',meaning:'Unwilling to change views or agree; stubborn',antonym:'Flexible/amenable',usage:'The intransigent promoter\'s refusal delayed NCLT proceedings by 2 years.'},
{word:'Intuitive',meaning:'Using or based on feeling or gut rather than deliberate reasoning',antonym:'Analytical/deliberate',usage:'AI credit scoring combines intuitive pattern recognition with analytical models.'},
{word:'Irrevocable',meaning:'Not able to be changed, reversed, or recovered; final',antonym:'Revocable/changeable',usage:'Payment guarantee is irrevocable — bank must pay regardless of customer\'s claim.'},
{word:'Jeopardize',meaning:'Put something into a situation of risk; endanger',antonym:'Protect/safeguard',usage:'Concentrated exposure to single sector jeopardizes bank\'s portfolio quality.'},
{word:'Judicious',meaning:'Having or showing good judgment; wise and careful',antonym:'Injudicious/rash',usage:'Judicious credit expansion — growing loans while monitoring quality — is the goal.'},
{word:'Lackluster',meaning:'Lacking in vitality, force, or conviction; dull',antonym:'Vibrant/dynamic',usage:'Lackluster private investment has constrained economic growth.'},
{word:'Legitimate',meaning:'Conforming to law or rules; able to be defended',antonym:'Illegitimate/illegal',usage:'Legitimate debt restructuring differs from fraudulent evergreening.'},
{word:'Lenient',meaning:'More merciful or tolerant than expected',antonym:'Strict/harsh',usage:'Critics argued that RBI was too lenient with failing cooperative banks.'},
{word:'Lucid',meaning:'Expressed clearly; easy to understand',antonym:'Opaque/muddled',usage:'Governor\'s post-policy press conference provided lucid communication of RBI\'s thinking.'},
{word:'Magnanimous',meaning:'Generous or forgiving, especially toward rival or enemy',antonym:'Petty/vengeful',usage:'Banks took a magnanimous view in restructuring loans during COVID distress.'},
{word:'Malevolent',meaning:'Having or showing desire to do evil or cause harm',antonym:'Benevolent/kind',usage:'Malevolent promoters stripped assets and fled, leaving behind NPAs.'},
{word:'Mandate',meaning:'Official or authoritative instruction; give authority to',antonym:'Suggestion/request',usage:'RBI\'s mandate includes price stability and financial stability.'},
{word:'Meager',meaning:'Lacking in quantity or quality; thin; inadequate',antonym:'Abundant/generous',usage:'Priority sector lending to small farmers often provides meager credit at usurious terms from moneylenders.'},
{word:'Meticulous',meaning:'Showing great attention to detail or being very careful and precise',antonym:'Careless/sloppy',usage:'Meticulous due diligence in credit appraisal prevents NPA formation.'},
{word:'Mitigate',meaning:'Lessen the gravity, seriousness, or painfulness of',antonym:'Aggravate/intensify',usage:'Diversification mitigates portfolio concentration risk.'},
{word:'Moderate',meaning:'Average in amount, intensity, quality; not extreme',antonym:'Extreme/radical',usage:'Moderate inflation of 4% is RBI\'s target — balancing purchasing power and growth.'},
{word:'Morass',meaning:'Complicated or confused situation; swamp',antonym:'Clear path/simple situation',usage:'The NPAs created a morass that took years to resolve.'},
{word:'Mundane',meaning:'Lacking interest or excitement; ordinary',antonym:'Extraordinary/unique',usage:'Behind the mundane task of deposit taking lies significant risk management complexity.'},
{word:'Nascent',meaning:'Just coming into existence and beginning to display signs of future potential',antonym:'Mature/established',usage:'India\'s nascent corporate bond market needs deeper liquidity.'},
{word:'Nefarious',meaning:'Wicked or criminal',antonym:'Virtuous/lawful',usage:'Nefarious loan fraud schemes target elderly customers with forged documents.'},
{word:'Neutral',meaning:'Not supporting either side; unbiased; (monetary policy stance)',antonym:'Hawkish/dovish',usage:'RBI maintained neutral monetary policy stance in the June 2025 policy review.'},
{word:'Nominal',meaning:'Existing in name only; very small; not adjusted for inflation',antonym:'Real/substantial',usage:'Nominal GDP includes inflation effect; real GDP removes it.'},
{word:'Nuance',meaning:'A subtle difference in meaning, opinion, or attitude',antonym:'Generalization/oversimplification',usage:'Monetary policy communication requires nuance to avoid market overreaction.'},
{word:'Obfuscate',meaning:'Make obscure, unclear, or unintelligible; confuse',antonym:'Clarify/illuminate',usage:'Complex derivative structures were used to obfuscate actual credit risk.'},
{word:'Obsolete',meaning:'No longer produced or used; outdated',antonym:'Current/modern',usage:'Cheque-based payment is becoming obsolete as UPI dominates.'},
{word:'Onerous',meaning:'Involving heavy obligations; burdensome',antonym:'Light/easy',usage:'Onerous compliance burden on smaller banks diverts resources from lending.'},
{word:'Opaque',meaning:'Not able to be seen through; not transparent',antonym:'Transparent/clear',usage:'Opaque NBFC balance sheets made risk assessment difficult.'},
{word:'Opportunistic',meaning:'Exploiting opportunities as they arise, without principle',antonym:'Principled/consistent',usage:'Opportunistic lending during economic peaks without risk assessment creates boom-bust cycles.'},
{word:'Ostensible',meaning:'Stated or appearing to be true, but not necessarily so',antonym:'Genuine/actual',usage:'The ostensible reason for the loan was working capital; actual end-use was equity investment.'},
{word:'Ostracize',meaning:'Exclude from a society or group',antonym:'Include/welcome',usage:'Wilful defaulters should be ostracized from credit markets as per RBI framework.'},
{word:'Overhaul',meaning:'Take apart and examine carefully; make changes to improve',antonym:'Maintain/preserve',usage:'The insolvency framework needed an overhaul, leading to IBC 2016.'},
{word:'Panacea',meaning:'A solution to all difficulties or diseases',antonym:'Partial solution',usage:'Fintech is not a panacea for all financial inclusion challenges.'},
{word:'Paradox',meaning:'Statement that contradicts itself but might be true',antonym:'Consistency',usage:'India\'s paradox: high savings rate but low financial inclusion.'},
{word:'Parity',meaning:'Equality; especially of pay, status, or treatment',antonym:'Disparity/inequality',usage:'Interest rate parity theory links exchange rates and interest differentials.'},
{word:'Pedantic',meaning:'Excessively concerned with minor details; overly formal',antonym:'Flexible/broad-minded',usage:'Pedantic interpretation of KYC rules can exclude genuine customers.'},
{word:'Penal',meaning:'Of or used for punishment; prohibitively expensive',antonym:'Rewarding/permissive',usage:'Penal interest rates on overdue payments incentivize timely repayment.'},
{word:'Pervasive',meaning:'Spreading widely throughout an area or group of people',antonym:'Localized/isolated',usage:'Digital payments have become pervasive across urban and semi-urban India.'},
{word:'Pragmatic',meaning:'Dealing with things sensibly and realistically; practical',antonym:'Idealistic/theoretical',usage:'RBI adopted a pragmatic approach to fintech regulation through the sandbox framework.'},
{word:'Precipitous',meaning:'Dangerously high or steep; (of action) done suddenly',antonym:'Gradual/gentle',usage:'Precipitous fall in rupee triggered emergency RBI intervention.'},
{word:'Predominant',meaning:'Present as the strongest or main element',antonym:'Minor/insignificant',usage:'Public sector banks remain predominant in Indian banking (60%+ market share).'},
{word:'Premature',meaning:'Occurring or done before the usual or proper time',antonym:'Timely/appropriate',usage:'Premature withdrawal of COVID stimulus hampered economic recovery.'},
{word:'Profligate',meaning:'Recklessly extravagant or wasteful; licentious',antonym:'Frugal/economical',usage:'Profligate spending without matching revenue creates unsustainable deficits.'},
{word:'Prolific',meaning:'Producing much; highly productive',antonym:'Unproductive/scarce',usage:'India is a prolific issuer of government securities to fund fiscal deficit.'},
{word:'Prudent',meaning:'Acting with or showing care and thought for the future',antonym:'Reckless/imprudent',usage:'Prudent lending practices require assessment of borrower\'s repayment capacity.'},
{word:'Punitive',meaning:'Inflicting or intended as punishment',antonym:'Lenient/permissive',usage:'Punitive charges on prepayment were banned by RBI for floating rate home loans.'},
{word:'Quintessential',meaning:'Representing the most perfect or typical example',antonym:'Atypical/uncharacteristic',usage:'SBI is the quintessential public sector bank in India.'},
{word:'Rampant',meaning:'Flourishing or spreading unchecked; unrestrained',antonym:'Controlled/checked',usage:'Rampant financial fraud led to Fugitive Economic Offenders Act 2018.'},
{word:'Rationalize',meaning:'Attempt to explain behavior with logical reasons; make more efficient by reducing redundancy',antonym:'Complicate/expand',usage:'Bank mergers rationalize branch networks and reduce overhead costs.'},
{word:'Recalcitrant',meaning:'Having an obstinately uncooperative attitude',antonym:'Cooperative/compliant',usage:'Recalcitrant promoters delay NPA resolution, costing banks more.'},
{word:'Reciprocal',meaning:'Given, felt, or done in return; mutual',antonym:'One-sided/unilateral',usage:'Reciprocal trade agreements between India and ASEAN benefit both sides.'},
{word:'Redundant',meaning:'Not needed; superfluous; (employment) dismissed as no longer needed',antonym:'Essential/necessary',usage:'Branch rationalization after bank mergers made some roles redundant.'},
{word:'Repudiate',meaning:'Refuse to accept or be associated with; deny',antonym:'Accept/acknowledge',usage:'The borrower repudiated the loan agreement, claiming misrepresentation.'},
{word:'Resilient',meaning:'Able to withstand or recover quickly from difficult conditions',antonym:'Fragile/vulnerable',usage:'Indian banks proved resilient during COVID with strong capital buffers.'},
{word:'Reticent',meaning:'Not revealing one\'s thoughts readily; reserved',antonym:'Forthcoming/communicative',usage:'The MPC minutes showed some members were reticent about immediate rate cuts.'},
{word:'Robust',meaning:'Strong and healthy; vigorous; (system) able to withstand stress',antonym:'Fragile/weak',usage:'Robust economic fundamentals support India\'s long-term growth story.'},
{word:'Rogue',meaning:'Acting in an unauthorized or deviant manner',antonym:'Compliant/legitimate',usage:'Rogue traders at banks have caused billions in unauthorized losses globally.'},
{word:'Salutary',meaning:'Producing good effects; beneficial',antonym:'Harmful/detrimental',usage:'The Asset Quality Review had a salutary effect on banking sector transparency.'},
{word:'Sanguine',meaning:'Optimistic, especially in difficult situations',antonym:'Pessimistic/gloomy',usage:'The Governor was sanguine about India\'s economic prospects for the next year.'},
{word:'Scrupulous',meaning:'Diligent, thorough, and attentive to details; having strong moral principles',antonym:'Dishonest/careless',usage:'Banks must be scrupulous in verifying KYC documents to prevent fraud.'},
{word:'Seminal',meaning:'Strongly influencing later developments; original and important',antonym:'Derivative/insignificant',usage:'The Narasimham Committee reports were seminal for Indian banking reform.'},
{word:'Somnolent',meaning:'Drowsy; sleepy; inducing drowsiness',antonym:'Alert/vibrant',usage:'The somnolent rural banking sector was awakened by Jan Dhan Yojana.'},
{word:'Specious',meaning:'Superficially plausible but actually wrong; misleading',antonym:'Genuine/sound',usage:'The promoter\'s specious argument for further credit was rejected by the bank.'},
{word:'Spurious',meaning:'Not genuine; false; (of offspring) illegitimate',antonym:'Genuine/authentic',usage:'Spurious KYC documents were submitted to open fraudulent accounts.'},
{word:'Stagnation',meaning:'Lack of activity, growth, or development',antonym:'Growth/dynamism',usage:'Economic stagnation combined with inflation creates the worst of both worlds.'},
{word:'Steadfast',meaning:'Resolutely firm and unwavering',antonym:'Wavering/inconsistent',usage:'RBI\'s steadfast commitment to inflation targeting has built monetary credibility.'},
{word:'Stringent',meaning:'Strict, precise, and exacting',antonym:'Lenient/flexible',usage:'Stringent AML norms require banks to file STRs for suspicious transactions.'},
{word:'Surmount',meaning:'Overcome a difficulty or obstacle',antonym:'Fail/succumb',usage:'India needs to surmount financial inclusion challenges through technology and policy.'},
{word:'Sycophantic',meaning:'Behaving or done in an obsequious way; flattering',antonym:'Honest/forthright',usage:'Sycophantic board members who didn\'t challenge management created governance failures.'},
{word:'Tangential',meaning:'Slightly connected or related; diverging from a direct course',antonym:'Central/relevant',usage:'Tangential issues distracted from the core NPA resolution strategy.'},
{word:'Tenacious',meaning:'Holding firmly to something; persistent; not easily releasing',antonym:'Giving up/weak',usage:'Recovery officers must be tenacious in pursuing defaulters.'},
{word:'Tenuous',meaning:'Very weak or slight; thin',antonym:'Strong/solid',usage:'The economic recovery remained tenuous, dependent on rural demand.'},
{word:'Torpid',meaning:'Mentally or physically inactive; lethargic',antonym:'Active/vibrant',usage:'Corporate investment remained torpid despite low interest rates.'},
{word:'Tractable',meaning:'Easy to deal with; manageable',antonym:'Intractable/difficult',usage:'Small NPAs are more tractable than large infrastructure loan defaults.'},
{word:'Transient',meaning:'Lasting only for a short time; temporary',antonym:'Permanent/enduring',usage:'RBI characterized food inflation as transient — not warranting monetary tightening.'},
{word:'Trite',meaning:'Overused and consequently of little impact; commonplace',antonym:'Fresh/original',usage:'Trite statements about financial inclusion mask the complexity of the challenge.'},
{word:'Ubiquitous',meaning:'Present, appearing, or found everywhere',antonym:'Rare/unusual',usage:'UPI has become ubiquitous in India\'s payment landscape.'},
{word:'Unconscionable',meaning:'Not right or reasonable; shockingly unfair or unjust',antonym:'Fair/equitable',usage:'Charging unconscionable interest rates to desperate borrowers is banned under Consumer Protection Act.'},
{word:'Unprecedented',meaning:'Never done or known before',antonym:'Common/usual',usage:'RBI\'s COVID relief measures were unprecedented in scope and speed.'},
{word:'Vacillate',meaning:'Waver between different opinions or actions; be indecisive',antonym:'Resolute/decisive',usage:'Banks that vacillate between restructuring and enforcement lose on both counts.'},
{word:'Verbose',meaning:'Using more words than needed; wordy',antonym:'Concise/succinct',usage:'Bank exam RC passages test ability to extract key ideas from verbose academic writing.'},
{word:'Vindicate',meaning:'Clear of blame or suspicion; show to be right',antonym:'Blame/condemn',usage:'GDP growth data vindicated RBI\'s decision to cut rates earlier.'},
{word:'Volatile',meaning:'Liable to change rapidly and unpredictably',antonym:'Stable/steady',usage:'Rupee has been volatile against dollar due to global risk-off sentiment.'},
{word:'Zealous',meaning:'Having great energy or enthusiasm for a cause or objective',antonym:'Apathetic/indifferent',usage:'The new RBI Governor was zealous about digital payment adoption.'}
]}};

// ═══ IMPORTANT DATA REFERENCE ═══
const KEY_DATA={
banking_rates:{
title:'Current Banking Rates & Key Figures (2024-25)',
data:[
{item:'Repo Rate',value:'6.25%',note:'Cut by 25 bps in Feb 2025 (first in 5 years)'},
{item:'Reverse Repo Rate',value:'3.35%',note:'Corridor floor; SDF rate (5.75%) is more relevant now'},
{item:'Standing Deposit Facility (SDF)',value:'6.00%',note:'25 bps below repo; banks park excess liquidity here'},
{item:'Marginal Standing Facility (MSF)',value:'6.50%',note:'25 bps above repo; emergency overnight borrowing'},
{item:'Bank Rate',value:'6.50%',note:'Same as MSF rate; for long-term advances'},
{item:'CRR',value:'4.00%',note:'No interest paid; direct liquidity control tool'},
{item:'SLR',value:'18.00%',note:'Banks can earn on govt securities; liquidity buffer'},
{item:'Inflation Target',value:'4% (±2%)',note:'CPI range: 2%-6%; RBI Act mandates this'},
{item:'CRAR Minimum',value:'9%',note:'Indian mandate is higher than Basel III\'s 8%'},
{item:'PSL Target',value:'40% of ANBC',note:'Agriculture 18%, Micro & Small 7.5%, Weaker sections 10%'},
{item:'Max DICGC Insurance',value:'₹5 lakh',note:'Per depositor per bank; raised from ₹1L in 2020'},
{item:'RTGS Minimum',value:'₹2 lakh',note:'No upper limit; 24×7 since December 2020'},
{item:'NEFT',value:'No minimum',note:'24×7, settled in half-hourly batches'},
{item:'IMPS',value:'₹5 lakh max',note:'Instant, 24×7×365'},
{item:'UPI Daily Limit',value:'₹1 lakh (₹5L some categories)',note:'₹5L for verified merchants; ₹2L for credit on UPI'},
{item:'Payments Bank Deposit Limit',value:'₹2 lakh',note:'Raised from ₹1L in October 2023'},
{item:'Gross NPA Ratio',value:'~3.2%',note:'March 2024; peak was 11.5% in March 2018'},
{item:'Net NPA Ratio',value:'~0.8%',note:'March 2024; significant improvement from 6.1% in 2018'},
{item:'CRAR Average (PSBs)',value:'~14.8%',note:'Well above 9% minimum'},
{item:'Credit Growth',value:'~14%',note:'FY24; bank credit crossed ₹160 lakh crore'},
]},
important_committees:{
title:'Key Banking & Financial Committees',
data:[
{committee:'Narasimham Committee I (1991)',recommendations:'Reduce CRR/SLR, deregulate interest rates, allow new private banks, strengthen supervision. Led to 1991 banking reforms.'},
{committee:'Narasimham Committee II (1998)',recommendations:'Capital adequacy norms, bank mergers, NPA definitions, phased reduction of NPA ratios. Post-Asian crisis review.'},
{committee:'Tarapore Committee (1997,2006)',recommendations:'Capital Account Convertibility roadmap — phased opening of capital account. Cautious approach due to macro prerequisites.'},
{committee:'Rajan Committee on Financial Sector Reforms (2008)',recommendations:'Universal Bank licensing, consumer protection, credit bureau development, financial inclusion innovations.'},
{committee:'Deepak Mohanty Committee (2015)',recommendations:'Medium-term priority sector lending policy, financial inclusion framework, credit guarantee mechanisms.'},
{committee:'P.J. Nayak Committee (2014)',recommendations:'Government ownership in PSBs should be reduced below 50%; independent bank board bureaus; governance reforms.'},
{committee:'Malegam Committee (2011)',recommendations:'Regulation of microfinance; capped interest rates and margins for MFIs; customer protection in microfinance.'},
{committee:'FSLRC (Financial Sector Legislative Reforms Commission, 2013)',recommendations:'Unified financial regulator for all non-banking sectors; consumer protection focus; merge SEBI, IRDA, PFRDA.'},
{committee:'Verma Committee on Weak Banks',recommendations:'Identified parameters for identifying weak banks; restructuring plan for weak PSBs.'},
{committee:'Khan Committee on MSMEs',recommendations:'Framework for MSME financing; early warning systems for MSME stress; supply chain financing.'},
{committee:'Internal Working Group on LCR (2019)',recommendations:'Standardized LCR reporting; liquidity risk management practices for banks.'},
]},
economic_survey_highlights:{
title:'Economic Survey & Budget Highlights (2024-25)',
data:[
{item:'GDP Growth FY24',value:'8.2%',note:'Fastest among major economies; driven by govt capex and services'},
{item:'GDP Growth FY25 Estimate',value:'6.4-6.8%',note:'Moderation from high base; NSO estimate 6.4%'},
{item:'India\'s GDP Size',value:'$3.73 trillion',note:'5th largest economy; will be 3rd by ~2030'},
{item:'Capital Expenditure FY25',value:'₹11.11 lakh crore',note:'3.4% of GDP; 17% higher than FY24'},
{item:'Fiscal Deficit FY25',value:'4.9% of GDP',note:'Down from 5.8% in FY23; path to 4.5% in FY26'},
{item:'Revenue Deficit FY25',value:'2.0% of GDP',note:'Improving due to higher tax revenue collection'},
{item:'Tax Revenue Growth FY24',value:'~18%',note:'GST crossed ₹20 lakh crore for first time'},
{item:'GST Collections FY24',value:'₹20.18 lakh crore',note:'Average ₹1.68 lakh crore per month in FY24'},
{item:'Disinvestment Target FY25',value:'₹50,000 crore',note:'Consistently missed in recent years'},
{item:'Subsidy Bill FY25',value:'₹3.81 lakh crore',note:'Food, fertilizer, petroleum subsidies combined'},
{item:'Interest Payment FY25',value:'₹11.63 lakh crore',note:'Largest single expenditure item; 3.3% of GDP'},
{item:'Manufacturing Share of GDP',value:'~17%',note:'Target to raise to 25% under Make in India 2.0'},
{item:'Services Share of GDP',value:'~55%',note:'IT/ITES, financial services, telecom key contributors'},
{item:'Agriculture Share of GDP',value:'~18%',note:'Employs ~47% workforce; low productivity gap is challenge'},
{item:'FDI Inflow FY24',value:'$44.4 billion',note:'Lower than FY23\'s $71.4B; services, IT, retail top sectors'},
{item:'Forex Reserves',value:'$640+ billion',note:'4th largest globally; ~10 months import cover'},
{item:'Current Account Deficit',value:'~0.9% of GDP',note:'Significantly improved from 2.7% in FY23'},
{item:'Exports FY24',value:'$776 billion',note:'Merchandise + Services combined'},
{item:'Unemployment Rate (PLFS)',value:'~7.2%',note:'Urban youth unemployment higher at ~17%'},
{item:'Power Sector Installed Capacity',value:'900+ GW target by 2032',note:'Current: 440 GW; Renewable: 140 GW'},
]}};
